"use client";

import {useEffect,useMemo,useState} from "react";
import {loadCurrentClientDashboard,resolveCurrentClientId,type BackendDashboard} from "@/lib/dashboard";
import {supabase} from "@/lib/supabase";

type Row=Record<string,unknown>;
type Review={habilitado:boolean;validated_at:string|null};
type Props={section:string};

const card="rounded-2xl border border-slate-200 bg-white shadow-sm";
const text=(v:unknown,f="—")=>v===null||v===undefined||String(v).trim()===""?f:String(v);
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};
const money=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)&&n>0?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n):"—"};
const status=(v:unknown)=>String(v??"").toLowerCase();

export default function ClientPortal({section}:Props){
 const[data,setData]=useState<BackendDashboard|null>(null),[review,setReview]=useState<Review|null>(null),[strategies,setStrategies]=useState<Row[]>([]),[enterprise,setEnterprise]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){if(!supabase)return;setLoading(true);setError("");try{const clientId=await resolveCurrentClientId();if(!clientId)throw new Error("Conta sem empresa associada.");const[d,r,s,e]=await Promise.all([loadCurrentClientDashboard(),supabase.from("client_habilitation_reviews").select("habilitado,validated_at").eq("client_id",clientId).maybeSingle(),supabase.from("dispute_strategies").select("id,opportunity_id,status,created_at,updated_at").eq("client_id",clientId).order("updated_at",{ascending:false}),supabase.from("client_enterprise_data").select("cnpj,legal_name,trade_name,headquarters_city,headquarters_state").eq("client_id",clientId).maybeSingle()]);if(r.error||s.error||e.error)throw r.error||s.error||e.error;setData(d);setReview((r.data??null) as Review|null);setStrategies((s.data??[]) as Row[]);setEnterprise((e.data??null) as Row|null)}catch(x){setError(x instanceof Error?x.message:String(x))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const opportunities=useMemo(()=>(data?.opportunities??[]) as Row[],[data]);
 const approved=useMemo(()=>opportunities.filter(o=>o.participation_allowed===true||["approved","analyzed"].includes(status(o.match_status))),[opportunities]);
 const opportunityById=useMemo(()=>new Map(opportunities.map(o=>[String(o.opportunity_id),o])),[opportunities]);
 const participations=useMemo(()=>strategies.filter(s=>!["won","lost","cancelled","closed"].includes(status(s.status))),[strategies]);
 const results=useMemo(()=>strategies.filter(s=>["won","lost","cancelled","closed"].includes(status(s.status))),[strategies]);
 if(loading)return <div className="p-8 text-sm text-slate-500">Carregando sua conta...</div>;
 if(error&&!data)return <div className="m-6 rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}<button onClick={()=>void load()} className="ml-3 font-bold underline">Tentar novamente</button></div>;
 const company=data?.client?.display_name||data?.client?.legal_name||text(enterprise?.trade_name,"Empresa");
 if(section==="Editais aprovados")return <List title="Editais aprovados" subtitle="Oportunidades aprovadas pelo UNI para sua empresa." rows={approved}/>;
 if(section==="Participações")return <StrategyList title="Participações" subtitle="Processos em andamento conduzidos pelo UNI." rows={participations} opportunities={opportunityById}/>;
 if(section==="Resultados")return <StrategyList title="Resultados" subtitle="Resultado das participações concluídas." rows={results} opportunities={opportunityById}/>;
 if(section==="Minha conta")return <main className="mx-auto max-w-[1200px] p-5"><Header title="Minha conta" subtitle="Informações básicas cadastradas no UNI."/><section className={`${card} mt-5 p-5`}><dl className="grid gap-5 sm:grid-cols-2"><Field label="Empresa" value={company}/><Field label="Razão social" value={text(enterprise?.legal_name,data?.client?.legal_name)}/><Field label="CNPJ" value={text(enterprise?.cnpj)}/><Field label="Sede" value={[enterprise?.headquarters_city,enterprise?.headquarters_state].filter(Boolean).join("/")||"—"}/><Field label="Situação no UNI" value={review?.habilitado?"Habilitado":"Aguardando habilitação"}/><Field label="Última validação" value={date(review?.validated_at)}/></dl></section></main>;
 return <main className="mx-auto max-w-[1400px] p-5"><Header title={company} subtitle="Acompanhe os editais aprovados, as participações e os resultados."/><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Situação" value={review?.habilitado?"Habilitado":"Aguardando"} tone={review?.habilitado?"green":"amber"}/><Metric label="Editais aprovados" value={approved.length}/><Metric label="Participações" value={participations.length}/><Metric label="Resultados" value={results.length}/></div><section className={`${card} mt-4 p-5`}><h2 className="font-black text-slate-900">Editais aprovados recentes</h2><div className="mt-3"><OpportunityTable rows={approved.slice(0,5)}/></div></section></main>;
}

function Header({title,subtitle}:{title:string;subtitle:string}){return <div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">UNI Licitações</p><h1 className="mt-1 text-3xl font-black text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>}
function Field({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-bold text-slate-800">{value}</dd></div>}
function Metric({label,value,tone="blue"}:{label:string;value:string|number;tone?:"blue"|"green"|"amber"}){const colors={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700"};return <div className={`${card} p-5`}><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${colors[tone]}`}>{label}</span><p className="mt-4 text-2xl font-black text-slate-900">{value}</p></div>}
function List({title,subtitle,rows}:{title:string;subtitle:string;rows:Row[]}){return <main className="mx-auto max-w-[1400px] p-5"><Header title={title} subtitle={subtitle}/><section className={`${card} mt-5 overflow-hidden`}><OpportunityTable rows={rows}/></section></main>}
function OpportunityTable({rows}:{rows:Row[]}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Processo</th><th>Órgão</th><th>Objeto</th><th>Prazo</th><th>Valor estimado</th></tr></thead><tbody>{rows.map((o,i)=><tr key={`${text(o.opportunity_id)}-${i}`} className="border-t border-slate-100"><td className="p-3 font-bold">{text(o.process_number)}</td><td>{text(o.buyer_name)}</td><td className="max-w-[360px]"><span className="line-clamp-2">{text(o.object_text,o.title as string)}</span></td><td>{date(o.proposal_deadline)}</td><td>{money(o.estimated_value)}</td></tr>)}{!rows.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhum registro disponível.</td></tr>}</tbody></table></div>}
function StrategyList({title,subtitle,rows,opportunities}:{title:string;subtitle:string;rows:Row[];opportunities:Map<string,Row>}){return <main className="mx-auto max-w-[1400px] p-5"><Header title={title} subtitle={subtitle}/><section className={`${card} mt-5 overflow-hidden`}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Processo</th><th>Órgão</th><th>Objeto</th><th>Status</th><th>Atualização</th></tr></thead><tbody>{rows.map((r,i)=>{const o=opportunities.get(String(r.opportunity_id))??{};return <tr key={`${text(r.id)}-${i}`} className="border-t border-slate-100"><td className="p-3 font-bold">{text(o.process_number)}</td><td>{text(o.buyer_name)}</td><td className="max-w-[360px]"><span className="line-clamp-2">{text(o.object_text,o.title as string)}</span></td><td><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{text(r.status,"Em andamento")}</span></td><td>{date(r.updated_at||r.created_at)}</td></tr>})}{!rows.length&&<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhum registro disponível.</td></tr>}</tbody></table></div></section></main>}
