"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BackendDashboard, loadCurrentClientDashboard } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";
import {
  AdvancedRadarFilters,
  canStartDetailedAnalysis,
  emptyAdvancedRadarFilters,
  errorMessage,
  TriageSnapshot,
  toAdvancedRadarRpcParams,
} from "./radar-utils";

type Opportunity = Record<string, unknown>;
type OpportunityDocument = { id:string; original_filename:string; validation_status:string; uploaded_at:string; file_size_bytes:number|null };
type TriageStage = { stage?:string; result?:string };
type DocumentSync = { status:"idle"|"running"|"complete"|"partial"|"manual_required"|"error"; found?:number; downloaded?:number; skipped?:number; failed?:number; reason?:string };
type Filters = { state:string; modality:string; lifecycle:string; match:string; deadline:string; minValue:string; maxValue:string };
const emptyFilters: Filters = { state:"", modality:"", lifecycle:"", match:"", deadline:"", minValue:"", maxValue:"" };
type ExplorerOpportunity = Opportunity & { total_count?:number; source_code?:string; source_name?:string; official_modality_code?:number|null; uasg?:string|null; agency_code?:number|null; agency_cnpj?:string|null; ibge_code?:number|null; pncp_updated_at?:string|null; legal_basis_code?:number|null; excluded?:boolean|null };

function text(value:unknown,fallback="—"){return value===null||value===undefined||value===""?fallback:String(value)}
function date(value:unknown,withTime=false){if(!value)return"—";const d=new Date(String(value));if(Number.isNaN(d.getTime()))return text(value);return new Intl.DateTimeFormat("pt-BR",withTime?{dateStyle:"short",timeStyle:"short"}:{dateStyle:"short"}).format(d)}
function money(value:unknown){const n=typeof value==="number"?value:Number(value);if(!Number.isFinite(n)||n<=0)return"Não informado";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n)}
function safeName(name:string){return name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"_")}
function opportunityId(o:Opportunity|null){return o?.opportunity_id?String(o.opportunity_id):""}
function capabilityId(o:Opportunity|null){return o?.capability_id?String(o.capability_id):""}
function fileMime(file:File){const n=file.name.toLowerCase();if(n.endsWith(".pdf"))return"application/pdf";if(n.endsWith(".zip"))return"application/zip";if(n.endsWith(".doc"))return"application/msword";if(n.endsWith(".docx"))return"application/vnd.openxmlformats-officedocument.wordprocessingml.document";if(n.endsWith(".xls"))return"application/vnd.ms-excel";if(n.endsWith(".xlsx"))return"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";return""}
function stageLabel(stage?:string){if(stage==="operational_prefilter")return"Filtro operacional";if(stage==="capability_match")return"Compatibilidade com o perfil";return stage?.replaceAll("_"," ")||"Etapa"}
function resultLabel(result?:string){const map:Record<string,string>={queued_for_ai:"APROVADO PARA ANÁLISE",filtered_out:"NÃO APROVADO NA TRIAGEM",matched:"COMPATÍVEL",not_filtered:"APROVADO",queued_for_analysis:"AGUARDANDO ANÁLISE DETALHADA",approved:"APROVADO",analyzed:"ANALISADO",candidate:"CANDIDATO",rejected:"NÃO APROVADO"};return map[result||""]||text(result,"EM ANÁLISE").replaceAll("_"," ").toUpperCase()}
function prettyKey(k:string){const map:Record<string,string>={matched_terms:"Termos compatíveis",excluded_terms:"Termos de exclusão",score:"Pontuação",reason:"Motivo",reasons:"Motivos",matched:"Compatibilidade",source:"Fonte"};return map[k]||k.replaceAll("_"," ").replace(/^./,c=>c.toUpperCase())}
function prettyReasons(value:unknown):string{if(!value)return"Nenhuma justificativa adicional registrada.";if(typeof value==="string")return value;if(Array.isArray(value))return value.map(prettyReasons).filter(Boolean).join(" · ");if(typeof value==="object")return Object.entries(value as Record<string,unknown>).map(([k,v])=>`${prettyKey(k)}: ${prettyReasons(v)}`).join(" · ");return String(value)}
function activeParticipationLabel(triage:TriageSnapshot|null){if(!triage)return"Ainda não avaliada";if(triage.participation_allowed===true)return"Liberada";if(triage.result==="filtered_out")return"Não liberada pela triagem";return"Ainda não liberada — análise em andamento"}

export default function Radar(){
  const [data,setData]=useState<BackendDashboard|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [filtersOpen,setFiltersOpen]=useState(false); const [draftFilters,setDraftFilters]=useState<Filters>(emptyFilters); const [filters,setFilters]=useState<Filters>(emptyFilters);
  const [selected,setSelected]=useState<Opportunity|null>(null); const [documents,setDocuments]=useState<OpportunityDocument[]>([]); const [docsLoading,setDocsLoading]=useState(false); const [uploading,setUploading]=useState(false); const [uploadMessage,setUploadMessage]=useState("");
  const [triageBusy,setTriageBusy]=useState(false); const [triage,setTriage]=useState<TriageSnapshot|null>(null); const [triageError,setTriageError]=useState(""); const [documentSync,setDocumentSync]=useState<DocumentSync>({status:"idle"});
  const [analysisBusy,setAnalysisBusy]=useState(false); const [analysisMessage,setAnalysisMessage]=useState(""); const [analysisQueued,setAnalysisQueued]=useState(false);
  const [advancedOpen,setAdvancedOpen]=useState(false); const [advancedDraft,setAdvancedDraft]=useState<AdvancedRadarFilters>(emptyAdvancedRadarFilters); const [advancedFilters,setAdvancedFilters]=useState<AdvancedRadarFilters>(emptyAdvancedRadarFilters);
  const [explorerRows,setExplorerRows]=useState<ExplorerOpportunity[]>([]); const [explorerPage,setExplorerPage]=useState(1); const [explorerTotal,setExplorerTotal]=useState(0); const [explorerLoading,setExplorerLoading]=useState(false); const [explorerSearched,setExplorerSearched]=useState(false); const [explorerError,setExplorerError]=useState(""); const explorerPageSize=50;
  const [referenceNow]=useState(Date.now);

  const refreshDashboard=useCallback(async(initial=false)=>{if(initial)setLoading(true);else setRefreshing(true);setError("");try{const result=await loadCurrentClientDashboard();if(!result)throw new Error("Nenhum ambiente empresarial foi associado ao usuário autenticado.");setData(result);return result}catch(e){setError(errorMessage(e));return null}finally{setLoading(false);setRefreshing(false)}},[]);
  useEffect(()=>{void refreshDashboard(true)},[refreshDashboard]);

  const rows=useMemo(()=>(data?.opportunities??[]) as Opportunity[],[data?.opportunities]);
  const clientId=data?.client?.id;
  const states=useMemo(()=>Array.from(new Set(rows.map(r=>text(r.state,"")).filter(Boolean))).sort(),[rows]);
  const modalities=useMemo(()=>Array.from(new Set(rows.map(r=>text(r.modality,"")).filter(Boolean))).sort(),[rows]);
  const matches=useMemo(()=>Array.from(new Set(rows.map(r=>text(r.match_status,"")).filter(Boolean))).sort(),[rows]);
  const activeFilterCount=Object.values(filters).filter(Boolean).length;
  const opportunities=useMemo(()=>{const q=query.trim().toLowerCase();const now=referenceNow;return rows.filter(row=>{
    if(q&&!([row.buyer_name,row.modality,row.process_number,row.title,row.object_text,row.city,row.state].map(v=>text(v,"").toLowerCase()).some(v=>v.includes(q))))return false;
    if(filters.state&&text(row.state,"")!==filters.state)return false;if(filters.modality&&text(row.modality,"")!==filters.modality)return false;if(filters.lifecycle&&text(row.lifecycle,"")!==filters.lifecycle)return false;if(filters.match&&text(row.match_status,"")!==filters.match)return false;
    const value=Number(row.estimated_value??0);if(filters.minValue&&value<Number(filters.minValue))return false;if(filters.maxValue&&value>Number(filters.maxValue))return false;
    if(filters.deadline&&typeof row.proposal_deadline==="string"){const diff=new Date(row.proposal_deadline).getTime()-now;const days=Number(filters.deadline);if(diff<0||diff>days*86400000)return false}else if(filters.deadline)return false;
    return true;});},[rows,query,filters,referenceNow]);

  const searchAdvanced=useCallback(async(nextFilters:AdvancedRadarFilters,nextPage=1)=>{if(!supabase||!clientId){setExplorerError("A pesquisa exige um ambiente empresarial autenticado.");return}setExplorerLoading(true);setExplorerSearched(true);setExplorerError("");try{const{data:result,error:searchError}=await supabase.rpc("search_radar_opportunities",toAdvancedRadarRpcParams(clientId,nextFilters,nextPage,explorerPageSize));if(searchError)throw searchError;const found=(result??[]) as ExplorerOpportunity[];setAdvancedFilters(nextFilters);setExplorerRows(found);setExplorerPage(nextPage);setExplorerTotal(Number(found[0]?.total_count??0));}catch(e){setExplorerRows([]);setExplorerTotal(0);setExplorerError(`A pesquisa não pôde ser concluída: ${errorMessage(e)}`)}finally{setExplorerLoading(false)}},[clientId]);

  async function loadDocuments(opportunity:Opportunity){const oid=opportunityId(opportunity);if(!supabase||!data?.client?.id||!oid)return;setDocsLoading(true);try{const{data:docs,error:e}=await supabase.from("opportunity_documents").select("id,original_filename,validation_status,uploaded_at,file_size_bytes").eq("client_id",data.client.id).eq("opportunity_id",oid).eq("validation_status","available").order("uploaded_at",{ascending:false});if(e)throw e;setDocuments((docs??[]) as OpportunityDocument[])}catch(e){setUploadMessage(`Não foi possível consultar os anexos: ${errorMessage(e)}`)}finally{setDocsLoading(false)}}

  async function runTriage(opportunity:Opportunity):Promise<TriageSnapshot>{if(!supabase)throw new Error("Conexão com o backend indisponível.");const oid=opportunityId(opportunity),cid=capabilityId(opportunity);if(!oid||!cid)throw new Error("A oportunidade ainda não possui identidade operacional suficiente para executar a triagem.");setTriageBusy(true);setTriageError("");try{const{data:result,error:runError}=await supabase.rpc("run_deterministic_triage",{p_capability_id:cid,p_opportunity_id:oid});if(runError)throw runError;const[runResponse,matchResponse]=await Promise.all([supabase.from("opportunity_triage_runs").select("result,stages,created_at,run_sequence").eq("capability_id",cid).eq("opportunity_id",oid).order("run_sequence",{ascending:false}).limit(1).maybeSingle(),supabase.from("client_opportunity_matches").select("match_status,deterministic_score,deterministic_reasons,participation_allowed").eq("capability_id",cid).eq("opportunity_id",oid).limit(1).maybeSingle()]);if(runResponse.error)throw runResponse.error;if(matchResponse.error)throw matchResponse.error;const run=runResponse.data as {result?:string;stages?:TriageStage[];created_at?:string}|null;const match=matchResponse.data as {match_status?:string;deterministic_score?:number|null;deterministic_reasons?:unknown;participation_allowed?:boolean}|null;const snapshot:TriageSnapshot={result:String(run?.result??result??"unknown"),stages:Array.isArray(run?.stages)?run!.stages!:[],created_at:run?.created_at,match_status:match?.match_status,deterministic_score:match?.deterministic_score??null,deterministic_reasons:match?.deterministic_reasons,participation_allowed:match?.participation_allowed};setTriage(snapshot);await refreshDashboard();return snapshot}catch(e){const msg=errorMessage(e);setTriageError(`A triagem não pôde ser concluída: ${msg}`);throw e}finally{setTriageBusy(false)}}

  async function syncPncpDocuments(opportunity:Opportunity){if(!supabase||!data?.client?.id)return;const oid=opportunityId(opportunity);if(!oid)return;setDocumentSync({status:"running"});try{const{data:result,error:e}=await supabase.functions.invoke("opportunity-document-sync",{body:{client_id:data.client.id,opportunity_id:oid}});if(e)throw e;const s=result?.status;const status:DocumentSync["status"]=s==="complete"||s==="partial"||s==="manual_required"?s:"error";setDocumentSync({status,found:Number(result?.found??0),downloaded:Number(result?.downloaded??0),skipped:Number(result?.skipped??0),failed:Number(result?.failed??0),reason:result?.reason?String(result.reason):undefined});await loadDocuments(opportunity)}catch(e){setDocumentSync({status:"error",reason:errorMessage(e)});await loadDocuments(opportunity)}}

  function openOpportunity(opportunity:Opportunity){setSelected(opportunity);setDocuments([]);setUploadMessage("");setAnalysisMessage("");setAnalysisQueued(false);setTriage(null);setTriageError("");setDocumentSync({status:"idle"});void Promise.allSettled([runTriage(opportunity),syncPncpDocuments(opportunity)])}

  async function uploadFiles(files:File[]){const oid=opportunityId(selected);if(!files.length||!supabase||!data?.client?.id||!selected||!oid)return;setUploading(true);setUploadMessage(`${files.length} arquivo(s) selecionado(s). Enviando...`);try{const{data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw new Error("Sessão não autenticada.");let completed=0;for(const file of files){if(file.size>50*1024*1024)throw new Error(`${file.name}: o arquivo excede o limite de 50 MB.`);const mime=fileMime(file);if(!mime)throw new Error(`${file.name}: formato não permitido.`);setUploadMessage(`Enviando ${completed+1} de ${files.length}: ${file.name}`);const path=`${data.client.id}/${oid}/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${safeName(file.name)}`;const{error:storageError}=await supabase.storage.from("opportunity-documents").upload(path,file,{upsert:false,contentType:mime,cacheControl:"3600"});if(storageError)throw new Error(`Falha no armazenamento de ${file.name}: ${errorMessage(storageError)}`);const{error:dbError}=await supabase.from("opportunity_documents").insert({client_id:data.client.id,opportunity_id:oid,storage_bucket:"opportunity-documents",storage_path:path,original_filename:file.name,mime_type:mime,file_size_bytes:file.size,source_kind:"user_upload",validation_status:"available",uploaded_by:auth.user.id,metadata:{origin:"pncp_fallback_manual_upload"}});if(dbError){await supabase.storage.from("opportunity-documents").remove([path]);throw new Error(`Falha ao registrar ${file.name}: ${errorMessage(dbError)}`)}completed++}setUploadMessage(`${completed} arquivo(s) anexado(s) com sucesso.`);await loadDocuments(selected)}catch(e){setUploadMessage(errorMessage(e))}finally{setUploading(false)}}

  async function startDetailedAnalysis(){if(!supabase||!selected)return;const oid=opportunityId(selected),cid=capabilityId(selected);if(!oid||!cid){setAnalysisMessage("A oportunidade não possui identidade operacional suficiente para iniciar a análise.");return}if(!triage||triage.result!=="queued_for_ai"){setAnalysisMessage("A Análise Detalhada só pode ser solicitada após aprovação na triagem preliminar.");return}if(documents.length===0){setAnalysisMessage("Ainda não há documentos disponíveis. Aguarde o download automático ou anexe o edital/TR.");return}setAnalysisBusy(true);setAnalysisMessage("Registrando a solicitação na fila do UNI...");try{const{data:queueId,error:e}=await supabase.rpc("enqueue_opportunity_ai_analysis",{p_capability_id:cid,p_opportunity_id:oid,p_prompt_master_version:"Prompt Mestre v1.17"});if(e)throw e;setAnalysisQueued(true);setAnalysisMessage(`Análise detalhada solicitada. Execução ${String(queueId).slice(0,8)}… registrada com o Prompt Mestre v1.17. Aguardando o executor do UNI.`);await refreshDashboard()}catch(e){setAnalysisQueued(false);setAnalysisMessage(`Não foi possível solicitar a análise detalhada: ${errorMessage(e)}`)}finally{setAnalysisBusy(false)}}

  const approvedForAnalysis=triage?.result==="queued_for_ai";const detailedAnalysisReady=canStartDetailedAnalysis({triage,documentCount:documents.length,analysisBusy,triageBusy});
  const syncMessage=documentSync.status==="running"?"Localizando e baixando os documentos oficiais no PNCP...":documentSync.status==="complete"?`Download concluído: ${documentSync.downloaded??0} novo(s), ${documentSync.skipped??0} já existente(s).`:documentSync.status==="partial"?`Download parcial: ${documentSync.downloaded??0} obtido(s), ${documentSync.failed??0} falha(s). Complete manualmente se necessário.`:documentSync.status==="manual_required"?"Os anexos não puderam ser obtidos automaticamente. Use a fonte oficial e o upload manual.":documentSync.status==="error"?"A tentativa automática falhou. A contingência manual está disponível.":"A tentativa automática será executada ao abrir a oportunidade.";

  return <div className="px-4 py-6 sm:px-6 xl:px-8"><div className="mx-auto max-w-[1540px]">
    <div className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Monitoramento personalizado</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Radar de Licitações</h1><p className="mt-1 text-sm text-slate-500">Oportunidades vinculadas ao perfil de capacidade do ambiente autenticado.</p></div><div className="flex w-full flex-wrap gap-2 xl:max-w-2xl"><div className="min-w-[260px] flex-1"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar órgão, processo, objeto, cidade..." className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100"/></div><button type="button" onClick={()=>setFiltersOpen(v=>!v)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${filtersOpen||activeFilterCount?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200 bg-white text-slate-700"}`}>☷ Filtros{activeFilterCount?` (${activeFilterCount})`:""}</button><button type="button" onClick={()=>void refreshDashboard()} disabled={refreshing} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 disabled:opacity-50">{refreshing?"Atualizando...":"Atualizar"}</button></div></div>

    <section className="mb-4 rounded-2xl border border-blue-100 bg-blue-50/60 p-4">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Pesquisa exploratória</p><h2 className="mt-1 font-bold text-slate-900">Filtros oficiais do Compras.gov.br e filtros avançados do UNI</h2><p className="mt-1 text-xs text-slate-600">Consulta a base oficial já coletada. Não altera nem substitui o monitoramento automático orientado pelo Perfil de Capacidade do CNPJ.</p></div><button type="button" onClick={()=>setAdvancedOpen(v=>!v)} className="self-start rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-semibold text-blue-700">{advancedOpen?"Fechar pesquisa":"Abrir pesquisa avançada"}</button></div>
      {advancedOpen&&<div className="mt-4 space-y-4 border-t border-blue-100 pt-4">
        <div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Filtros principais do UNI</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <input value={advancedDraft.query} onChange={e=>setAdvancedDraft({...advancedDraft,query:e.target.value})} placeholder="Objeto ou palavra-chave" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input value={advancedDraft.processNumber} onChange={e=>setAdvancedDraft({...advancedDraft,processNumber:e.target.value})} placeholder="Número do processo" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input value={advancedDraft.buyerName} onChange={e=>setAdvancedDraft({...advancedDraft,buyerName:e.target.value})} placeholder="Órgão/comprador" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input value={advancedDraft.city} onChange={e=>setAdvancedDraft({...advancedDraft,city:e.target.value})} placeholder="Município" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <select aria-label="UF da pesquisa avançada" value={advancedDraft.state} onChange={e=>setAdvancedDraft({...advancedDraft,state:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Todas as UFs</option>{["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"].map(v=><option key={v}>{v}</option>)}</select>
          <select aria-label="Fonte oficial" value={advancedDraft.source} onChange={e=>setAdvancedDraft({...advancedDraft,source:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Todas as fontes</option><option value="compras_gov_br">Compras.gov.br</option><option value="pncp">PNCP</option><option value="cptm_portal">CPTM</option></select>
          <select aria-label="Situação da oportunidade" value={advancedDraft.lifecycle} onChange={e=>setAdvancedDraft({...advancedDraft,lifecycle:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Ativas, históricas e sem prazo</option><option value="live">Ativas</option><option value="historical">Históricas</option><option value="unknown">Sem prazo definido</option></select>
          <select aria-label="Liberação para participação" value={advancedDraft.participation} onChange={e=>setAdvancedDraft({...advancedDraft,participation:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Qualquer situação de participação</option><option value="released">Participação liberada</option><option value="blocked">Participação não liberada</option></select>
          <input type="number" min="0" value={advancedDraft.minValue} onChange={e=>setAdvancedDraft({...advancedDraft,minValue:e.target.value})} placeholder="Valor mínimo (R$)" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input type="number" min="0" value={advancedDraft.maxValue} onChange={e=>setAdvancedDraft({...advancedDraft,maxValue:e.target.value})} placeholder="Valor máximo (R$)" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
        </div></div>
        <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-bold text-slate-700">Filtros oficiais avançados do Compras.gov.br</summary><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <label className="text-xs font-semibold text-slate-600">Publicação inicial<input type="date" value={advancedDraft.publicationStart} onChange={e=>setAdvancedDraft({...advancedDraft,publicationStart:e.target.value})} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal"/></label>
          <label className="text-xs font-semibold text-slate-600">Publicação final<input type="date" value={advancedDraft.publicationEnd} onChange={e=>setAdvancedDraft({...advancedDraft,publicationEnd:e.target.value})} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal"/></label>
          <input inputMode="numeric" value={advancedDraft.modalityCode} onChange={e=>setAdvancedDraft({...advancedDraft,modalityCode:e.target.value})} placeholder="Código da modalidade" className="self-end rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input inputMode="numeric" value={advancedDraft.uasg} onChange={e=>setAdvancedDraft({...advancedDraft,uasg:e.target.value})} placeholder="Unidade / UASG" className="self-end rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input inputMode="numeric" value={advancedDraft.agencyCode} onChange={e=>setAdvancedDraft({...advancedDraft,agencyCode:e.target.value})} placeholder="Código do órgão" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input inputMode="numeric" value={advancedDraft.agencyCnpj} onChange={e=>setAdvancedDraft({...advancedDraft,agencyCnpj:e.target.value})} placeholder="CNPJ do órgão" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <input inputMode="numeric" value={advancedDraft.ibgeCode} onChange={e=>setAdvancedDraft({...advancedDraft,ibgeCode:e.target.value})} placeholder="Código IBGE do município" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <label className="text-xs font-semibold text-slate-600">Atualizada no PNCP após<input type="datetime-local" value={advancedDraft.pncpUpdatedAfter} onChange={e=>setAdvancedDraft({...advancedDraft,pncpUpdatedAfter:e.target.value})} className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal"/></label>
          <input inputMode="numeric" value={advancedDraft.legalBasisCode} onChange={e=>setAdvancedDraft({...advancedDraft,legalBasisCode:e.target.value})} placeholder="Código do amparo legal PNCP" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>
          <select aria-label="Contratação excluída" value={advancedDraft.excluded} onChange={e=>setAdvancedDraft({...advancedDraft,excluded:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="false">Somente não excluídas</option><option value="">Todas</option><option value="true">Somente excluídas</option></select>
        </div></details>
        <div className="flex flex-wrap justify-end gap-2"><button type="button" onClick={()=>{setAdvancedDraft(emptyAdvancedRadarFilters);setAdvancedFilters(emptyAdvancedRadarFilters);setExplorerRows([]);setExplorerTotal(0);setExplorerSearched(false);setExplorerError("")}} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">Limpar</button><button type="button" onClick={()=>void searchAdvanced(advancedDraft,1)} disabled={explorerLoading} className="rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{explorerLoading?"Pesquisando...":"Pesquisar base oficial"}</button></div>
        {explorerError&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{explorerError}</div>}
        {(explorerLoading||explorerSearched)&&<div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-3"><p className="text-sm font-bold text-slate-700">Resultados oficiais</p><span className="text-xs text-slate-500">{explorerTotal} encontrado(s) · página {explorerPage}</span></div>{explorerLoading?<p className="p-5 text-sm text-slate-500">Consultando a base normalizada...</p>:explorerRows.length===0?<p className="p-5 text-sm text-slate-500">Nenhuma oportunidade encontrada com os filtros aplicados.</p>:<div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Fonte","Órgão","Modalidade","Processo","Objeto","Local","Publicação","Prazo","Valor","Ação"].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{explorerRows.map((row,index)=><tr key={text(row.opportunity_id,String(index))}><td className="px-4 py-3 font-semibold">{text(row.source_name??row.source_code)}</td><td className="px-4 py-3">{text(row.buyer_name)}</td><td className="px-4 py-3">{text(row.modality)}</td><td className="px-4 py-3">{text(row.process_number)}</td><td className="max-w-[340px] px-4 py-3"><div className="line-clamp-2">{text(row.object_text??row.title)}</div></td><td className="px-4 py-3">{[text(row.city,""),text(row.state,"")].filter(Boolean).join("/")||"—"}</td><td className="px-4 py-3">{date(row.publication_date)}</td><td className="px-4 py-3">{date(row.proposal_deadline,true)}</td><td className="px-4 py-3">{money(row.estimated_value)}</td><td className="px-4 py-3">{row.source_url?<a href={String(row.source_url)} target="_blank" rel="noreferrer" className="font-semibold text-blue-700 underline">Fonte oficial</a>:"—"}</td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2 border-t border-slate-100 p-3"><button type="button" disabled={explorerLoading||explorerPage<=1} onClick={()=>void searchAdvanced(advancedFilters,explorerPage-1)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40">Anterior</button><button type="button" disabled={explorerLoading||explorerPage*explorerPageSize>=explorerTotal} onClick={()=>void searchAdvanced(advancedFilters,explorerPage+1)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40">Próxima</button></div></div>}
      </div>}
    </section>

    {filtersOpen&&<section className="mb-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><select value={draftFilters.state} onChange={e=>setDraftFilters({...draftFilters,state:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Todos os estados</option>{states.map(v=><option key={v}>{v}</option>)}</select><select value={draftFilters.modality} onChange={e=>setDraftFilters({...draftFilters,modality:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Todas as modalidades</option>{modalities.map(v=><option key={v}>{v}</option>)}</select><select value={draftFilters.lifecycle} onChange={e=>setDraftFilters({...draftFilters,lifecycle:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Ativas e históricas</option><option value="live">Ativas</option><option value="historical">Históricas</option></select><select value={draftFilters.match} onChange={e=>setDraftFilters({...draftFilters,match:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Todos os status</option>{matches.map(v=><option key={v} value={v}>{resultLabel(v)}</option>)}</select><select value={draftFilters.deadline} onChange={e=>setDraftFilters({...draftFilters,deadline:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Qualquer prazo</option><option value="3">Próximos 3 dias</option><option value="7">Próximos 7 dias</option><option value="15">Próximos 15 dias</option><option value="30">Próximos 30 dias</option></select><input type="number" min="0" placeholder="Valor mínimo (R$)" value={draftFilters.minValue} onChange={e=>setDraftFilters({...draftFilters,minValue:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><input type="number" min="0" placeholder="Valor máximo (R$)" value={draftFilters.maxValue} onChange={e=>setDraftFilters({...draftFilters,maxValue:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><div className="flex gap-2"><button type="button" onClick={()=>{setDraftFilters(emptyFilters);setFilters(emptyFilters)}} className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-600">Limpar</button><button type="button" onClick={()=>{setFilters(draftFilters);setFiltersOpen(false)}} className="flex-1 rounded-xl bg-blue-700 px-3 py-2.5 text-sm font-semibold text-white">Aplicar</button></div></div></section>}

    {error&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><span>{error}</span><button type="button" onClick={()=>void refreshDashboard(true)} className="font-semibold underline">Tentar novamente</button></div>}
    <div className="mb-4 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-bold">{Number(data?.summary?.live_count??0)}</div><div className="text-sm text-slate-500">Oportunidades ativas</div></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-bold">{Number(data?.summary?.historical_count??0)}</div><div className="text-sm text-slate-500">Históricas</div></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-bold">{Number(data?.summary?.released_for_participation_count??0)}</div><div className="text-sm text-slate-500">Liberadas para participação</div></div></div>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold">Oportunidades</h2><p className="mt-1 text-xs text-slate-400">Resultados já associados ao perfil do cliente.</p></div><span className="text-xs text-slate-500">{opportunities.length} exibida(s)</span></div>{loading?<div className="p-8 text-sm text-slate-500">Carregando oportunidades...</div>:opportunities.length===0?<div className="p-8 text-sm text-slate-500">Nenhuma oportunidade encontrada para os filtros atuais.</div>:<div className="overflow-x-auto"><table className="min-w-[1120px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Órgão","Modalidade","Processo","Objeto","Local","Publicação","Prazo","Valor estimado","Situação","Ação"].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{opportunities.map((row,index)=>{const lifecycle=text(row.lifecycle,"unknown"),released=Boolean(row.participation_allowed??false);return <tr key={text(row.opportunity_id,String(index))} className="hover:bg-slate-50/70"><td className="px-5 py-3 font-semibold">{text(row.buyer_name)}</td><td className="px-5 py-3 text-slate-600">{text(row.modality)}</td><td className="px-5 py-3 text-slate-600">{text(row.process_number)}</td><td className="max-w-[360px] px-5 py-3 text-slate-600"><div className="line-clamp-2">{text(row.object_text??row.title)}</div></td><td className="px-5 py-3 text-slate-600">{[text(row.city,""),text(row.state,"")].filter(Boolean).join("/")||"—"}</td><td className="px-5 py-3 text-slate-600">{date(row.publication_date)}</td><td className="px-5 py-3 text-slate-600">{date(row.proposal_deadline,true)}</td><td className="px-5 py-3 text-slate-600">{money(row.estimated_value)}</td><td className="px-5 py-3"><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${released?"bg-emerald-50 text-emerald-700":lifecycle==="live"?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-600"}`}>{released?"Liberada":lifecycle==="live"?"Ativa":"Histórica"}</span></td><td className="px-5 py-3"><button type="button" onClick={()=>openOpportunity(row)} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 font-semibold text-blue-700 hover:bg-blue-100">Abrir</button></td></tr>})}</tbody></table></div>}</section>

    {selected&&<section className="mt-4 space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Triagem preliminar</p><h2 className="mt-1 text-xl font-bold">{text(selected.buyer_name)} · {text(selected.process_number)}</h2><p className="mt-2 max-w-5xl text-sm text-slate-600">{text(selected.object_text??selected.title)}</p></div><button type="button" onClick={()=>setSelected(null)} className="self-start rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">Fechar</button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase text-slate-400">Modalidade</p><p className="mt-1 text-sm font-semibold">{text(selected.modality)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase text-slate-400">Local</p><p className="mt-1 text-sm font-semibold">{[text(selected.city,""),text(selected.state,"")].filter(Boolean).join("/")||"—"}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase text-slate-400">Prazo</p><p className="mt-1 text-sm font-semibold">{date(selected.proposal_deadline,true)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase text-slate-400">Valor estimado</p><p className="mt-1 text-sm font-semibold">{money(selected.estimated_value)}</p></div></div>
      <div className="mt-4 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Resultado da triagem</h3><p className="text-xs text-slate-500">Executada automaticamente ao abrir a oportunidade.</p></div>{triageBusy?<span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">TRIANDO...</span>:triage?<span className={`rounded-lg px-3 py-2 text-xs font-bold ${triage.result==="filtered_out"?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{resultLabel(triage.result)}</span>:null}</div>{triageError&&<div className="mt-3 rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{triageError}</div>}{triage&&<div className="mt-4 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-2 text-sm text-slate-600"><p><strong className="text-slate-800">Status operacional:</strong> {resultLabel(triage.result)}</p><p><strong className="text-slate-800">Compatibilidade:</strong> {resultLabel(triage.match_status)}</p><p><strong className="text-slate-800">Score determinístico:</strong> {triage.deterministic_score??"—"}</p><p><strong className="text-slate-800">Participação:</strong> {activeParticipationLabel(triage)}</p><p><strong className="text-slate-800">Execução:</strong> {date(triage.created_at,true)}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Etapas e fundamentos</p><div className="mt-2 space-y-2">{triage.stages.map((s,i)=><div key={`${s.stage}-${i}`} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-xs"><span className="font-semibold text-slate-700">{stageLabel(s.stage)}</span><span className="font-bold text-slate-600">{resultLabel(s.result)}</span></div>)}<div className="rounded-lg bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600"><strong>Justificativas:</strong> {prettyReasons(triage.deterministic_reasons)}</div></div></div></div>}
      {approvedForAnalysis&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-emerald-800">Aprovada para Análise Detalhada</p><p className="mt-1 text-xs text-emerald-700">A solicitação pode ser registrada quando houver documentos disponíveis.</p></div><button type="button" onClick={()=>void startDetailedAnalysis()} disabled={!detailedAnalysisReady} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-emerald-300">{analysisBusy?"Registrando...":documents.length?"Iniciar Análise Detalhada":"Aguardando documentos"}</button></div></div>}</div></div>

      <div className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Fonte oficial</h3><p className="mt-2 text-sm text-slate-600">O UNI tenta obter automaticamente os documentos do PNCP e mantém contingência manual quando necessário.</p><div className={`mt-4 rounded-lg border p-3 text-xs ${documentSync.status==="complete"?"border-emerald-200 bg-emerald-50 text-emerald-800":documentSync.status==="running"?"border-blue-200 bg-blue-50 text-blue-800":"border-amber-200 bg-amber-50 text-amber-800"}`}><strong>Documentos:</strong> {syncMessage}{documentSync.reason&&<div className="mt-1 opacity-75">Diagnóstico: {documentSync.reason}</div>}</div>{selected.source_url?<a href={String(selected.source_url)} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Abrir fonte oficial ↗</a>:<p className="mt-4 text-sm font-semibold text-amber-700">Link oficial não disponível.</p>}<div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><strong>Contingência:</strong> falha no download não encerra o fluxo; os documentos podem ser anexados manualmente.</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Anexos do edital</h3><p className="mt-1 text-sm text-slate-500">PDF, ZIP, DOC/DOCX ou XLS/XLSX. Limite de 50 MB por arquivo.</p><label className="mt-4 flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 px-5 py-8 text-center hover:border-blue-300"><span className="text-sm font-semibold text-slate-700">{uploading?"Enviando arquivos...":"Anexar documentos manualmente"}</span><span className="mt-1 text-xs text-slate-400">Vinculados ao tenant e à oportunidade.</span><input type="file" multiple disabled={uploading} accept=".pdf,.zip,.doc,.docx,.xls,.xlsx,application/pdf,application/zip" onChange={e=>{const chosen=Array.from(e.currentTarget.files??[]);e.currentTarget.value="";void uploadFiles(chosen)}} className="hidden"/></label>{uploadMessage&&<div className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs font-medium text-slate-700">{uploadMessage}</div>}<div className="mt-4"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">Arquivos disponíveis</span><span className="text-xs text-slate-400">{documents.length}</span></div>{docsLoading?<p className="text-sm text-slate-500">Consultando anexos...</p>:documents.length===0?<p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">Nenhum anexo disponível ainda.</p>:<div className="space-y-2">{documents.map(doc=><div key={doc.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 px-3 py-2"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-700">{doc.original_filename}</p><p className="text-[11px] text-slate-400">{date(doc.uploaded_at,true)} · {doc.file_size_bytes?`${(doc.file_size_bytes/1024/1024).toFixed(2)} MB`:"tamanho não informado"}</p></div><span className="rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">DISPONÍVEL</span></div>)}</div>}</div>{!approvedForAnalysis&&<div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-center text-sm font-semibold text-slate-500">{triage?.result==="filtered_out"?"Oportunidade não aprovada na triagem":"Aguardando aprovação da triagem"}</div>}{analysisMessage&&<div className={`mt-3 rounded-lg border p-3 text-xs ${analysisQueued?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-slate-200 bg-slate-50 text-slate-700"}`}>{analysisMessage}</div>}</div></div></section>}
  </div></div>
}
