import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const U=Deno.env.get("SUPABASE_URL")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}});
type Obj={bucket:string;path:string;etag:string;size:number};
type ClientDoc={id:string;client_id:string;storage_bucket:string;storage_path:string;is_current:boolean;uploaded_at:string;content_sha256:string|null};
type OppDoc={id:string;client_id:string;opportunity_id:string;storage_bucket:string;storage_path:string;source_kind:string;preserve_permanently:boolean;uploaded_at:string;content_sha256:string|null};
function etag(v:any){return String(v?.metadata?.eTag??v?.metadata?.etag??"").replaceAll('"',"")}
async function walk(bucket:string,prefix=""):Promise<Obj[]>{let out:Obj[]=[];let offset=0;for(;;){const{data,error}=await db.storage.from(bucket).list(prefix,{limit:100,offset,sortBy:{column:"name",order:"asc"}});if(error)throw error;if(!data?.length)break;for(const item of data){const path=prefix?`${prefix}/${item.name}`:item.name;if(item.metadata)out.push({bucket,path,etag:etag(item),size:Number(item.metadata?.size??0)});else out=out.concat(await walk(bucket,path))}if(data.length<100)break;offset+=100}return out}
async function sha(bucket:string,path:string){const{data,error}=await db.storage.from(bucket).download(path);if(error||!data)throw error??new Error("download_failed");const bytes=await data.arrayBuffer();return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(b=>b.toString(16).padStart(2,"0")).join("")}
function clientKey(o:Obj){return `${o.path.split("/")[0]}:${o.etag}:${o.size}`}
function oppKey(o:Obj){const p=o.path.split("/");return `${p[0]}:${p[1]??""}:${o.etag}:${o.size}`}
async function remove(bucket:string,path:string){const{error}=await db.storage.from(bucket).remove([path]);if(error)throw error}
async function finish(id:string,status:"completed"|"failed",result:any){await db.rpc("complete_storage_maintenance_request_service",{p_id:id,p_status:status,p_result:result})}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const{data:userData,error:userError}=await db.auth.getUser(token);if(userError||!userData.user)return json({error:"unauthorized"},401);const{data:owner}=await db.from("platform_user_roles").select("user_id").eq("user_id",userData.user.id).eq("role","platform_owner").eq("active",true).maybeSingle();if(!owner)return json({error:"forbidden"},403);const body=await req.json().catch(()=>({}));const requestId=String(body?.request_id??"");if(!requestId)return json({error:"request_id_required"},400);const{data:claimed,error:claimErr}=await db.rpc("claim_storage_maintenance_request_service",{p_id:requestId,p_action:"deduplicate_storage"});if(claimErr||claimed!==true)return json({error:"invalid_or_expired_request",detail:claimErr?.message??null},403);
 const result:any={client:{groups:0,physical_removed:0,logical_repointed:0},opportunity:{groups:0,physical_removed:0,logical_removed:0,references_repointed:0},errors:[]};
 try{
  const[{data:clientRows,error:clientErr},{data:oppRows,error:oppErr},clientObjs,oppObjs]=await Promise.all([db.from("client_documents").select("id,client_id,storage_bucket,storage_path,is_current,uploaded_at,content_sha256"),db.from("opportunity_documents").select("id,client_id,opportunity_id,storage_bucket,storage_path,source_kind,preserve_permanently,uploaded_at,content_sha256"),walk("client-documents"),walk("opportunity-documents")]);if(clientErr)throw clientErr;if(oppErr)throw oppErr;
  const clients=(clientRows??[]) as ClientDoc[],opps=(oppRows??[]) as OppDoc[];const clientByPath=new Map<string,ClientDoc[]>(),oppByPath=new Map<string,OppDoc[]>();for(const d of clients){const a=clientByPath.get(d.storage_path)??[];a.push(d);clientByPath.set(d.storage_path,a)}for(const d of opps){const a=oppByPath.get(d.storage_path)??[];a.push(d);oppByPath.set(d.storage_path,a)}
  const reviewCache=new Map<string,any>();const cg=new Map<string,Obj[]>();for(const o of clientObjs){if(!o.etag||!o.size)continue;const k=clientKey(o),a=cg.get(k)??[];a.push(o);cg.set(k,a)}
  for(const candidates of [...cg.values()].filter(x=>x.length>1)){const verified=new Map<string,Obj[]>();for(const o of candidates){const h=await sha(o.bucket,o.path);const a=verified.get(h)??[];a.push(o);verified.set(h,a)}for(const[hash,group]of verified){if(group.length<2)continue;result.client.groups++;group.sort((a,b)=>{const ar=clientByPath.get(a.path)??[],br=clientByPath.get(b.path)??[];const as=ar.reduce((n,d)=>n+(d.is_current?100:10),0)+(ar.length?5:0),bs=br.reduce((n,d)=>n+(d.is_current?100:10),0)+(br.length?5:0);return bs-as});const keeper=group[0];for(const d of clientByPath.get(keeper.path)??[]){const{error:e}=await db.from("client_documents").update({content_sha256:hash}).eq("id",d.id);if(e)throw e}for(const dup of group.slice(1)){const refs=clientByPath.get(dup.path)??[];for(const d of refs){if(!reviewCache.has(d.client_id)){const{data:r}=await db.from("client_habilitation_reviews").select("*").eq("client_id",d.client_id).maybeSingle();reviewCache.set(d.client_id,r??null)}const{error:e}=await db.from("client_documents").update({storage_bucket:keeper.bucket,storage_path:keeper.path,content_sha256:hash,observations:"Arquivo físico deduplicado; registro lógico/histórico preservado."}).eq("id",d.id);if(e)throw e;result.client.logical_repointed++}await remove(dup.bucket,dup.path);result.client.physical_removed++}}}
  for(const[clientId,r]of reviewCache){if(r?.habilitado===true){const{error:e}=await db.from("client_habilitation_reviews").upsert({client_id:clientId,habilitado:true,notes:r.notes,validated_by:r.validated_by,validated_at:r.validated_at,updated_at:new Date().toISOString()});if(e)throw e}}
  const og=new Map<string,Obj[]>();for(const o of oppObjs){if(!o.etag||!o.size)continue;const k=oppKey(o),a=og.get(k)??[];a.push(o);og.set(k,a)}
  for(const candidates of [...og.values()].filter(x=>x.length>1)){const verified=new Map<string,Obj[]>();for(const o of candidates){const h=await sha(o.bucket,o.path);const a=verified.get(h)??[];a.push(o);verified.set(h,a)}for(const[hash,group]of verified){if(group.length<2)continue;result.opportunity.groups++;group.sort((a,b)=>{const ar=oppByPath.get(a.path)??[],br=oppByPath.get(b.path)??[];const score=(rows:OppDoc[])=>rows.reduce((n,d)=>n+(d.source_kind==="agent_download"?100:0)+(d.preserve_permanently?50:0)+10,0);return score(br)-score(ar)});const keeper=group[0],keeperRows=oppByPath.get(keeper.path)??[];if(!keeperRows.length){result.errors.push({path:keeper.path,error:"keeper_without_logical_record"});continue}const keeperDoc=keeperRows[0];for(const d of keeperRows){const{error:e}=await db.from("opportunity_documents").update({content_sha256:hash}).eq("id",d.id);if(e)throw e}for(const dup of group.slice(1)){for(const d of oppByPath.get(dup.path)??[]){const{data:refs,error:re}=await db.from("opportunity_document_references").select("client_id,opportunity_id,reference_kind,source_url").eq("document_id",d.id);if(re)throw re;for(const ref of refs??[]){const{error:e}=await db.from("opportunity_document_references").upsert({...ref,document_id:keeperDoc.id},{onConflict:"client_id,document_id,opportunity_id,reference_kind",ignoreDuplicates:true});if(e)throw e;result.opportunity.references_repointed++}const{error:rq}=await db.from("opportunity_requirements").update({evidence_document_id:keeperDoc.id}).eq("evidence_document_id",d.id);if(rq)throw rq;const{error:de}=await db.from("opportunity_documents").delete().eq("id",d.id);if(de)throw de;result.opportunity.logical_removed++}await remove(dup.bucket,dup.path);result.opportunity.physical_removed++}}}
  await finish(requestId,"completed",result);await db.from("audit_events").insert({actor_user_id:userData.user.id,event_type:"storage_dedup_completed",entity_type:"storage_maintenance_requests",entity_id:requestId,after_data:result});return json({ok:true,...result});
 }catch(e){const err=e instanceof Error?e.message:String(e);result.errors.push(err);await finish(requestId,"failed",result);return json({ok:false,...result},500)}
});