"use client";

import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";

type QueueRow={id:string;client_id:string;opportunity_id:string;status:string;queued_at:string;attempt_count:number;max_attempts:number};
type AuthRow={authorization_id:string;queue_id:string;client_id:string;authorized_by:string;max_claims:number;consumed_claims:number;max_cost_usd:number;expires_at:string;status:string;created_at:string;consumed_at:string|null;reason:string|null};
type Item={queue:QueueRow;client:string;process:string;authorization:AuthRow|null};

const moneyUsd=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:4}).format(n):"—"};
const when=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)};
const errorText=(e:unknown)=>{if(e instanceof Error)return e.message;if(e&&typeof e==="object"){const x=e as Record<string,unknown>;return [x.message,x.details,x.hint,x.code].filter(Boolean).map(String).join(" · ")||"Falha não identificada."}return String(e??"Falha não identificada.")};

export default function OwnerAiControl(){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function load(){if(!supabase)return;setLoading(true);setMessage("");try{const{data:q,error:qe}=await supabase.from("opportunity_ai_analysis_queue").select("id,client_id,opportunity_id,status,queued_at,attempt_count,max_attempts").in("status",["pending","retry_wait"]).order("queued_at");if(qe)throw qe;const queues=(q??[]) as QueueRow[];if(!queues.length){setItems([]);return}const clientIds=[...new Set(queues.map(x=>x.client_id))],opportunityIds=[...new Set(queues.map(x=>x.opportunity_id))];const[c,o]=await Promise.all([supabase.from("clients").select("id,display_name,legal_name").in("id",clientIds),supabase.from("public_opportunities").select("id,process_number").in("id",opportunityIds)]);if(c.error||o.error)throw c.error||o.error;const clientNames=new Map((c.data??[]).map(x=>[String(x.id),String(x.display_name||x.legal_name||"Cliente")]));const processes=new Map((o.data??[]).map(x=>[String(x.id),String(x.process_number||"Processo não informado")]));const auths=await Promise.all(queues.map(async queue=>{const{data,error}=await supabase!.rpc("get_ai_execution_authorization",{p_queue_id:queue.id}).maybeSingle();if(error)throw error;return(data??null) as AuthRow|null}));setItems(queues.map((queue,i)=>({queue,client:clientNames.get(queue.client_id)||"Cliente",process:processes.get(queue.opportunity_id)||"Processo não informado",authorization:auths[i]})))}catch(e){setMessage(`Não foi possível carregar as autorizações: ${errorText(e)}`)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function authorizeAndRun(item:Item){if(!supabase||busy)return;setBusy(item.queue.id);setMessage("");try{const key=`prod-owner-ui:${item.queue.id}:${Date.now()}`;const{error:ae}=await supabase.rpc("authorize_ai_execution",{p_queue_id:item.queue.id,p_max_claims:1,p_max_cost_usd:0.05,p_valid_for_minutes:15,p_idempotency_key:key,p_reason:"Liberação humana explícita pelo Owner no Veence Web"});if(ae)throw ae;const{data,error}=await supabase.functions.invoke("uni-analysis-worker-gemini",{body:{queue_id:item.queue.id}});if(error)throw error;if(data?.ok!==true)throw new Error(String(data?.detail||data?.error||"O worker não concluiu a execução autorizada."));setMessage(`Execução autorizada e concluída para ${item.process}.`);await load()}catch(e){setMessage(`A execução não foi concluída: ${errorText(e)}`);await load()}finally{setBusy("")}}
 async function runReleased(item:Item){if(!supabase||busy)return;setBusy(item.queue.id);setMessage("");try{const{data,error}=await supabase.functions.invoke("uni-analysis-worker-gemini",{body:{queue_id:item.queue.id}});if(error)throw error;if(data?.ok!==true)throw new Error(String(data?.detail||data?.error||"O worker não concluiu a execução autorizada."));setMessage(`Execução concluída para ${item.process}.`);await load()}catch(e){setMessage(`A execução não foi concluída: ${errorText(e)}`);await load()}finally{setBusy("")}}
 async function revoke(item:Item){if(!supabase||busy||!item.authorization)return;setBusy(item.queue.id);setMessage("");try{const{data,error}=await supabase.rpc("revoke_ai_execution_authorization",{p_authorization_id:item.authorization.authorization_id});if(error)throw error;if(data!==true)throw new Error("A autorização já não estava liberada.");setMessage(`Autorização revogada para ${item.process}.`);await load()}catch(e){setMessage(`Não foi possível revogar: ${errorText(e)}`)}finally{setBusy("")}}
 if(loading)return <div className="mt-4 rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-500">Carregando fila de IA...</div>;
 return <section className="mt-4 rounded-xl border border-[#dbe7f2] bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="font-black">Execuções de IA em produção</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Nenhuma inferência é liberada automaticamente. O Owner precisa liberar uma fila específica; a liberação padrão desta tela vale por 15 minutos, permite 1 claim e registra teto autorizado de US$ 0,05.</p></div><button type="button" onClick={()=>void load()} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-blue-700">Atualizar</button></div>{message&&<div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">{message}</div>}{items.length===0?<div className="mt-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Nenhuma análise detalhada aguarda liberação.</div>:<div className="mt-4 space-y-3">{items.map(item=>{const a=item.authorization,released=a?.status==="released"&&new Date(a.expires_at).getTime()>Date.now();return <div key={item.queue.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div><p className="text-sm font-black text-slate-900">{item.process}</p><p className="mt-1 text-xs text-slate-500">{item.client} · fila {item.queue.status} · criada em {when(item.queue.queued_at)}</p>{a&&<p className="mt-1 text-[11px] text-slate-500">Autorização: {a.status} · {a.consumed_claims}/{a.max_claims} claim(s) · {moneyUsd(a.max_cost_usd)} · expira {when(a.expires_at)}</p>}</div><div className="flex flex-wrap gap-2">{released?<><button type="button" disabled={busy===item.queue.id} onClick={()=>void runReleased(item)} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Executar autorização</button><button type="button" disabled={busy===item.queue.id} onClick={()=>void revoke(item)} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700 disabled:opacity-50">Revogar</button></>:<button type="button" disabled={busy===item.queue.id} onClick={()=>void authorizeAndRun(item)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Liberar e executar</button>}</div></div></div>})}</div>}</section>
}
