"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";

type Row=Record<string,unknown>;
type Review={client_id:string;habilitado:boolean;validated_at:string|null};
type AccessRequest={id:string;user_id:string;cnpj:string;email:string;login:string;status:string;client_id:string|null;created_at:string};
type Props={section:string;onOpenClient:(id:string)=>void};
type Data={clients:Row[];members:Row[];opps:Row[];reviews:Review[];requests:AccessRequest[]};

const card="rounded-xl border border-[#dbe7f2] bg-white shadow-[0_2px_8px_rgba(12,68,120,.06)]";
const btn="rounded-lg border border-[#bdd6ef] bg-white px-3 py-2 text-[11px] font-black text-[#0a5cc8] hover:bg-[#edf6ff] disabled:opacity-50";
const text=(v:unknown,f="—")=>v===null||v===undefined||String(v).trim()===""?f:String(v);
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};

export default function OwnerAdminV2({section,onOpenClient}:Props){
 const[data,setData]=useState<Data>({clients:[],members:[],opps:[],reviews:[],requests:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function load(){if(!supabase)return;setLoading(true);setError("");try{const[c,m,o,h,rq]=await Promise.all([supabase.from("clients").select("id,display_name,legal_name,status,created_at,updated_at").order("created_at",{ascending:false}),supabase.from("client_members").select("client_id,user_id,role,created_at"),supabase.from("client_radar_dashboard").select("client_id,opportunity_id,proposal_deadline,participation_allowed").limit(2000),supabase.from("client_habilitation_reviews").select("client_id,habilitado,validated_at"),supabase.functions.invoke("company-access-requests",{body:{action:"list"}})]);for(const x of[c,m,o,h])if(x.error)throw x.error;if(rq.error||!rq.data?.ok)throw new Error(rq.data?.detail||"Falha ao carregar solicitações de acesso.");setData({clients:(c.data??[]) as Row[],members:(m.data??[]) as Row[],opps:(o.data??[]) as Row[],reviews:(h.data??[]) as Review[],requests:(rq.data.requests??[]) as AccessRequest[]})}catch(x){setError(x instanceof Error?x.message:String(x))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const names=useMemo(()=>new Map(data.clients.map(c=>[String(c.id),text(c.display_name,text(c.legal_name,"Cliente"))])),[data.clients]);
 async function setHabilitado(clientId:string,next:boolean){if(!supabase||busy)return;setBusy(clientId);setError("");try{const{error:e}=await supabase.rpc("set_client_habilitation_status",{p_client_id:clientId,p_habilitado:next,p_notes:null});if(e)throw e;await load()}catch(x){setError(x instanceof Error?x.message:String(x))}finally{setBusy("")}}
 async function reviewRequest(r:AccessRequest,action:"approve"|"reject"){if(!supabase||busy)return;let reason="";if(action==="reject"){reason=window.prompt("Motivo da rejeição:","Solicitação não aprovada.")??"";if(!reason)return}setBusy(r.id);try{const{data:res,error:e}=await supabase.functions.invoke("company-access-requests",{body:{action,request_id:r.id,reason}});if(e||!res?.ok)throw new Error(res?.detail||e?.message||"Falha na operação.");await load()}catch(x){setError(x instanceof Error?x.message:String(x))}finally{setBusy("")}}
 if(loading)return <div className="p-8 text-sm text-slate-500">Carregando o ambiente do Owner...</div>;
 return <>{error&&<div className="mx-auto mt-4 max-w-[1500px] rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{section==="Clientes"?<Clients data={data} names={names} busy={busy} onOpenClient={onOpenClient} onHabilitado={setHabilitado} onRequest={reviewRequest}/>:section==="Configurações"?<Settings data={data}/>:<Dashboard data={data} names={names} onOpenClient={onOpenClient}/>}</>;
}

function Header({title,subtitle}:{title:string;subtitle:string}){return <div><h1 className="text-[26px] font-black text-[#09245f]">{title}</h1><p className="mt-1 text-[12px] text-[#315a92]">{subtitle}</p></div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className={`${card} p-4`}><b className="text-3xl text-[#08245c]">{value}</b><p className="mt-1 text-xs font-semibold text-[#315a92]">{label}</p></div>}

function Dashboard({data,names,onOpenClient}:{data:Data;names:Map<string,string>;onOpenClient:(id:string)=>void}){const unique=new Set(data.opps.map(o=>String(o.opportunity_id))).size;const enabled=data.reviews.filter(r=>r.habilitado).length;return <main className="mx-auto max-w-[1500px] p-5"><Header title="Painel do Owner" subtitle="Administração simplificada dos clientes e das oportunidades do UNI."/><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Clientes" value={data.clients.length}/><Metric label="Clientes habilitados" value={enabled}/><Metric label="Oportunidades" value={unique}/><Metric label="Participações liberadas" value={data.opps.filter(o=>o.participation_allowed===true).length}/></div><section className={`${card} mt-4 overflow-hidden`}><div className="border-b border-slate-100 p-4"><h2 className="font-black">Clientes recentes</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[#f3f8fd]"><tr><th className="p-3">Cliente</th><th>Habilitação</th><th>Oportunidades</th><th>Ação</th></tr></thead><tbody>{data.clients.slice(0,8).map(c=>{const id=String(c.id),review=data.reviews.find(r=>r.client_id===id);return <tr key={id} className="border-t"><td className="p-3 font-bold">{names.get(id)}</td><td>{review?.habilitado?"Habilitado":"Aguardando habilitação"}</td><td>{new Set(data.opps.filter(o=>String(o.client_id)===id).map(o=>String(o.opportunity_id))).size}</td><td><button className={btn} onClick={()=>onOpenClient(id)}>Acessar perfil</button></td></tr>})}</tbody></table></div></section></main>}

function Clients({data,names,busy,onOpenClient,onHabilitado,onRequest}:{data:Data;names:Map<string,string>;busy:string;onOpenClient:(id:string)=>void;onHabilitado:(id:string,next:boolean)=>Promise<void>;onRequest:(r:AccessRequest,a:"approve"|"reject")=>Promise<void>}){return <main className="mx-auto max-w-[1500px] p-5"><Header title="Clientes" subtitle="Aprove acessos e defina somente se cada cliente está habilitado."/>{data.requests.some(r=>r.status==="pending")&&<section className={`${card} mt-4 p-4`}><h2 className="font-black">Solicitações de acesso</h2><div className="mt-3 space-y-2">{data.requests.filter(r=>r.status==="pending").map(r=><div key={r.id} className="flex flex-col gap-3 rounded-lg border p-3 md:flex-row md:items-center md:justify-between"><div><b>{r.login}</b><p className="text-xs text-slate-500">{r.email} · CNPJ {r.cnpj}</p></div><div className="flex gap-2"><button disabled={busy===r.id} onClick={()=>void onRequest(r,"approve")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Aprovar</button><button disabled={busy===r.id} onClick={()=>void onRequest(r,"reject")} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Rejeitar</button></div></div>)}</div></section>}<section className={`${card} mt-4 overflow-hidden`}><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-[#f3f8fd]"><tr><th className="p-3">Cliente</th><th>Conta</th><th>Habilitação</th><th>Última validação</th><th>Ações</th></tr></thead><tbody>{data.clients.map(c=>{const id=String(c.id),review=data.reviews.find(r=>r.client_id===id),enabled=Boolean(review?.habilitado);return <tr key={id} className="border-t"><td className="p-3 font-bold">{names.get(id)}</td><td>{text(c.status)}</td><td><label className="inline-flex items-center gap-2 font-bold"><input type="checkbox" checked={enabled} disabled={busy===id} onChange={e=>void onHabilitado(id,e.target.checked)}/>{enabled?"Habilitado":"Aguardando"}</label></td><td>{date(review?.validated_at)}</td><td><button className={btn} onClick={()=>onOpenClient(id)}>Operar no perfil</button></td></tr>})}</tbody></table></div></section><section className={`${card} mt-4 p-4`}><h2 className="font-black">Documentos normalmente necessários</h2><p className="mt-1 text-xs text-slate-500">Lista de referência. Nenhum arquivo é armazenado no UNI Web.</p><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-3">{["Ato constitutivo e alterações","Cartão CNPJ","Inscrições estadual e municipal","Certidões Federal, Estadual e Municipal","CRF/FGTS e CNDT","Falência e recuperação judicial","Balanço e DRE","SICAF","Atestados de capacidade técnica","Declarações do edital"].map(x=><div key={x} className="rounded-lg bg-slate-50 p-3">✓ {x}</div>)}</div></section></main>}

function Settings({data}:{data:Data}){const[theme,setTheme]=useState("light");useEffect(()=>setTheme(localStorage.getItem("uni-theme")||"light"),[]);function apply(v:string){localStorage.setItem("uni-theme",v);setTheme(v);window.dispatchEvent(new Event("uni-theme-change"))}return <main className="mx-auto max-w-[1200px] p-5"><Header title="Configurações" subtitle="Preferências administrativas do Owner."/><section className={`${card} mt-5 p-5`}><h2 className="font-black">Aparência</h2><div className="mt-3 flex gap-2">{[["light","Claro"],["dark","Escuro"],["system","Automático"]].map(([v,l])=><button key={v} onClick={()=>apply(v)} className={`${btn} ${theme===v?"border-blue-600 bg-blue-50":""}`}>{l}</button>)}</div></section><section className={`${card} mt-4 p-5`}><h2 className="font-black">Resumo da conta</h2><p className="mt-2 text-sm text-slate-600">{data.clients.length} cliente(s) e {data.members.length} usuário(s) vinculados. O UNI Web não armazena documentos dos clientes.</p></section></main>}
