"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";

type Row=Record<string,unknown>;

type Props={onOpenClient:(id:string)=>void};

const money=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(n):"—"};
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};
const txt=(v:unknown,f="—")=>v===null||v===undefined||String(v).trim()===""?f:String(v);
const norm=(v:unknown)=>String(v??"").trim().toLowerCase();

export default function OwnerOportunidades({onOpenClient}:Props){
 const[rows,setRows]=useState<Row[]>([]),[clients,setClients]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[q,setQ]=useState(""),[client,setClient]=useState(""),[modality,setModality]=useState(""),[uf,setUf]=useState(""),[city,setCity]=useState(""),[lifecycle,setLifecycle]=useState(""),[participation,setParticipation]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[minValue,setMinValue]=useState(""),[maxValue,setMaxValue]=useState(""),[sort,setSort]=useState("newest");
 async function load(){if(!supabase)return;setLoading(true);setError("");try{const[r,c]=await Promise.all([supabase.from("client_radar_dashboard").select("client_id,capability_id,opportunity_id,process_number,title,object_text,buyer_name,city,state,modality,publication_date,proposal_deadline,estimated_value,currency,source_url,lifecycle,match_status,deterministic_score,participation_allowed,method_version,match_updated_at").order("publication_date",{ascending:false}).limit(2000),supabase.from("clients").select("id,display_name,legal_name,status").order("display_name")]);if(r.error)throw r.error;if(c.error)throw c.error;setRows((r.data??[])as Row[]);setClients((c.data??[])as Row[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const names=useMemo(()=>new Map(clients.map(c=>[String(c.id),txt(c.display_name,txt(c.legal_name,"Cliente"))])),[clients]);
 const modalities=useMemo(()=>[...new Set(rows.map(r=>txt(r.modality,"")).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[rows]);
 const states=useMemo(()=>[...new Set(rows.map(r=>txt(r.state,"")).filter(Boolean))].sort(),[rows]);
 const cities=useMemo(()=>[...new Set(rows.filter(r=>!uf||txt(r.state,"")===uf).map(r=>txt(r.city,"")).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[rows,uf]);
 const lifecycles=useMemo(()=>[...new Set(rows.map(r=>txt(r.lifecycle,"")).filter(Boolean))].sort(),[rows]);
 const filtered=useMemo(()=>{const start=from?new Date(`${from}T00:00:00`).getTime():null;const end=to?new Date(`${to}T23:59:59`).getTime():null;const min=minValue?Number(minValue.replace(",",".")):null;const max=maxValue?Number(maxValue.replace(",",".")):null;const needle=q.trim().toLowerCase();const out=rows.filter(r=>{const pub=r.publication_date?new Date(String(r.publication_date)).getTime():0;const val=Number(r.estimated_value||0);if(needle&&![(names.get(String(r.client_id))||""),r.process_number,r.title,r.object_text,r.buyer_name,r.city,r.state,r.modality].some(v=>norm(v).includes(needle)))return false;if(client&&String(r.client_id)!==client)return false;if(modality&&txt(r.modality,"")!==modality)return false;if(uf&&txt(r.state,"")!==uf)return false;if(city&&txt(r.city,"")!==city)return false;if(lifecycle&&txt(r.lifecycle,"")!==lifecycle)return false;if(participation==="allowed"&&r.participation_allowed!==true)return false;if(participation==="blocked"&&r.participation_allowed!==false)return false;if(participation==="pending"&&r.participation_allowed!==null&&r.participation_allowed!==undefined)return false;if(start!==null&&pub<start)return false;if(end!==null&&pub>end)return false;if(min!==null&&Number.isFinite(min)&&val<min)return false;if(max!==null&&Number.isFinite(max)&&val>max)return false;return true});return [...out].sort((a,b)=>{if(sort==="oldest")return new Date(String(a.publication_date||0)).getTime()-new Date(String(b.publication_date||0)).getTime();if(sort==="value_desc")return Number(b.estimated_value||0)-Number(a.estimated_value||0);if(sort==="value_asc")return Number(a.estimated_value||0)-Number(b.estimated_value||0);if(sort==="deadline")return new Date(String(a.proposal_deadline||"2999-12-31")).getTime()-new Date(String(b.proposal_deadline||"2999-12-31")).getTime();return new Date(String(b.publication_date||0)).getTime()-new Date(String(a.publication_date||0)).getTime()})},[rows,q,client,modality,uf,city,lifecycle,participation,from,to,minValue,maxValue,sort,names]);
 function clear(){setQ("");setClient("");setModality("");setUf("");setCity("");setLifecycle("");setParticipation("");setFrom("");setTo("");setMinValue("");setMaxValue("");setSort("newest")}
 function open(r:Row){sessionStorage.setItem("uni-owner-start-module","Oportunidades");sessionStorage.setItem("uni-opportunity-open",String(r.opportunity_id));sessionStorage.setItem("uni-opportunity-tab","Resumo");onOpenClient(String(r.client_id))}
 const activeCount=filtered.filter(r=>!r.proposal_deadline||new Date(String(r.proposal_deadline)).getTime()>=Date.now()).length;
 const allowedCount=filtered.filter(r=>r.participation_allowed===true).length;
 const total=filtered.reduce((s,r)=>s+Number(r.estimated_value||0),0);
 const input="rounded-lg border border-[#cfe0ef] bg-white px-3 py-2 text-[11px] text-[#153b74] outline-none focus:border-[#2a78da]";
 return <main className="mx-auto max-w-[1650px] p-5 text-[#08245c]"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#e8f3ff] text-2xl text-[#0a66f5]">⌕</div><div><h1 className="text-[26px] font-black">Oportunidades</h1><p className="text-[12px] font-medium text-[#315a92]">Visão consolidada de oportunidades de todos os clientes do UNI.</p></div></div><button onClick={()=>void load()} className="rounded-lg border border-[#bdd6ef] bg-white px-4 py-2 text-[11px] font-black text-[#0a5cc8]">Atualizar dados</button></div>
 <section className="mt-4 rounded-xl border border-[#dbe7f2] bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="text-[13px] font-black">Filtros</h2><p className="text-[10px] text-[#5c7598]">Combine os campos para localizar oportunidades específicas.</p></div><button onClick={clear} className="rounded-lg border border-[#cfe0ef] px-3 py-2 text-[10px] font-black text-[#0a5cc8]">Limpar filtros</button></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-5"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Processo, órgão, objeto, cidade..." className={`${input} xl:col-span-2`}/><select value={client} onChange={e=>setClient(e.target.value)} className={input}><option value="">Todos os clientes</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{names.get(String(c.id))}</option>)}</select><select value={modality} onChange={e=>setModality(e.target.value)} className={input}><option value="">Todas as modalidades</option>{modalities.map(x=><option key={x}>{x}</option>)}</select><select value={participation} onChange={e=>setParticipation(e.target.value)} className={input}><option value="">Participação: todas</option><option value="allowed">Liberadas</option><option value="blocked">Bloqueadas</option><option value="pending">Sem decisão</option></select><select value={uf} onChange={e=>{setUf(e.target.value);setCity("")}} className={input}><option value="">Todos os estados</option>{states.map(x=><option key={x}>{x}</option>)}</select><select value={city} onChange={e=>setCity(e.target.value)} className={input}><option value="">Todas as cidades</option>{cities.map(x=><option key={x}>{x}</option>)}</select><select value={lifecycle} onChange={e=>setLifecycle(e.target.value)} className={input}><option value="">Todos os status</option>{lifecycles.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} title="Publicadas a partir de" className={input}/><input type="date" value={to} onChange={e=>setTo(e.target.value)} title="Publicadas até" className={input}/><input inputMode="decimal" value={minValue} onChange={e=>setMinValue(e.target.value)} placeholder="Valor mínimo" className={input}/><input inputMode="decimal" value={maxValue} onChange={e=>setMaxValue(e.target.value)} placeholder="Valor máximo" className={input}/><select value={sort} onChange={e=>setSort(e.target.value)} className={input}><option value="newest">Mais recentes</option><option value="oldest">Mais antigas</option><option value="deadline">Prazo mais próximo</option><option value="value_desc">Maior valor</option><option value="value_asc">Menor valor</option></select></div></section>
 <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[filtered.length,"Resultados"],[activeCount,"Com prazo ativo"],[allowedCount,"Participação liberada"],[money(total),"Valor estimado filtrado"]].map(([v,l])=><div key={String(l)} className="rounded-xl border border-[#dbe7f2] bg-white p-4 shadow-sm"><b className="text-2xl">{String(v)}</b><p className="mt-1 text-[11px] font-semibold text-[#315a92]">{l}</p></div>)}</div>
 {error&&<div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{loading?<div className="mt-4 rounded-xl border border-[#dbe7f2] bg-white p-8 text-sm text-[#5c7598]">Carregando oportunidades...</div>:<section className="mt-3 overflow-hidden rounded-xl border border-[#dbe7f2] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-[10px]"><thead className="bg-[#f4f8fc] text-[#31578c]"><tr><th className="p-3">Cliente</th><th>Processo / objeto</th><th>Órgão</th><th>Local</th><th>Modalidade</th><th>Publicação</th><th>Prazo</th><th>Valor estimado</th><th>Status</th><th>Score</th><th>Ação</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={`${r.client_id}-${r.opportunity_id}`} className="border-t border-[#e5eef6] hover:bg-[#f9fcff]"><td className="p-3 font-black">{names.get(String(r.client_id))||"Cliente"}</td><td className="max-w-[330px]"><b>{txt(r.process_number,"Sem número")}</b><p className="mt-1 line-clamp-2 text-[#5c7598]">{txt(r.object_text,txt(r.title))}</p></td><td className="max-w-[220px]">{txt(r.buyer_name)}</td><td>{[txt(r.city,""),txt(r.state,"")].filter(Boolean).join("/")||"—"}</td><td>{txt(r.modality)}</td><td>{date(r.publication_date)}</td><td>{date(r.proposal_deadline)}</td><td className="font-bold">{money(r.estimated_value)}</td><td><span className={`rounded-full px-2 py-1 font-bold ${r.participation_allowed===true?"bg-emerald-50 text-emerald-700":r.participation_allowed===false?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{r.participation_allowed===true?"Liberada":r.participation_allowed===false?"Bloqueada":txt(r.lifecycle,"Em análise")}</span></td><td className="font-bold">{r.deterministic_score===null||r.deterministic_score===undefined?"—":Number(r.deterministic_score).toFixed(0)}</td><td><button onClick={()=>open(r)} className="rounded-md border border-[#b9d7f3] bg-[#edf6ff] px-3 py-1.5 font-bold text-[#0a5fd3]">Abrir</button></td></tr>):<tr><td colSpan={11} className="p-8 text-center text-sm text-slate-500">Nenhuma oportunidade corresponde aos filtros selecionados.</td></tr>}</tbody></table></div></section>}</main>;
}
