"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {BackendDashboard,loadCurrentClientDashboard} from "@/lib/dashboard";

interface DashboardProps{onNavigate?:(module:string)=>void}
type Opportunity=Record<string,unknown>;
type Tone="blue"|"green"|"amber"|"violet"|"rose"|"slate";
const badge:Record<Tone,string>={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",violet:"bg-violet-50 text-violet-700",rose:"bg-rose-50 text-rose-700",slate:"bg-slate-100 text-slate-600"};
function n(v:unknown){const x=Number(v??0);return Number.isFinite(x)?x:0}
function t(v:unknown,f="—"){return typeof v==="string"&&v.trim()?v:f}
function date(v:unknown){if(typeof v!=="string")return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)}
function days(v:unknown,now:number){if(typeof v!=="string")return null;const x=new Date(v).getTime();return Number.isFinite(x)?Math.ceil((x-now)/86400000):null}
function err(e:unknown){if(e instanceof Error)return e.message;if(typeof e==="string")return e;try{return JSON.stringify(e)}catch{return"Falha ao carregar o painel."}}
function status(o:Opportunity):{label:string;tone:Tone}{if(o.participation_allowed===true)return{label:"Liberada",tone:"green"};const m=t(o.match_status,"candidate");if(m==="approved")return{label:"Aprovada",tone:"green"};if(m==="rejected"||m==="filtered_out")return{label:"Não aprovada",tone:"rose"};if(m==="analyzed")return{label:"Analisada",tone:"violet"};if(m==="queued_for_analysis")return{label:"Em análise",tone:"blue"};return{label:"Candidata",tone:"amber"}}
function advanced(o:Opportunity,keys:string[]){return keys.some(k=>{const v=o[k];return v===true||(typeof v==="string"&&v.length>0&&!["pending","candidate","not_started","unknown"].includes(v))})}

export default function Dashboard({onNavigate}:DashboardProps){
 const[data,setData]=useState<BackendDashboard|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[updatedAt,setUpdatedAt]=useState<Date|null>(null);const[now]=useState(Date.now);
 const load=useCallback(async(initial=false)=>{if(initial)setLoading(true);else setRefreshing(true);setError("");try{const p=await loadCurrentClientDashboard();if(!p)throw new Error("Nenhuma empresa foi associada a este usuário.");setData(p);setUpdatedAt(new Date())}catch(e){setError(err(e))}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void load(true)},[load]);
 const opps=useMemo(()=>data?.opportunities??[],[data?.opportunities]);
 const live=n(data?.summary?.live_count),released=n(data?.summary?.released_for_participation_count),pending=n(data?.pending?.open_pending_count),blocking=n(data?.pending?.blocking_pending_count);
 const deadlines=useMemo(()=>opps.filter(o=>typeof o.proposal_deadline==="string"&&new Date(o.proposal_deadline as string).getTime()>=now).sort((a,b)=>new Date(a.proposal_deadline as string).getTime()-new Date(b.proposal_deadline as string).getTime()).slice(0,5),[opps,now]);
 const triaged=opps.filter(o=>advanced(o,["triage_result","match_status"])).length,analyzed=opps.filter(o=>advanced(o,["analysis_status","ai_analysis_status"])||["analyzed","approved","rejected"].includes(t(o.match_status,""))).length,cfp=opps.filter(o=>advanced(o,["cfp_status","quotation_status","quote_status"])).length,economic=opps.filter(o=>advanced(o,["economic_gate_status","viability_status","economic_status"])).length,dispute=opps.filter(o=>advanced(o,["dispute_status","session_status","post_dispute_status"])).length;
 const pipeline=[{label:"Triagem",value:triaged,target:"Radar"},{label:"Análise",value:analyzed,target:"Oportunidades"},{label:"CFP",value:cfp,target:"CFP"},{label:"Gate Econômico",value:economic,target:"Gate Econômico"},{label:"Participação",value:released,target:"Gate de Participação"},{label:"Disputa / Resultado",value:dispute,target:"Disputa"}];
 const client=data?.client?.display_name||data?.client?.legal_name||"Empresa";
 if(loading)return <div className="p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-[1500px] rounded-2xl border border-slate-200 bg-white p-8"><div className="h-3 w-44 animate-pulse rounded bg-slate-200"/><p className="mt-4 text-sm text-slate-500">Preparando seu painel...</p></div></div>;
 if(error&&!data)return <div className="p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-[1500px] rounded-2xl border border-rose-200 bg-rose-50 p-8"><h2 className="text-lg font-bold text-rose-800">Não foi possível carregar o painel</h2><p className="mt-2 text-sm text-rose-700">{error}</p><button onClick={()=>void load(true)} className="mt-4 rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-bold text-white">Tentar novamente</button></div></div>;
 if(!data)return null;
 const priorities=[...(blocking>0?[{title:`${blocking} pendência${blocking===1?"":"s"} bloqueadora${blocking===1?"":"s"}`,detail:"Resolva antes de avançar em participações afetadas.",target:"Empresa",tone:"rose" as Tone}]:[]),...(deadlines.length?[{title:`${deadlines.length} prazo${deadlines.length===1?"":"s"} próximo${deadlines.length===1?"":"s"}`,detail:"Revise as oportunidades com sessão mais próxima.",target:"Radar",tone:"amber" as Tone}]:[]),...(released>0?[{title:`${released} oportunidade${released===1?"":"s"} liberada${released===1?"":"s"}`,detail:"Há processos aptos a seguir para preparação de participação.",target:"Negócios",tone:"green" as Tone}]:[])];
 return <div className="p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-[1500px]">
  {error&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><span>Não foi possível atualizar agora: {error}</span><button onClick={()=>void load()} className="font-bold underline">Tentar novamente</button></div>}
  <div className="mb-5 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Visão de hoje</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">{client}</h1><p className="mt-1 text-sm text-slate-500">Prioridades, prazos e avanço no método UNI em um só lugar.</p></div><div className="flex items-center gap-3"><p className="text-xs text-slate-400">{updatedAt?`Atualizado às ${updatedAt.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`:""}</p><button onClick={()=>void load()} disabled={refreshing} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50">{refreshing?"Atualizando...":"Atualizar"}</button></div></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-black text-slate-900">Prioridades de hoje</h2><p className="mt-1 text-xs text-slate-500">O que merece atenção antes das demais atividades.</p></div><button onClick={()=>onNavigate?.("Radar")} className="text-xs font-bold text-blue-600">Abrir Radar</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{priorities.length?priorities.map(p=><button key={p.title} onClick={()=>onNavigate?.(p.target)} className="rounded-xl border border-slate-200 p-4 text-left transition hover:border-blue-200 hover:bg-blue-50/30"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${badge[p.tone]}`}>{p.title}</span><p className="mt-3 text-sm leading-5 text-slate-600">{p.detail}</p></button>):<div className="md:col-span-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><strong>Nenhuma prioridade crítica agora.</strong><span className="ml-1">O ambiente está sem bloqueios imediatos identificados.</span></div>}</div></section>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:"Oportunidades ativas",value:live,helper:"Ver no Radar",target:"Radar"},{label:"Liberadas para participação",value:released,helper:"Avançar em Negócios",target:"Negócios"},{label:"Pendências abertas",value:pending,helper:`${blocking} bloqueadora${blocking===1?"":"s"}`,target:"Empresa"},{label:"Próximos prazos",value:deadlines.length,helper:"Revisar agenda",target:"Radar"}].map(k=><button key={k.label} onClick={()=>onNavigate?.(k.target)} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><p className="text-sm font-semibold text-slate-500">{k.label}</p><p className="mt-2 text-3xl font-black text-slate-900">{k.value}</p><p className="mt-3 text-xs font-bold text-blue-600">{k.helper}</p></button>)}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.85fr]">
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Fluxo do método UNI</h2><p className="mt-1 text-xs text-slate-500">Visão operacional das oportunidades conforme os dados disponíveis em cada etapa.</p></div><button onClick={()=>onNavigate?.("Negócios")} className="text-xs font-bold text-blue-600">Abrir Negócios</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{pipeline.map((s,i)=><button key={s.label} onClick={()=>onNavigate?.(s.target)} className="group rounded-xl border border-slate-200 p-4 text-left hover:border-blue-200"><div className="flex items-center justify-between"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-[11px] font-black text-slate-600 group-hover:bg-blue-600 group-hover:text-white">{i+1}</span><strong className="text-xl">{s.value}</strong></div><p className="mt-3 text-sm font-bold text-slate-700">{s.label}</p></button>)}</div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Próximos prazos</h2><p className="mt-1 text-xs text-slate-500">Sessões e encerramentos futuros.</p></div><button onClick={()=>onNavigate?.("Radar")} className="text-xs font-bold text-blue-600">Ver todos</button></div><div className="mt-4 space-y-2">{deadlines.length?deadlines.map((o,i)=>{const d=days(o.proposal_deadline,now);return <button key={`${t(o.opportunity_id)}-${i}`} onClick={()=>onNavigate?.("Radar")} className="flex w-full items-center justify-between gap-3 rounded-xl border border-slate-100 p-3 text-left hover:border-blue-200 hover:bg-blue-50/30"><div className="min-w-0"><p className="truncate text-sm font-bold">{t(o.process_number)}</p><p className="mt-1 truncate text-xs text-slate-500">{t(o.buyer_name)}</p></div><div className="shrink-0 text-right"><p className="text-xs font-bold text-rose-600">{date(o.proposal_deadline)}</p><p className="mt-1 text-[11px] text-slate-400">{d===0?"hoje":d===1?"amanhã":d!==null?`em ${d} dias`:""}</p></div></button>}):<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Nenhum prazo futuro identificado.</p>}</div></section>
  </div>
  <section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-black">Oportunidades recentes</h2><p className="mt-1 text-xs text-slate-500">Resumo das oportunidades do seu ambiente.</p></div><button onClick={()=>onNavigate?.("Oportunidades")} className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Ver todas</button></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Órgão","Processo","Objeto","Prazo","Situação",""].map((h,i)=><th key={`${h}-${i}`} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{opps.slice(0,5).map((o,i)=>{const s=status(o);return <tr key={`${t(o.opportunity_id)}-${i}`} className="hover:bg-slate-50/70"><td className="max-w-[220px] px-5 py-3 font-semibold"><span className="block truncate">{t(o.buyer_name)}</span></td><td className="px-5 py-3 text-slate-600">{t(o.process_number)}</td><td className="max-w-[330px] px-5 py-3 text-slate-600"><span className="block truncate">{t(o.object_text,t(o.title))}</span></td><td className="px-5 py-3">{date(o.proposal_deadline)}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${badge[s.tone]}`}>{s.label}</span></td><td className="px-5 py-3"><button onClick={()=>onNavigate?.("Oportunidades")} className="font-bold text-blue-600">Abrir</button></td></tr>})}{!opps.length&&<tr><td colSpan={6} className="px-5 py-8 text-center text-sm text-slate-500">Nenhuma oportunidade disponível ainda.</td></tr>}</tbody></table></div></section>
 </div></div>;
}
