"use client";

import { useEffect, useMemo, useState } from "react";
import { BackendDashboard, loadCurrentClientDashboard } from "@/lib/dashboard";

interface DashboardProps { onNavigate?: (module: string) => void; }
type Opportunity = Record<string, unknown>;

const statusDotClasses: Record<string, string> = { blue:"bg-blue-500", green:"bg-emerald-500", amber:"bg-amber-500", violet:"bg-violet-500", rose:"bg-rose-500" };
const toneClasses: Record<string, string> = { blue:"bg-blue-50 text-blue-700", green:"bg-emerald-50 text-emerald-700", amber:"bg-amber-50 text-amber-700", violet:"bg-violet-50 text-violet-700", rose:"bg-rose-50 text-rose-700" };

function n(v: unknown) { const x = Number(v ?? 0); return Number.isFinite(x) ? x : 0; }
function t(v: unknown, fallback="—") { return typeof v === "string" && v.trim() ? v : fallback; }
function date(v: unknown) { if(typeof v!=="string") return "—"; const d=new Date(v); return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d); }
function parts(v: unknown) { if(typeof v!=="string") return {day:"—",month:"—"}; const d=new Date(v); if(Number.isNaN(d.getTime())) return {day:"—",month:"—"}; return {day:new Intl.DateTimeFormat("pt-BR",{day:"2-digit"}).format(d),month:new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(d).replace(".","").toUpperCase()}; }
function status(o: Opportunity) { if(o.participation_allowed===true) return {label:"Liberada",tone:"green"}; const m=t(o.match_status,"candidate"); if(m==="approved") return {label:"Aprovada",tone:"green"}; if(m==="rejected"||m==="filtered_out") return {label:"Não aprovada",tone:"rose"}; if(m==="analyzed") return {label:"Analisada",tone:"violet"}; if(m==="queued_for_analysis") return {label:"Em análise",tone:"blue"}; return {label:"Candidata",tone:"amber"}; }

export default function Dashboard({ onNavigate }: DashboardProps) {
  const [data,setData]=useState<BackendDashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{ let active=true; loadCurrentClientDashboard().then(p=>{if(!active)return;setData(p);if(!p)setError("Nenhum tenant foi associado a este usuário.");}).catch(()=>active&&setError("Não foi possível carregar os dados operacionais do tenant.")).finally(()=>active&&setLoading(false)); return()=>{active=false}; },[]);
  const opportunities=data?.opportunities??[]; const live=n(data?.summary?.live_count), historical=n(data?.summary?.historical_count), released=n(data?.summary?.released_for_participation_count), pending=n(data?.pending?.open_pending_count), blocking=n(data?.pending?.blocking_pending_count), unknown=n(data?.summary?.unknown_count);
  const deadlines=useMemo(()=>opportunities.filter(o=>typeof o.proposal_deadline==="string"&&new Date(o.proposal_deadline as string).getTime()>=Date.now()).sort((a,b)=>new Date(a.proposal_deadline as string).getTime()-new Date(b.proposal_deadline as string).getTime()).slice(0,4),[opportunities]);
  const monthly=useMemo(()=>{const now=new Date();return Array.from({length:6},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-5+i,1);const count=opportunities.filter(o=>{if(typeof o.publication_date!=="string")return false;const p=new Date(o.publication_date);return p.getFullYear()===d.getFullYear()&&p.getMonth()===d.getMonth();}).length;return{label:new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(d).replace(".",""),count};});},[opportunities]);
  const max=Math.max(1,...monthly.map(x=>x.count)); const points=monthly.map((x,i)=>`${20+i*112},${155-(x.count/max)*100}`).join(" "); const client=data?.client?.display_name||data?.client?.legal_name||"Cliente"; const today=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date());
  if(loading)return <div className="px-4 py-6 sm:px-6 xl:px-8"><div className="mx-auto max-w-[1540px] rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500 shadow-sm">Carregando painel operacional...</div></div>;
  if(error||!data)return <div className="px-4 py-6 sm:px-6 xl:px-8"><div className="mx-auto max-w-[1540px] rounded-2xl border border-rose-200 bg-rose-50 p-8 text-sm text-rose-700">{error||"Dados indisponíveis."}</div></div>;
  const total=live+historical+unknown, lp=total?(live/total)*100:0, hp=total?(historical/total)*100:0;
  return <div className="px-4 py-6 sm:px-6 xl:px-8"><div className="mx-auto max-w-[1540px]">
    <div className="mb-5 flex flex-col justify-between gap-4 xl:flex-row xl:items-start"><div><h1 className="text-3xl font-bold tracking-tight text-slate-900">Olá!</h1><p className="mt-1 text-base text-slate-500">Resumo operacional de {client} com dados do backend.</p></div><div className="flex items-center gap-3 text-sm text-slate-600"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white">▣</div><div><p className="font-semibold capitalize text-slate-800">{today}</p><p className="text-xs text-slate-500">Ambiente autenticado</p></div></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["⌕",live,"Oportunidades Ativas","Radar do tenant","from-blue-500 to-blue-600"],["!",pending,"Pendências Abertas",`${blocking} bloqueadoras`,"from-orange-500 to-amber-500"],["✓",released,"Liberadas p/ Participação","Gate operacional","from-emerald-500 to-green-600"],["▥",historical,"Oportunidades Históricas","Base do tenant","from-violet-500 to-purple-600"]].map(([icon,value,title,helper,gradient])=><section key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-4"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br ${gradient} text-lg font-bold text-white shadow-sm`}>{icon}</div><div><div className="text-2xl font-bold text-slate-900">{value}</div><div className="text-sm text-slate-600">{title}</div></div></div><div className="mt-4 text-xs text-slate-400">{helper}</div></section>)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_1fr_0.62fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Evolução de Oportunidades</h2><span className="text-xs text-slate-400">Últimos 6 meses</span></div><div className="mt-5 h-[190px] rounded-xl bg-[linear-gradient(to_right,#e2e8f0_1px,transparent_1px),linear-gradient(to_bottom,#e2e8f0_1px,transparent_1px)] bg-[size:20%_25%] p-4"><svg viewBox="0 0 600 180" className="h-full w-full"><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{points.split(" ").map(p=>{const[cx,cy]=p.split(",");return <circle key={p} cx={cx} cy={cy} r="5" fill="#3b82f6" stroke="white" strokeWidth="2"/>})}</svg></div><div className="mt-2 flex justify-between px-3 text-[11px] text-slate-400">{monthly.map(x=><span key={x.label}>{x.label}</span>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Status do Radar</h2><div className="mt-5 flex items-center gap-6"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{background:total?`conic-gradient(#3b82f6 0 ${lp}%,#8b5cf6 ${lp}% ${lp+hp}%,#f59e0b ${lp+hp}% 100%)`:"#e2e8f0"}}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-white"><span className="text-2xl font-bold">{total}</span><span className="text-xs text-slate-500">Total</span></div></div><div className="min-w-0 flex-1 space-y-2.5 text-xs">{[["blue","Ativas",live],["violet","Históricas",historical],["amber","Sem classificação",unknown],["green","Liberadas",released],["rose","Pendências bloqueadoras",blocking]].map(([c,l,v])=><div key={String(l)} className="flex items-center justify-between gap-3"><span className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${statusDotClasses[String(c)]}`}/>{l}</span><strong>{v}</strong></div>)}</div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">Próximos Prazos</h2><button onClick={()=>onNavigate?.("Radar")} className="text-xs font-semibold text-blue-600">Ver todos</button></div><div className="space-y-3">{deadlines.length===0&&<p className="py-6 text-center text-xs text-slate-400">Nenhum prazo futuro no radar atual.</p>}{deadlines.map((o,i)=>{const p=parts(o.proposal_deadline);return <div key={`${t(o.process_number)}-${i}`} className="flex gap-3 border-b border-slate-100 pb-3 last:border-0"><div className="flex h-11 w-11 shrink-0 flex-col items-center justify-center rounded-xl bg-rose-50 text-rose-600"><span className="font-bold leading-none">{p.day}</span><span className="mt-1 text-[9px] font-bold">{p.month}</span></div><div className="min-w-0"><p className="text-[11px] font-bold">{t(o.process_number)}</p><p className="truncate text-[10px] text-slate-500">Prazo de proposta</p><p className="truncate text-[10px] text-slate-400">{t(o.buyer_name)}</p></div></div>})}</div></section>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_0.8fr]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-4"><h2 className="font-bold">Últimas Oportunidades</h2><button onClick={()=>onNavigate?.("Radar")} className="text-xs font-semibold text-blue-600">Ver todas</button></div><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Órgão","Modalidade","Número","Objeto","Prazo","Status"].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{opportunities.slice(0,5).map((o,i)=>{const s=status(o);return <tr key={`${t(o.process_number)}-${i}`} className="hover:bg-slate-50/70"><td className="px-5 py-3 font-semibold">{t(o.buyer_name)}</td><td className="px-5 py-3 text-slate-500">{t(o.modality)}</td><td className="px-5 py-3">{t(o.process_number)}</td><td className="max-w-[260px] truncate px-5 py-3">{t(o.object_text,t(o.title))}</td><td className="px-5 py-3">{date(o.proposal_deadline)}</td><td className="px-5 py-3"><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${toneClasses[s.tone]}`}>{s.label}</span></td></tr>})}{opportunities.length===0&&<tr><td colSpan={6} className="px-5 py-8 text-center text-slate-400">Nenhuma oportunidade disponível para este tenant.</td></tr>}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Estado Operacional</h2><span className="text-xs text-slate-400">Backend real</span></div><div className="space-y-4 text-xs"><div className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-emerald-500"/><div><p className="font-semibold">Tenant validado</p><p className="text-slate-500">{client}</p></div></div><div className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-blue-500"/><div><p className="font-semibold">Radar carregado</p><p className="text-slate-500">{live} oportunidades ativas</p></div></div><div className="flex gap-3"><span className={`mt-1.5 h-2.5 w-2.5 rounded-full ${blocking?"bg-rose-500":"bg-emerald-500"}`}/><div><p className="font-semibold">Pendências</p><p className="text-slate-500">{pending} abertas, {blocking} bloqueadoras</p></div></div><div className="rounded-xl bg-slate-50 p-3 text-slate-500">Atividades, CFP e relatórios só aparecerão quando esses módulos registrarem eventos no backend. Nenhum dado demonstrativo é exibido.</div></div></section>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Acesso Rápido</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Radar","⌕","Buscar Editais"],["Editais","▣","Nova Análise"],["Relatórios","▥","Gerar Relatório"],["Documentos","□","Meus Documentos"],["Fornecedores","♙","Fornecedores"]].map(([m,i,l])=><button key={l} onClick={()=>onNavigate?.(m)} className="rounded-xl border border-slate-200 bg-white p-4 text-center hover:border-blue-200"><span className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-lg text-blue-600">{i}</span><span className="mt-2 block text-xs font-semibold">{l}</span></button>)}</div></section><section className="flex min-h-[145px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-1 flex-col justify-center p-6"><span className="text-3xl text-slate-200">“</span><p className="mt-1 text-lg italic text-slate-700">Decisão orientada por evidências.</p><p className="mt-2 text-xs text-slate-400">UNI Licitações</p></div><div className="flex w-[42%] items-center justify-center bg-gradient-to-br from-slate-900 to-blue-950 p-6 text-center text-sm font-semibold text-white">Inteligência para oportunidades reais.</div></section></div>
  </div></div>;
}
