import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const U=Deno.env.get("SUPABASE_URL")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,MODEL=Deno.env.get("GEMINI_MODEL")||"gemini-2.5-flash-lite",WORKER_ID="uni-analysis-worker-gemini-v6";
const MAX_PDF_BYTES=8*1024*1024,MAX_TOTAL_PDF_BYTES=16*1024*1024;
const db=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,"content-type":"application/json"}});
const versionNumber=(v:unknown)=>{const m=String(v??"").match(/(\d+)$/);return m?Number(m[1]):null};
const methodVersion=(v:unknown)=>{const m=String(v??"").match(/v\d+(?:\.\d+)?/i);return m?m[0].toLowerCase():null};
const clamp100=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const rec=(v:unknown)=>{const x=String(v??"revisao_manual").toLowerCase();return ["aprovado","aprovado_com_ressalva","nao_aprovado","revisao_manual"].includes(x)?x:"revisao_manual"};
const hashJson=async(v:unknown)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v))))).map(b=>b.toString(16).padStart(2,"0")).join("");
function base64(bytes:Uint8Array){let out="";for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(out)}
function errorText(e:unknown){if(e instanceof Error)return e.message;if(e&&typeof e==="object"){const r=e as Record<string,unknown>,parts=[r.message,r.error,r.details,r.hint,r.code].filter(Boolean).map(v=>typeof v==="object"?JSON.stringify(v):String(v));if(parts.length)return parts.join(" · ");try{return JSON.stringify(e)}catch{return"unknown_error"}}return String(e??"unknown_error")}
async function callGemini(parts:any[],key:string){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(MODEL)}:generateContent`,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{parts}],generationConfig:{temperature:0.1,responseMimeType:"application/json"}})});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(`gemini_http_${response.status}:${body?.error?.message??"unknown"}`);const text=body?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text??"").join("")??"";if(!text)throw new Error("gemini_empty_response");let parsed:any;try{parsed=JSON.parse(text.replace(/^```json\s*/i,"").replace(/```$/i,"").trim())}catch{throw new Error("gemini_invalid_json")}return{parsed,raw:body,requestId:response.headers.get("x-request-id")||crypto.randomUUID()}}

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:C});
 if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const geminiKey=Deno.env.get("GEMINI_API_KEY");if(!geminiKey)return json({error:"gemini_not_configured"},503);
 const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const{data:userData,error:userError}=await db.auth.getUser(token);if(userError||!userData.user)return json({error:"unauthorized"},401);
 const input=await req.json().catch(()=>({})),queueId=String(input?.queue_id||"");if(!queueId)return json({error:"queue_id_required"},400);
 const{data:queue,error:queueError}=await db.from("opportunity_ai_analysis_queue").select("id,client_id,status,context_snapshot").eq("id",queueId).maybeSingle();if(queueError||!queue)return json({error:"queue_not_found"},404);
 const[{data:membership},{data:owner}]=await Promise.all([db.from("client_members").select("client_id").eq("client_id",queue.client_id).eq("user_id",userData.user.id).maybeSingle(),db.from("platform_user_roles").select("user_id").eq("user_id",userData.user.id).eq("role","platform_owner").eq("active",true).maybeSingle()]);if(!membership&&!owner)return json({error:"forbidden"},403);
 const{data:claimed,error:claimError}=await db.rpc("claim_opportunity_ai_analysis_job_service",{p_queue_id:queueId,p_client_id:queue.client_id,p_worker_id:WORKER_ID});if(claimError)return json({error:"queue_claim_failed",detail:claimError.message},409);const job=Array.isArray(claimed)?claimed[0]:null;if(!job){if(queue.status==="completed")return json({ok:true,status:"completed",queue_id:queueId,already_completed:true});return json({error:"queue_not_runnable",status:queue.status},409)}
 let aiExecutionId:string|null=null;
 try{
  const pbn=versionNumber(job.playbook_version),pvn=versionNumber(job.profile_version),mv=methodVersion(job.prompt_master_version);if(pbn===null)throw new Error("invalid_playbook_version");if(pvn===null)throw new Error("invalid_profile_version");if(!mv)throw new Error("invalid_prompt_master_version");
  const[opRes,docsRes,pbRes,profileRes,methodRes,allItemsRes,selectedRes]=await Promise.all([
   db.from("public_opportunities").select("id,source_id,buyer_name,buyer_document,process_number,modality,title,object_text,publication_date,proposal_deadline,estimated_value,state,city,lifecycle").eq("id",job.opportunity_id).maybeSingle(),
   db.from("opportunity_documents").select("id,storage_bucket,storage_path,original_filename,mime_type,file_size_bytes,source_kind,validation_status,uploaded_at,metadata").eq("client_id",job.client_id).eq("opportunity_id",job.opportunity_id).eq("validation_status","available").order("uploaded_at"),
   db.from("playbooks").select("id,version_no,payload,is_current").eq("client_id",job.client_id).eq("version_no",pbn).maybeSingle(),
   db.from("client_profiles").select("id,version_no,payload,is_current").eq("client_id",job.client_id).eq("version_no",pvn).maybeSingle(),
   db.from("method_versions").select("id,method_name,version,status,content,metadata,checksum").eq("version",mv).eq("status","official").maybeSingle(),
   db.from("public_opportunity_items").select("id,item_number,description,quantity,unit,estimated_unit_value,estimated_total_value").eq("opportunity_id",job.opportunity_id).order("item_number"),
   db.from("client_opportunity_item_selections").select("item_id").eq("client_id",job.client_id).eq("opportunity_id",job.opportunity_id).eq("selected",true)
  ]);for(const x of[opRes,docsRes,pbRes,profileRes,methodRes,allItemsRes,selectedRes])if(x.error)throw x.error;
  const op=opRes.data,docs=docsRes.data??[],playbook=pbRes.data,profile=profileRes.data,method=methodRes.data,allItems=allItemsRes.data??[];if(!op)throw new Error("opportunity_not_found");if(!playbook)throw new Error("playbook_version_not_found");if(!profile)throw new Error("profile_version_not_found");if(!method?.content)throw new Error("prompt_master_content_not_found");
  const liveIds=new Set((selectedRes.data??[]).map((x:any)=>String(x.item_id)));const snapRaw=(queue.context_snapshot as any)?.selection_snapshot?.selected_item_ids;const snapshotIds=Array.isArray(snapRaw)?new Set(snapRaw.map((x:any)=>String(x))):null;const chosenIds=snapshotIds&&snapshotIds.size?snapshotIds:liveIds;const selectedItems=allItems.length?allItems.filter((x:any)=>chosenIds.has(String(x.id))):[];if(allItems.length&&!selectedItems.length)throw new Error("no_items_selected_for_detailed_analysis");
  const documentMeta=docs.map((d:any)=>({id:d.id,name:d.original_filename,mimeType:d.mime_type,size:d.file_size_bytes,sourceKind:d.source_kind,validationStatus:d.validation_status,uploadedAt:d.uploaded_at,metadata:d.metadata}));
  const context={schemaVersion:"6.0",queueId,clientId:job.client_id,capabilityId:job.capability_id,opportunityId:job.opportunity_id,triageRunId:job.triage_run_id,versions:{promptMaster:job.prompt_master_version,profile:job.profile_version,playbook:job.playbook_version},method:{id:method.id,methodName:method.method_name,version:method.version,checksum:method.checksum,metadata:method.metadata},profile:profile.payload??{},playbook:playbook.payload??{},opportunity:op,selectedItems,selection:{selectedCount:selectedItems.length,totalItems:allItems.length,scope:allItems.length?"selected_items_only":"opportunity_without_structured_items",source:snapshotIds&&snapshotIds.size?"enqueue_snapshot":"live_fallback"},documents:documentMeta,deterministicContext:{externalInference:true,provider:"google-gemini",model:MODEL}};
  const contextHash=await hashJson(context);await db.from("opportunity_ai_analysis_queue").update({context_snapshot:context,context_hash:contextHash,model_provider:"google-gemini",model_name:MODEL,heartbeat_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",queueId).eq("locked_by",WORKER_ID);
  const parts:any[]=[{text:`PROMPT MESTRE OFICIAL — ${method.version}\n\n${method.content}`},{text:`PERFIL EMPRESARIAL VERSIONADO:\n${JSON.stringify(profile.payload??{})}`},{text:`PLAYBOOK OPERACIONAL VERSIONADO:\n${JSON.stringify(playbook.payload??{})}`},{text:`TAREFA: Execute a Análise Detalhada aplicando integralmente o Prompt Mestre, Perfil e Playbook. QUANDO HOUVER ITENS ESTRUTURADOS, ANALISE EXCLUSIVAMENTE OS PRODUTOS SELECIONADOS EM selectedItems; não avalie, aprove, reprove nem cote itens não selecionados. Não invente dados. Preserve a precedência normativa. Se documento essencial não estiver disponível ou não tiver sido lido, declare a limitação e use revisao_manual quando impedir conclusão segura. Terminologia final: APROVADO, APROVADO COM RESSALVA, NÃO APROVADO. Retorne SOMENTE JSON com recommendation, summary, technical_score, commercial_score, confidence, blockers, warnings, gate_results e evidence. CONTEXTO: ${JSON.stringify(context)}`}];
  let totalPdfBytes=0;const includedDocs:string[]=[],omittedDocs:{name:string;reason:string}[]=[];for(const d of docs){const mime=String((d as any).mime_type??"").toLowerCase();if(mime!=="application/pdf"){omittedDocs.push({name:(d as any).original_filename,reason:"unsupported_inline_mime"});continue}const size=Number((d as any).file_size_bytes??0);if(size<=0||size>MAX_PDF_BYTES||totalPdfBytes+size>MAX_TOTAL_PDF_BYTES){omittedDocs.push({name:(d as any).original_filename,reason:"size_limit"});continue}const{data:file,error:fileError}=await db.storage.from((d as any).storage_bucket).download((d as any).storage_path);if(fileError||!file){omittedDocs.push({name:(d as any).original_filename,reason:"download_failed"});continue}const bytes=new Uint8Array(await file.arrayBuffer());totalPdfBytes+=bytes.length;includedDocs.push((d as any).original_filename);parts.push({text:`DOCUMENTO OFICIAL/ANEXO: ${(d as any).original_filename}`},{inlineData:{mimeType:"application/pdf",data:base64(bytes)}})}parts.push({text:`CONTROLE DOCUMENTAL: PDFs incluídos=${JSON.stringify(includedDocs)}. Omitidos=${JSON.stringify(omittedDocs)}. Não trate documento omitido como lido.`});
  const{data:aiExec}=await db.from("ai_executions").insert({client_id:job.client_id,playbook_id:playbook.id,model_name:MODEL,execution_type:"opportunity_detailed_analysis",created_by:userData.user.id,result:{status:"processing",queue_id:queueId,context_hash:contextHash,selected_item_ids:selectedItems.map((x:any)=>x.id)},evidence:{included_documents:includedDocs,omitted_documents:omittedDocs,selected_items:selectedItems}}).select("id").maybeSingle();aiExecutionId=aiExec?.id??null;
  const started=Date.now(),gemini=await callGemini(parts,geminiKey),latency=Date.now()-started,r=gemini.parsed??{},recommendation=rec(r.recommendation);const evidence=Array.isArray(r.evidence)?r.evidence.slice(0,50).map((e:any)=>({source:String(e?.source??"Gemini"),locator:e?.locator?String(e.locator):null,finding:String(e?.finding??""),metadata:{provider:"google-gemini",model:MODEL,methodVersion:method.version}})):[];
  const payload={schemaVersion:"6.0",summary:String(r.summary??""),technicalScore:clamp100(r.technical_score),commercialScore:clamp100(r.commercial_score),confidence:clamp100(r.confidence),blockers:Array.isArray(r.blockers)?r.blockers.map(String):[],warnings:Array.isArray(r.warnings)?r.warnings.map(String):[],contextHash,provider:"google-gemini",model:MODEL,method:{version:method.version,checksum:method.checksum},profileVersion:pvn,playbookVersion:pbn,selectedItems,documents:{included:includedDocs,omitted:omittedDocs},usage:{promptTokens:gemini.raw?.usageMetadata?.promptTokenCount??null,candidatesTokens:gemini.raw?.usageMetadata?.candidatesTokenCount??null,totalTokens:gemini.raw?.usageMetadata?.totalTokenCount??null,latencyMs:latency,billingMode:"free-tier-validation"}};
  const{data:resultId,error:completeError}=await db.rpc("complete_opportunity_ai_analysis_job_service",{p_queue_id:queueId,p_worker_id:WORKER_ID,p_recommendation:recommendation,p_gate_results:r.gate_results&&typeof r.gate_results==="object"?r.gate_results:{},p_evidence:evidence,p_analysis_payload:payload,p_model_provider:"google-gemini",p_model_name:MODEL,p_provider_request_id:gemini.requestId});if(completeError)throw completeError;
  if(aiExecutionId)await db.from("ai_executions").update({result:{status:"completed",queue_id:queueId,result_id:resultId,context_hash:contextHash,recommendation,payload},evidence:{included_documents:includedDocs,omitted_documents:omittedDocs,evidence,selected_items:selectedItems,method_checksum:method.checksum}}).eq("id",aiExecutionId);
  await db.from("audit_events").insert({client_id:job.client_id,actor_user_id:userData.user.id,event_type:"ai_analysis_completed",entity_type:"opportunity_ai_analysis_queue",entity_id:queueId,after_data:{result_id:resultId,provider:"google-gemini",model:MODEL,recommendation,context_hash:contextHash,selected_item_ids:selectedItems.map((x:any)=>x.id)}});
  return json({ok:true,status:"completed",queue_id:queueId,result_id:resultId,recommendation,selected_items:selectedItems.length,documents_included:includedDocs.length,documents_omitted:omittedDocs.length,selection_source:context.selection.source});
 }catch(e){const message=errorText(e);const{data:failureStatus,error:failError}=await db.rpc("fail_opportunity_ai_analysis_job_service",{p_queue_id:queueId,p_worker_id:WORKER_ID,p_error:message,p_retry_delay_seconds:60});if(aiExecutionId)await db.from("ai_executions").update({result:{status:"failed",queue_id:queueId,error:message}}).eq("id",aiExecutionId);await db.from("audit_events").insert({client_id:job.client_id,actor_user_id:userData.user.id,event_type:"ai_analysis_failed",entity_type:"opportunity_ai_analysis_queue",entity_id:queueId,after_data:{provider:"google-gemini",model:MODEL,error:message,status:failureStatus??null}});return json({ok:false,status:failureStatus??"failed",queue_id:queueId,error:message,fail_error:failError?.message??null},500)}
});