"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Props={clientId:string;onClose:()=>void;onOpenEnvironment:(id:string)=>void};
type Row=Record<string,unknown>;
const txt=(v:unknown)=>v===null||v===undefined||v===""?"—":String(v);
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};
const mask=(v:unknown)=>String(v??"").replace(/\D/g,"").replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,"$1.$2.$3/$4-$5");
export default function ClientDossier({clientId,onClose,onOpenEnvironment}:Props){
 const[client,setClient]=useState<Row|null>(null),[enterprise,setEnterprise]=useState<Row|null>(null),[docs,setDocs]=useState<Row[]>([]),[sicaf,setSicaf]=useState<Row[]>([]),[readiness,setReadiness]=useState<Row[]>([]),[pending,setPending]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!supabase)return;void(async()=>{setLoading(true);setError("");try{const[c,e,d,s,r,p]=await Promise.all([supabase.from("clients").select("id,legal_name,display_name,status,created_at").eq("id",clientId).single(),supabase.from("client_enterprise_data").select("*").eq("client_id",clientId).eq("is_current",true).maybeSingle(),supabase.from("client_documents").select("id,original_filename,document_identifier,issuing_body,issue_date,expiry_date,validation_status,is_current,uploaded_at,storage_bucket,storage_path").eq("client_id",clientId).order("uploaded_at",{ascending:false}),supabase.from("client_sicaf_status").select("sicaf_level_id,status,observations,last_checked_at").eq("client_id",clientId).order("sicaf_level_id"),supabase.from("client_operational_readiness").select("radar_status,participation_released,blocking_reason,evaluated_at,method_version").eq("client_id",clientId),supabase.from("client_pending_items").select("id,title,impact,state,due_date").eq("client_id",clientId).not("state","in","(resolvida,cancelada)").order("created_at",{ascending:false})]);for(const x of[c,e,d,s,r,p])if(x.error)throw x.error;setClient(c.data as Row);setEnterprise(e.data as Row|null);setDocs((d.data??[]) as Row[]);setSicaf((s.data??[]) as Row[]);setReadiness((r.data??[]) as Row[]);setPending((p.data??[]) as Row[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}})()},[clientId]);
 const expired=useMemo(()=>docs.filter(d=>d.expiry_date&&new Date(String(d.expiry_date)).getTime()<Date.now()).length,[docs]);const currentDocs=docs.filter(d=>d.is_current!==false);const blocked=pending.filter(p=>String(p.impact).includes("bloqueia")).length;const released=readiness.some(r=>r.participation_released===true);const status=released&&blocked===0&&expired===0?"APTO":blocked>0||expired>0?"APTO COM PENDÊNCIAS":"EM PREPARAÇÃO";
 if(loading)return <div className="rounded-2xl border bg-white p-8 text-sm text-slate-500">Carregando dossiê do cliente...</div>;
 if(error)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700">Falha ao carregar dossiê: {error}</div>;
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><button onClick={onClose} className="text-xs font-semibold text-blue-700">← Voltar aos clientes</button><h2 className="mt-2 text-2xl font-bold">{txt(client?.display_name??client?.legal_name)}</h2><p className="text-sm text-slate-500">Dossiê cadastral, documental e de habilitação</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-2 text-xs font-bold ${status==="APTO"?"bg-emerald-50 text-emerald-700":status.includes("PENDÊNCIAS")?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>{status}</span><button onClick={()=>onOpenEnvironment(clientId)} className="rounded-xl bg-blue-700 px-4 py-2 text-xs font-bold text-white">Abrir ambiente</button></div></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Dados cadastrais</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["CNPJ",mask(enterprise?.cnpj)],["Razão social",txt(enterprise?.legal_name??client?.legal_name)],["Nome fantasia",txt(enterprise?.trade_name??client?.display_name)],["Regime tributário",txt(enterprise?.tax_regime)],["Inscrição estadual",txt(enterprise?.state_registration)],["Inscrição municipal",txt(enterprise?.municipal_registration)],["Município",txt(enterprise?.headquarters_city)],["UF",txt(enterprise?.headquarters_state)],["Situação cadastral",txt(enterprise?.validation_status)],["Última validação",date(enterprise?.validated_at)]].map(([k,v])=><div key={k}><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{k}</p><p className="mt-1 text-sm font-medium">{v}</p></div>)}</div>{Array.isArray(enterprise?.cnaes)&&<div className="mt-5"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">CNAEs</p><pre className="mt-2 max-h-40 overflow-auto rounded-xl bg-slate-50 p-3 text-xs whitespace-pre-wrap">{JSON.stringify(enterprise?.cnaes,null,2)}</pre></div>}</section>
 <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-bold">Documentos</h3><p className="text-xs text-slate-500">{currentDocs.length} atuais · {expired} vencidos</p></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-xs"><thead className="bg-slate-50"><tr>{["Documento","Órgão","Emissão","Validade","Validação"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{currentDocs.map(d=><tr key={String(d.id)}><td className="px-4 py-3 font-semibold">{txt(d.original_filename??d.document_identifier)}</td><td className="px-4 py-3">{txt(d.issuing_body)}</td><td className="px-4 py-3">{date(d.issue_date)}</td><td className="px-4 py-3">{date(d.expiry_date)}</td><td className="px-4 py-3">{txt(d.validation_status)}</td></tr>)}{currentDocs.length===0&&<tr><td colSpan={5} className="p-6 text-center text-slate-400">Nenhum documento cadastrado.</td></tr>}</tbody></table></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Habilitação</h3><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Pendências abertas</span><b>{pending.length}</b></div><div className="flex justify-between"><span>Bloqueadoras</span><b>{blocked}</b></div><div className="flex justify-between"><span>Níveis SICAF</span><b>{sicaf.length}</b></div><div className="flex justify-between"><span>Participação liberada</span><b>{released?"Sim":"Não"}</b></div></div>{pending.length>0&&<div className="mt-5 space-y-2">{pending.slice(0,6).map(p=><div key={String(p.id)} className="rounded-xl bg-amber-50 p-3 text-xs"><b>{txt(p.title)}</b><p className="mt-1 text-amber-800">{txt(p.impact)} · {txt(p.state)}</p></div>)}</div>}</section></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">SICAF e prontidão operacional</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sicaf.map((s,i)=><div key={i} className="rounded-xl border p-3 text-xs"><b>Nível {txt(s.sicaf_level_id)}</b><p className="mt-1">{txt(s.status)}</p><p className="mt-1 text-slate-400">Verificado: {date(s.last_checked_at)}</p></div>)}{readiness.map((r,i)=><div key={`r-${i}`} className="rounded-xl border p-3 text-xs"><b>Prontidão</b><p className="mt-1">Radar: {txt(r.radar_status)}</p><p className="mt-1">Participação: {r.participation_released?"liberada":"não liberada"}</p></div>)}</div></section></div>;
}
