"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Props={clientId:string;onClose:()=>void;onOpenEnvironment:(id:string)=>void};
type Row=Record<string,unknown>;
const REFERENCE_NOW=Date.now();
const txt=(v:unknown)=>v===null||v===undefined||v===""?"—":String(v);
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};
const mask=(v:unknown)=>String(v??"").replace(/\D/g,"").replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,"$1.$2.$3/$4-$5");
const statusLabel=(v:unknown)=>({atende:"Validado",impeditivo:"Divergente",pendente:"Pendente",nao_iniciado:"Não iniciado",em_preparacao:"Em preparação"}[String(v)]||txt(v));

export default function ClientDossier({clientId,onClose,onOpenEnvironment}:Props){
 const[client,setClient]=useState<Row|null>(null),[enterprise,setEnterprise]=useState<Row|null>(null),[docs,setDocs]=useState<Row[]>([]),[sicaf,setSicaf]=useState<Row[]>([]),[readiness,setReadiness]=useState<Row[]>([]),[pending,setPending]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){if(!supabase)return;setLoading(true);setError("");try{const[c,e,d,s,r,p]=await Promise.all([supabase.from("clients").select("id,legal_name,display_name,status,created_at").eq("id",clientId).single(),supabase.from("client_enterprise_data").select("*").eq("client_id",clientId).eq("is_current",true).maybeSingle(),supabase.from("client_documents").select("id,original_filename,document_identifier,issuing_body,issue_date,expiry_date,validation_status,is_current,uploaded_at,storage_bucket,storage_path").eq("client_id",clientId).order("uploaded_at",{ascending:false}),supabase.from("client_sicaf_status").select("sicaf_level_id,status,observations,last_checked_at,evidence_document_id").eq("client_id",clientId).order("sicaf_level_id"),supabase.from("client_operational_readiness").select("radar_status,participation_released,blocking_reason,evaluated_at,method_version").eq("client_id",clientId),supabase.from("client_pending_items").select("id,title,impact,state,due_date").eq("client_id",clientId).not("state","in","(resolvida,cancelada)").order("created_at",{ascending:false})]);for(const x of[c,e,d,s,r,p])if(x.error)throw x.error;setClient(c.data as Row);setEnterprise(e.data as Row|null);setDocs((d.data??[]) as Row[]);setSicaf((s.data??[]) as Row[]);setReadiness((r.data??[]) as Row[]);setPending((p.data??[]) as Row[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[clientId]);
 const expired=useMemo(()=>docs.filter(d=>d.expiry_date&&new Date(String(d.expiry_date)).getTime()<REFERENCE_NOW).length,[docs]);const currentDocs=docs.filter(d=>d.is_current!==false);const blocked=pending.filter(p=>String(p.impact).includes("bloqueia")).length;const released=readiness.some(r=>r.participation_released===true);const status=released&&blocked===0&&expired===0?"APTO":blocked>0||expired>0?"APTO COM PENDÊNCIAS":"EM PREPARAÇÃO";
 async function openDoc(d:Row){if(!supabase)return;const{data,error}=await supabase.storage.from(String(d.storage_bucket)).createSignedUrl(String(d.storage_path),60);if(error||!data?.signedUrl){setMessage("Não foi possível abrir o documento.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function reviewDoc(d:Row,decision:"approved"|"divergent"|"pending"){if(!supabase)return;setBusy(`doc-${d.id}`);setMessage("");try{const{data,error}=await supabase.functions.invoke("owner-document-review",{body:{client_id:clientId,document_id:d.id,decision}});if(error||!data?.ok)throw new Error(data?.detail||error?.message||"Falha na validação do documento.");setMessage(decision==="approved"?"Documento validado pelo Owner.":decision==="divergent"?"Documento marcado como divergente.":"Documento devolvido para pendência.");await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 async function setSicaf(s:Row,next:"atende"|"pendente"|"impeditivo"){if(!supabase)return;setBusy(`sicaf-${s.sicaf_level_id}`);setMessage("");try{const{data,error}=await supabase.functions.invoke("sicaf-workspace",{body:{action:"set",client_id:clientId,level_id:Number(s.sicaf_level_id),status:next,observations:s.observations??null,evidence_document_id:s.evidence_document_id??null}});if(error||!data?.ok)throw new Error(data?.detail||error?.message||"Falha ao atualizar o nível SICAF.");setMessage(`Nível ${s.sicaf_level_id} atualizado para ${statusLabel(next)}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 function openModule(module:string){onOpenEnvironment(clientId);window.setTimeout(()=>window.dispatchEvent(new CustomEvent("uni-navigate",{detail:module})),120)}
 if(loading)return <div className="rounded-2xl border bg-white p-8 text-sm text-slate-500">Carregando dossiê do cliente...</div>;
 if(error)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700">Falha ao carregar dossiê: {error}</div>;
 return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><button onClick={onClose} className="text-xs font-semibold text-blue-700">← Voltar aos clientes</button><h2 className="mt-2 text-2xl font-bold">{txt(client?.display_name??client?.legal_name)}</h2><p className="text-sm text-slate-500">Dossiê cadastral, documental e de habilitação — validação administrativa do Owner</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-2 text-xs font-bold ${status==="APTO"?"bg-emerald-50 text-emerald-700":status.includes("PENDÊNCIAS")?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>{status}</span><button onClick={()=>openModule("Documentos")} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">Validar documentos</button><button onClick={()=>openModule("SICAF")} className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">Abrir SICAF</button><button onClick={()=>onOpenEnvironment(clientId)} className="rounded-xl bg-blue-700 px-4 py-2 text-xs font-bold text-white">Abrir ambiente</button></div></div>
 {message&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{message}</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Dados cadastrais</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["CNPJ",mask(enterprise?.cnpj)],["Razão social",txt(enterprise?.legal_name??client?.legal_name)],["Nome fantasia",txt(enterprise?.trade_name??client?.display_name)],["Regime tributário",txt(enterprise?.tax_regime)],["Inscrição estadual",txt(enterprise?.state_registration)],["Inscrição municipal",txt(enterprise?.municipal_registration)],["Município",txt(enterprise?.headquarters_city)],["UF",txt(enterprise?.headquarters_state)],["Situação cadastral",txt(enterprise?.validation_status)],["Última validação",date(enterprise?.validated_at)]].map(([k,v])=><div key={k}><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{k}</p><p className="mt-1 text-sm font-medium">{v}</p></div>)}</div></section>
 <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="font-bold">Documentos</h3><p className="text-xs text-slate-500">{currentDocs.length} atuais · {expired} vencidos · decisão reservada ao Owner</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-xs"><thead className="bg-slate-50"><tr>{["Documento","Órgão","Emissão","Validade","Validação","Ações"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{currentDocs.map(d=><tr key={String(d.id)}><td className="px-4 py-3 font-semibold">{txt(d.original_filename??d.document_identifier)}</td><td className="px-4 py-3">{txt(d.issuing_body)}</td><td className="px-4 py-3">{date(d.issue_date)}</td><td className="px-4 py-3">{date(d.expiry_date)}</td><td className="px-4 py-3 font-semibold">{statusLabel(d.validation_status)}</td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={()=>void openDoc(d)} className="rounded border px-2 py-1">Abrir</button><button disabled={busy===`doc-${d.id}`} onClick={()=>void reviewDoc(d,"approved")} className="rounded bg-emerald-600 px-2 py-1 font-bold text-white disabled:opacity-40">Validar</button><button disabled={busy===`doc-${d.id}`} onClick={()=>void reviewDoc(d,"divergent")} className="rounded bg-rose-50 px-2 py-1 font-semibold text-rose-700 disabled:opacity-40">Divergente</button></div></td></tr>)}{currentDocs.length===0&&<tr><td colSpan={6} className="p-6 text-center text-slate-400">Nenhum documento cadastrado.</td></tr>}</tbody></table></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Habilitação</h3><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Pendências abertas</span><b>{pending.length}</b></div><div className="flex justify-between"><span>Bloqueadoras</span><b>{blocked}</b></div><div className="flex justify-between"><span>Níveis SICAF</span><b>{sicaf.length}</b></div><div className="flex justify-between"><span>Participação liberada</span><b>{released?"Sim":"Não"}</b></div></div>{pending.length>0&&<div className="mt-5 space-y-2">{pending.slice(0,6).map(p=><div key={String(p.id)} className="rounded-xl bg-amber-50 p-3 text-xs"><b>{txt(p.title)}</b><p className="mt-1 text-amber-800">{txt(p.impact)} · {txt(p.state)}</p></div>)}</div>}</section></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-bold">SICAF e níveis de habilitação</h3><p className="mt-1 text-xs text-slate-500">O Owner conclui cada nível; o cliente apenas acompanha o status.</p></div><button onClick={()=>openModule("SICAF")} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Gerenciar SICAF completo</button></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{sicaf.map((s,i)=><div key={i} className="rounded-xl border p-3 text-xs"><div className="flex items-start justify-between gap-3"><div><b>Nível {txt(s.sicaf_level_id)}</b><p className="mt-1 font-semibold">{statusLabel(s.status)}</p><p className="mt-1 text-slate-400">Verificado: {date(s.last_checked_at)}</p></div><div className="flex flex-wrap justify-end gap-1"><button disabled={busy===`sicaf-${s.sicaf_level_id}`} onClick={()=>void setSicaf(s,"atende")} className="rounded bg-emerald-600 px-2 py-1 font-bold text-white disabled:opacity-40">Concluir</button><button disabled={busy===`sicaf-${s.sicaf_level_id}`} onClick={()=>void setSicaf(s,"pendente")} className="rounded bg-amber-50 px-2 py-1 font-semibold text-amber-700 disabled:opacity-40">Pendente</button><button disabled={busy===`sicaf-${s.sicaf_level_id}`} onClick={()=>void setSicaf(s,"impeditivo")} className="rounded bg-rose-50 px-2 py-1 font-semibold text-rose-700 disabled:opacity-40">Impeditivo</button></div></div></div>)}{readiness.map((r,i)=><div key={`r-${i}`} className="rounded-xl border p-3 text-xs"><b>Prontidão operacional</b><p className="mt-1">Radar: {txt(r.radar_status)}</p><p className="mt-1">Participação: {r.participation_released?"liberada":"não liberada"}</p></div>)}</div></section></div>;
}
