"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import ClientDossier from "@/modules/onboarding/ClientDossier";

type Client={id:string;legal_name:string;display_name:string|null;status:string};
type AccessRequest={id:string;cnpj:string;email:string;login:string;status:string;client_id:string|null;created_at:string;reviewed_at:string|null;rejection_reason:string|null};
const maskCnpj=(v:string)=>v.replace(/\D/g,"").replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2");
const statusLabel=(s:string)=>s==="ready"?"Pronto":s==="onboarding"?"Em cadastro":s;

export default function OwnerWorkspace({onOpenClient}:{onOpenClient:(id:string)=>void}){
 const[clients,setClients]=useState<Client[]>([]),[requests,setRequests]=useState<AccessRequest[]>([]),[selected,setSelected]=useState<string|null>(null),[busyId,setBusyId]=useState<string|null>(null),[message,setMessage]=useState("");
 async function loadClients(){if(!supabase)return;const{data,error}=await supabase.from("clients").select("id,legal_name,display_name,status").neq("status","inactive").order("legal_name");if(error){setMessage(`Não foi possível carregar os clientes: ${error.message}`);return}setClients((data??[])as Client[])}
 async function loadRequests(){if(!supabase)return;const{data,error}=await supabase.functions.invoke("company-access-requests",{body:{action:"list"}});if(error||!data?.ok){setMessage("Não foi possível carregar as solicitações de acesso.");return}setRequests((data.requests??[])as AccessRequest[])}
 useEffect(()=>{void Promise.all([loadClients(),loadRequests()])},[]);
 async function decide(requestId:string,action:"approve"|"reject"){if(!supabase||busyId)return;setBusyId(requestId);setMessage("");try{const{data,error}=await supabase.functions.invoke("company-access-requests",{body:{action,request_id:requestId}});if(error||!data?.ok)throw new Error(data?.detail||"A decisão não pôde ser concluída.");setMessage(action==="approve"?"Empresa aprovada. O onboarding já está liberado.":"Solicitação recusada.");await Promise.all([loadClients(),loadRequests()])}catch(e){setMessage(e instanceof Error?e.message:"A decisão não pôde ser concluída.")}finally{setBusyId(null)}}
 if(selected)return <div className="mx-auto w-full max-w-[1440px] p-5 sm:p-7"><ClientDossier clientId={selected} onClose={()=>setSelected(null)} onOpenEnvironment={onOpenClient}/></div>;
 const pending=requests.filter(r=>r.status==="pending"),recent=requests.filter(r=>r.status!=="pending").slice(0,5),ready=clients.filter(c=>c.status==="ready").length;
 return <div className="mx-auto w-full max-w-[1440px] p-5 sm:p-7 xl:p-9">
  <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Painel Owner</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">Clientes</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Controle de acesso, cadastro e entrada nos ambientes operacionais do UNI.</p></div><button onClick={()=>void Promise.all([loadClients(),loadRequests()])} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 shadow-sm">Atualizar painel</button></div>
  <div className="mb-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">Clientes ativos</p><p className="mt-2 text-3xl font-black text-slate-900">{clients.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">Prontos para operar</p><p className="mt-2 text-3xl font-black text-emerald-600">{ready}</p></div><div className={`rounded-2xl border p-5 shadow-sm ${pending.length?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}><p className="text-xs font-semibold text-slate-500">Aguardando aprovação</p><p className={`mt-2 text-3xl font-black ${pending.length?"text-amber-700":"text-slate-900"}`}>{pending.length}</p></div></div>
  {message&&<div className="mb-5 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-medium text-blue-800">{message}</div>}
  {pending.length>0&&<section className="mb-6 overflow-hidden rounded-2xl border border-amber-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-amber-100 bg-amber-50 px-5 py-4"><div><h2 className="font-bold text-slate-900">Solicitações aguardando decisão</h2><p className="mt-1 text-xs text-slate-500">Aprovar libera o cliente para concluir o cadastro inicial.</p></div><span className="rounded-full bg-amber-200 px-2.5 py-1 text-xs font-black text-amber-900">{pending.length}</span></div><div className="divide-y divide-slate-100">{pending.map(r=><div key={r.id} className="grid gap-4 px-5 py-4 lg:grid-cols-[1.2fr_1fr_1fr_auto] lg:items-center"><div><b className="block text-sm">{maskCnpj(r.cnpj)}</b><span className="text-[11px] text-slate-500">{new Date(r.created_at).toLocaleString("pt-BR")}</span></div><div><p className="text-xs font-semibold">{r.email}</p><p className="text-[10px] text-slate-400">E-mail</p></div><div><p className="text-xs font-semibold">{r.login}</p><p className="text-[10px] text-slate-400">Usuário UNI</p></div><div className="flex gap-2"><button onClick={()=>void decide(r.id,"reject")} disabled={busyId===r.id} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700 disabled:opacity-50">Recusar</button><button onClick={()=>void decide(r.id,"approve")} disabled={busyId===r.id} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busyId===r.id?"Processando...":"Aprovar"}</button></div></div>)}</div></section>}
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Ambientes de clientes</h2><p className="mt-1 text-xs text-slate-500">Entre no ambiente operacional ou consulte o dossiê administrativo.</p></div>{clients.length===0?<div className="p-8 text-center"><p className="text-sm font-semibold text-slate-700">Nenhum cliente cadastrado</p><p className="mt-1 text-xs text-slate-500">Novos clientes aparecerão aqui após a aprovação do acesso.</p></div>:<div className="divide-y divide-slate-100">{clients.map(c=><div key={c.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-sm font-black text-slate-600">{(c.display_name||c.legal_name).slice(0,2).toUpperCase()}</span><span><b className="block text-sm text-slate-900">{c.display_name||c.legal_name}</b><span className="text-xs text-slate-500">{c.legal_name}</span></span></div><div className="flex items-center gap-2"><span className={`mr-1 rounded-full px-2.5 py-1 text-[10px] font-bold ${c.status==="ready"?"bg-emerald-100 text-emerald-800":"bg-blue-50 text-blue-700"}`}>{statusLabel(c.status)}</span><button onClick={()=>setSelected(c.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">Dossiê</button><button onClick={()=>onOpenClient(c.id)} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Entrar</button></div></div>)}</div>}</section>
  {recent.length>0&&<section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">Histórico recente de acessos</h2><div className="mt-3 flex flex-wrap gap-2">{recent.map(r=><span key={r.id} className="rounded-lg bg-slate-50 px-3 py-2 text-[11px] text-slate-600">{maskCnpj(r.cnpj)} · <b>{r.status==="approved"?"Aprovado":"Recusado"}</b></span>)}</div></section>}
 </div>
}
