"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Client = { id:string; legal_name:string; display_name:string|null; status:string };
type Lookup = { cnpj:string; legal_name:string|null; trade_name:string|null; city:string|null; state:string|null; registration_status:string|null; cnaes:unknown[]; raw_reference?:unknown };
const onlyDigits=(v:string)=>v.replace(/\D/g,"").slice(0,14);
const maskCnpj=(v:string)=>onlyDigits(v).replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2");
const errorMessage=(e:unknown)=>e instanceof Error?e.message:String(e);

export default function OwnerWorkspace({onOpenClient}:{onOpenClient:(id:string)=>void}){
 const [clients,setClients]=useState<Client[]>([]),[cnpj,setCnpj]=useState(""),[lookup,setLookup]=useState<Lookup|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const clean=useMemo(()=>onlyDigits(cnpj),[cnpj]);
 async function loadClients(){if(!supabase)return;const {data,error}=await supabase.from("clients").select("id,legal_name,display_name,status").order("legal_name");if(error){setMessage(`Não foi possível carregar os clientes: ${error.message}`);return}setClients((data??[]) as Client[])}
 useEffect(()=>{void loadClients()},[]);
 async function searchCnpj(){if(!supabase||clean.length!==14)return;setBusy(true);setLookup(null);setMessage("");try{const existing=await supabase.from("client_enterprise_data").select("client_id").eq("cnpj",clean).eq("is_current",true).maybeSingle();if(existing.error)throw existing.error;if(existing.data?.client_id){setMessage("Cliente localizado no UNI. Abrindo o ambiente cadastrado.");onOpenClient(String(existing.data.client_id));return}const {data,error}=await supabase.functions.invoke("cnpj-lookup",{body:{cnpj:clean}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||"Consulta cadastral indisponível.");setLookup(data as Lookup);setMessage("CNPJ localizado. Revise os dados antes de cadastrar o cliente.")}catch(e){setMessage(`Consulta não concluída: ${errorMessage(e)}`)}finally{setBusy(false)}}
 async function createClient(){if(!supabase||!lookup)return;setBusy(true);setMessage("");try{const {data,error}=await supabase.functions.invoke("company-onboarding-start",{body:{cnpj:lookup.cnpj,legal_name:lookup.legal_name||lookup.trade_name||"Empresa",trade_name:lookup.trade_name,city:lookup.city,state:lookup.state,cnaes:lookup.cnaes,source_data:{provider:"BrasilAPI",registration_status:lookup.registration_status,raw_reference:lookup.raw_reference??{}}}});if(error)throw error;if(!data?.ok||!data?.client_id)throw new Error(data?.detail||data?.error||"Cadastro não concluído.");await loadClients();setLookup(null);setMessage("Cliente cadastrado com sucesso.");onOpenClient(String(data.client_id))}catch(e){setMessage(`Cadastro não concluído: ${errorMessage(e)}`)}finally{setBusy(false)}}
 return <div className="mx-auto w-full max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Administração da plataforma</p><h1 className="mt-1 text-3xl font-bold">Cliente</h1><p className="mt-2 text-sm text-slate-500">Localize empresas por CNPJ, evite cadastros duplicados e abra o ambiente do cliente.</p></div>{message&&<div className="mb-5 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Busca por CNPJ</h2><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={maskCnpj(cnpj)} onChange={e=>{setCnpj(e.target.value);setLookup(null)}} placeholder="00.000.000/0000-00" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm"/><button onClick={()=>void searchCnpj()} disabled={busy||clean.length!==14} className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Processando...":"Consultar CNPJ"}</button></div>{lookup&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><b className="text-xs text-emerald-700">Razão social</b><p className="text-sm">{lookup.legal_name||"—"}</p></div><div><b className="text-xs text-emerald-700">Fantasia</b><p className="text-sm">{lookup.trade_name||"—"}</p></div><div><b className="text-xs text-emerald-700">Situação</b><p className="text-sm">{lookup.registration_status||"—"}</p></div><div><b className="text-xs text-emerald-700">Local</b><p className="text-sm">{[lookup.city,lookup.state].filter(Boolean).join("/")||"—"}</p></div></div><button onClick={()=>void createClient()} disabled={busy} className="mt-4 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Cadastrar cliente</button></div>}</section><section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">Clientes cadastrados</h2></div>{clients.length===0?<p className="p-5 text-sm text-slate-500">Nenhum cliente disponível.</p>:<div className="divide-y">{clients.map(c=><button key={c.id} onClick={()=>onOpenClient(c.id)} className="flex w-full items-center justify-between px-5 py-4 text-left hover:bg-slate-50"><span><b className="block text-sm">{c.display_name||c.legal_name}</b><span className="text-xs text-slate-500">{c.legal_name}</span></span><span className="text-xs font-semibold text-blue-700">Abrir ambiente</span></button>)}</div>}</section></div>
}
