"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { loadCurrentClientDashboard, BackendDashboard } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";

type Supplier={id:string;name:string;contact_name:string|null;phone:string|null;email:string|null;website:string|null;categories:string[];notes:string|null;active:boolean;created_at:string;updated_at:string};
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}
function err(v:unknown){if(v instanceof Error)return v.message;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return [o.message,o.details,o.hint,o.code].filter(Boolean).map(String).join(" · ")||"Erro não identificado."}return String(v)}
function safeWebsite(value:string|null){if(!value)return null;try{const url=new URL(value);return url.protocol==="http:"||url.protocol==="https:"?url.toString():null}catch{return null}}
export default function Fornecedores(){
 const [dashboard,setDashboard]=useState<BackendDashboard|null>(null);const [rows,setRows]=useState<Supplier[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [query,setQuery]=useState("");const [form,setForm]=useState({name:"",contact_name:"",phone:"",email:"",website:"",categories:"",notes:""});
 async function load(){setLoading(true);setError("");try{const d=await loadCurrentClientDashboard();if(!d?.client?.id)throw new Error("Tenant não associado.");setDashboard(d);const {data,error:e}=await supabase!.from("client_suppliers").select("id,name,contact_name,phone,email,website,categories,notes,active,created_at,updated_at").eq("client_id",d.client.id).order("active",{ascending:false}).order("name");if(e)throw e;setRows((data??[]) as Supplier[])}catch(e){setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>rows.filter(r=>!query||[r.name,r.contact_name,r.email,r.phone,...(r.categories??[])].join(" ").toLowerCase().includes(query.toLowerCase())),[rows,query]);
 async function add(e:FormEvent){e.preventDefault();if(!supabase||!dashboard?.client?.id||!form.name.trim())return;setBusy(true);setMessage("");try{const website=form.website.trim()?safeWebsite(form.website.trim()):null;if(form.website.trim()&&!website)throw new Error("O site deve usar endereço http:// ou https:// válido.");const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Sessão não autenticada.");const {error:e2}=await supabase.from("client_suppliers").insert({client_id:dashboard.client.id,name:form.name.trim(),contact_name:form.contact_name||null,phone:form.phone||null,email:form.email||null,website,categories:form.categories.split(",").map(v=>v.trim()).filter(Boolean),notes:form.notes||null,created_by:auth.user.id});if(e2)throw e2;setForm({name:"",contact_name:"",phone:"",email:"",website:"",categories:"",notes:""});setMessage("Fornecedor cadastrado com sucesso.");await load()}catch(e2){setMessage(`Não foi possível cadastrar: ${err(e2)}`)}finally{setBusy(false)}}
 async function toggle(row:Supplier){if(!supabase)return;setBusy(true);const {error:e}=await supabase.from("client_suppliers").update({active:!row.active,updated_at:new Date().toISOString()}).eq("id",row.id);if(e)setMessage(`Falha ao atualizar: ${err(e)}`);else{setMessage(row.active?"Fornecedor inativado.":"Fornecedor reativado.");await load()}setBusy(false)}
 if(loading)return <div className="p-8"><div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando fornecedores...</div></div>;
 return <div className="mx-auto max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Fornecedores</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Mapa de Fornecedores</h1><p className="mt-2 text-sm text-slate-500">Cadastro por tenant para apoiar CFP, disponibilidade e rastreabilidade comercial.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Atualizar</button></div>{error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Novo fornecedor</h2><form onSubmit={add} className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Nome do fornecedor" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.contact_name} onChange={e=>setForm(v=>({...v,contact_name:e.target.value}))} placeholder="Contato" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} placeholder="Telefone" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} type="email" placeholder="E-mail" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.website} onChange={e=>setForm(v=>({...v,website:e.target.value}))} type="url" placeholder="https://site.com.br" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.categories} onChange={e=>setForm(v=>({...v,categories:e.target.value}))} placeholder="Categorias separadas por vírgula" className="xl:col-span-2 rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))} placeholder="Observações" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><button disabled={busy||!form.name.trim()} className="sm:col-span-2 xl:col-span-4 rounded-xl bg-blue-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Salvando...":"Cadastrar fornecedor"}</button></form></section>
 <div className="mt-5 flex items-center justify-between gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar fornecedor ou categoria..." className="w-full max-w-md rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"/><span className="text-xs text-slate-500">{rows.filter(r=>r.active).length} ativos · {rows.filter(r=>!r.active).length} inativos</span></div>
 <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Fornecedor","Categorias","Contato","Telefone","E-mail","Site","Situação","Ação"].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map(r=>{const website=safeWebsite(r.website);return <tr key={r.id}><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3">{r.categories?.length?r.categories.join(", "):"—"}</td><td className="px-4 py-3">{text(r.contact_name)}</td><td className="px-4 py-3">{text(r.phone)}</td><td className="px-4 py-3">{r.email?<a className="text-blue-600" href={`mailto:${r.email}`}>{r.email}</a>:"—"}</td><td className="px-4 py-3">{website?<a className="text-blue-600" target="_blank" rel="noopener noreferrer" href={website}>Abrir ↗</a>:r.website?<span className="text-amber-600">URL inválida</span>:"—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{r.active?"ATIVO":"INATIVO"}</span></td><td className="px-4 py-3"><button disabled={busy} onClick={()=>void toggle(r)} className="rounded-lg border border-slate-200 px-3 py-2 font-semibold">{r.active?"Inativar":"Reativar"}</button></td></tr>})}{visible.length===0&&<tr><td colSpan={8} className="px-4 py-8 text-center text-slate-400">Nenhum fornecedor encontrado.</td></tr>}</tbody></table></div></section>{message&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">{message}</div>}
 </div>;
}
