"use client";
import{useEffect,useMemo,useState}from"react";
import{supabase}from"@/lib/supabase";

type Company={client_id:string;display_name:string;legal_name:string;status:string;company_validation_status:string|null};
type Level={id:number;code:string;name:string;description:string|null;status:string;observations:string|null;last_checked_at:string|null;evidence_document_id:string|null};
type Workspace={client_id:string;company_validated:boolean;company_validation_status:string;levels:Level[];checkpoint:{status:string;completion_percent:number;blocking_reason:string|null}|null};
type ClientDocument={id:string;original_filename:string;validation_status:string;expiry_date:string|null;is_current:boolean;extraction_validated:boolean;observations:string|null};

const labels:Record<string,string>={nao_iniciado:"Não iniciado",em_preparacao:"Em preparação",pendente:"Pendente",atende:"Atende",impeditivo:"Impeditivo"};
function err(e:unknown){if(e instanceof Error)return e.message;if(e&&typeof e==="object"&&"message"in e)return String((e as{message?:unknown}).message||"Erro");return String(e||"Erro")}
function isExpired(v:string|null){if(!v)return false;const d=new Date(`${v}T23:59:59`);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()}

export default function SicafHabilitacao(){
 const[companies,setCompanies]=useState<Company[]>([]);const[clientId,setClientId]=useState("");const[workspace,setWorkspace]=useState<Workspace|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState<number|null>(null);const[validating,setValidating]=useState<number|null>(null);const[validatingAll,setValidatingAll]=useState(false);const[error,setError]=useState("");const[msg,setMsg]=useState("");const[notes,setNotes]=useState<Record<number,string>>({});const selected=useMemo(()=>companies.find(c=>c.client_id===clientId),[companies,clientId]);
 async function loadCompanies(){if(!supabase)return;setLoading(true);setError("");try{const{data,error}=await supabase.functions.invoke("sicaf-workspace",{body:{action:"list"}});if(error)throw error;if(!data?.ok)throw new Error(data?.detail||"Falha ao carregar empresas.");const rows=(data.companies??[])as Company[];setCompanies(rows);if(rows.length&&!clientId)setClientId(rows[0].client_id)}catch(e){setError(err(e))}finally{setLoading(false)}}
 async function loadWorkspace(id=clientId){if(!supabase||!id)return;setLoading(true);setError("");try{const{data,error}=await supabase.functions.invoke("sicaf-workspace",{body:{action:"workspace",client_id:id}});if(error)throw error;if(!data?.ok)throw new Error(data?.detail||"Falha ao carregar SICAF.");const w=data.workspace as Workspace;setWorkspace(w);setNotes(Object.fromEntries(w.levels.map(l=>[l.id,l.observations||""])))}catch(e){setWorkspace(null);setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{void loadCompanies()},[]);useEffect(()=>{if(clientId)void loadWorkspace(clientId)},[clientId]);
 async function saveLevel(level:Level,status:string,observations:string){if(!supabase||!workspace)return;const{data,error}=await supabase.functions.invoke("sicaf-workspace",{body:{action:"set",client_id:workspace.client_id,level_id:level.id,status,observations,evidence_document_id:level.evidence_document_id}});if(error)throw error;if(!data?.ok)throw new Error(data?.detail||"Falha ao atualizar nível SICAF.")}
 async function setStatus(level:Level,status:string){if(!supabase||!workspace)return;setSaving(level.id);setError("");setMsg("");try{await saveLevel(level,status,notes[level.id]||"");setMsg(`Nível ${level.id} atualizado para ${labels[status]||status}.`);await loadWorkspace(workspace.client_id)}catch(e){setError(err(e))}finally{setSaving(null)}}
 async function validateLevel(level:Level,refresh=true){if(!supabase||!workspace)return;setValidating(level.id);setError("");setMsg("");try{
   if(!workspace.company_validated)throw new Error("O cadastro empresarial precisa estar validado antes da conferência dos níveis SICAF.");
   if(!level.evidence_document_id){const obs=`Validação automática ${new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date())}: nenhum documento/evidência está vinculado a este nível.`;await saveLevel(level,"pendente",obs);if(refresh){setMsg(`Nível ${level.id}: pendente — vincule o documento exigido para validação.`);await loadWorkspace(workspace.client_id)}return;}
   const{data,error}=await supabase.from("client_documents").select("id,original_filename,validation_status,expiry_date,is_current,extraction_validated,observations").eq("client_id",workspace.client_id).eq("id",level.evidence_document_id).maybeSingle();if(error)throw error;const doc=data as ClientDocument|null;
   let status="pendente";let detail="documento não localizado no cadastro documental";
   if(doc){if(doc.validation_status==="impeditivo"){status="impeditivo";detail=`${doc.original_filename}: documento classificado como impeditivo`;}else if(isExpired(doc.expiry_date)){status="impeditivo";detail=`${doc.original_filename}: documento vencido em ${new Intl.DateTimeFormat("pt-BR").format(new Date(`${doc.expiry_date}T12:00:00`))}`;}else if(doc.validation_status==="atende"&&doc.is_current){status="atende";detail=`${doc.original_filename}: documento vigente e validado`;}else{detail=`${doc.original_filename}: status documental ${doc.validation_status.replaceAll("_"," ")}${doc.is_current?"":"; versão não vigente"}`;}}
   const obs=`Validação automática ${new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date())}: ${detail}.`;
   await saveLevel(level,status,obs);if(refresh){setMsg(`Nível ${level.id}: ${labels[status]||status}. ${detail}.`);await loadWorkspace(workspace.client_id)}
 }catch(e){setError(err(e))}finally{setValidating(null)}}
 async function validateAll(){if(!workspace)return;setValidatingAll(true);setError("");setMsg("");try{for(const level of workspace.levels)await validateLevel(level,false);setMsg("Validação documental dos níveis SICAF concluída. Revise os níveis pendentes ou impeditivos.");await loadWorkspace(workspace.client_id)}catch(e){setError(err(e))}finally{setValidatingAll(false);setValidating(null)}}
 const pct=Number(workspace?.checkpoint?.completion_percent||0);
 return <div className="mx-auto max-w-[1400px] p-4 sm:p-6 xl:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Habilitação</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">SICAF</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Controle dos seis níveis do SICAF, com validação documental por nível, bloqueios e rastreabilidade de cada conferência.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void validateAll()} disabled={!workspace||!workspace.company_validated||loading||validatingAll} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">{validatingAll?"Validando...":"Validar documentação"}</button><button onClick={()=>void loadWorkspace()} disabled={!clientId||loading} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">Atualizar</button></div></div>
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-sm font-semibold text-slate-700">Empresa<select value={clientId} onChange={e=>setClientId(e.target.value)} className="mt-2 w-full max-w-xl rounded-xl border border-slate-200 px-4 py-3 text-sm">{companies.map(c=><option key={c.client_id} value={c.client_id}>{c.display_name} — {c.company_validation_status||"sem validação"}</option>)}</select></label>{selected&&<p className="mt-2 text-xs text-slate-500">{selected.legal_name}</p>}</section>
 {error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{msg&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{msg}</div>}
 {loading?<div className="mt-5 rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando habilitação SICAF...</div>:workspace&&<><section className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Cadastro empresarial</p><p className={`mt-2 text-lg font-bold ${workspace.company_validated?"text-emerald-700":"text-amber-700"}`}>{workspace.company_validated?"Validado":"Bloqueado"}</p><p className="mt-1 text-xs text-slate-500">{workspace.company_validation_status}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Progresso SICAF</p><p className="mt-2 text-2xl font-bold">{pct.toFixed(0)}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${Math.max(0,Math.min(100,pct))}%`}}/></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Checkpoint</p><p className="mt-2 text-lg font-bold">{workspace.checkpoint?.status||"Não iniciado"}</p><p className="mt-1 text-xs text-slate-500">{workspace.checkpoint?.blocking_reason||"Sem bloqueios cadastrais."}</p></div></section>
 {!workspace.company_validated&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>SICAF bloqueado.</strong> Primeiro conclua a validação do Cartão CNPJ em Empresas. Nenhum nível pode ser aprovado antes desse gate.</div>}
 <section className="mt-5 space-y-3">{workspace.levels.map(level=><div key={level.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wide text-blue-600">Nível {level.id}</p><h2 className="mt-1 text-lg font-bold text-slate-900">{level.name}</h2>{level.description&&<p className="mt-1 text-sm text-slate-500">{level.description}</p>}<p className="mt-2 text-xs text-slate-500">Última conferência: {level.last_checked_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(level.last_checked_at)):"não realizada"}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">{labels[level.status]||level.status}</span><button onClick={()=>void validateLevel(level)} disabled={!workspace.company_validated||validating!==null||validatingAll} className="rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{validating===level.id?"Validando...":"Iniciar"}</button></div></div><textarea value={notes[level.id]??""} onChange={e=>setNotes(v=>({...v,[level.id]:e.target.value}))} placeholder="Observações e evidências da conferência..." className="mt-4 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm"/><div className="mt-3 flex flex-wrap gap-2">{["nao_iniciado","em_preparacao","pendente","atende","impeditivo"].map(s=><button key={s} disabled={!workspace.company_validated||saving===level.id||validating!==null||validatingAll} onClick={()=>void setStatus(level,s)} className={`rounded-lg border px-3 py-2 text-xs font-semibold disabled:cursor-not-allowed disabled:opacity-40 ${level.status===s?"border-blue-300 bg-blue-50 text-blue-700":"border-slate-200 bg-white text-slate-600"}`}>{labels[s]}</button>)}</div></div>)}</section></>}</div>}
