"use client";

import { useEffect, useState } from "react";
import { loadCurrentClientDashboard, BackendDashboard } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";

type Enrollment={id:string;capability_id:string;monitoring_enabled:boolean;participation_enabled:boolean;initial_history_months:number;initial_load_status:string;incremental_sync_enabled:boolean;last_sync_at:string|null;method_version:string};
type Capability={id:string;category_id:string;selected:boolean;status:string;legal_compatibility:string;version:number;category?:{name:string;code:string}|null};
type Profile={id:string;version_no:number;is_current:boolean;created_at:string};
type ThemePreference="light"|"dark"|"system";
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}
function date(v:unknown){if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?text(v):new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)}
function err(v:unknown){if(v instanceof Error)return v.message;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return [o.message,o.details,o.hint,o.code].filter(Boolean).map(String).join(" · ")||"Erro não identificado."}return String(v)}

export default function Configuracoes(){
 const [dashboard,setDashboard]=useState<BackendDashboard|null>(null);const [enrollments,setEnrollments]=useState<Enrollment[]>([]);const [capabilities,setCapabilities]=useState<Capability[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [theme,setTheme]=useState<ThemePreference>("system");
 async function load(){setLoading(true);setError("");try{const d=await loadCurrentClientDashboard();if(!d?.client?.id)throw new Error("Tenant não associado.");setDashboard(d);const [e,c,p]=await Promise.all([supabase!.from("client_radar_enrollments").select("id,capability_id,monitoring_enabled,participation_enabled,initial_history_months,initial_load_status,incremental_sync_enabled,last_sync_at,method_version").eq("client_id",d.client.id),supabase!.from("client_capabilities").select("id,category_id,selected,status,legal_compatibility,version,category:capability_categories(name,code)").eq("client_id",d.client.id).order("updated_at",{ascending:false}),supabase!.from("client_profiles").select("id,version_no,is_current,created_at").eq("client_id",d.client.id).order("version_no",{ascending:false})]);if(e.error||c.error||p.error)throw e.error||c.error||p.error;setEnrollments((e.data??[]) as unknown as Enrollment[]);setCapabilities((c.data??[]) as unknown as Capability[]);setProfiles((p.data??[]) as Profile[]);}catch(e){setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{const stored=window.localStorage.getItem("uni-theme");if(stored==="light"||stored==="dark"||stored==="system")setTheme(stored);void load()},[]);
 function changeTheme(next:ThemePreference){setTheme(next);window.localStorage.setItem("uni-theme",next);window.dispatchEvent(new Event("uni-theme-change"));setMessage(next==="system"?"Tema definido para acompanhar o dispositivo.":`Tema ${next==="dark"?"escuro":"claro"} ativado.`)}
 async function updateEnrollment(row:Enrollment,key:"monitoring_enabled"|"incremental_sync_enabled",value:boolean){if(!supabase)return;setBusy(true);setMessage("");const {error:e}=await supabase.from("client_radar_enrollments").update({[key]:value,updated_at:new Date().toISOString()}).eq("id",row.id);if(e)setMessage(`Não foi possível salvar: ${err(e)}`);else{setMessage("Configuração atualizada.");await load()}setBusy(false)}
 if(loading)return <div className="p-8"><div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando configurações...</div></div>;
 return <div className="mx-auto max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Configurações</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Ambiente da Empresa</h1><p className="mt-2 text-sm text-slate-500">Aparência, perfil, capacidades e controles de monitoramento do tenant autenticado.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Atualizar</button></div>{error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-xl">◐</div><div><h2 className="font-bold text-slate-900">Aparência</h2><p className="mt-1 text-xs text-slate-500">Escolha como o UNI deve aparecer neste dispositivo.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{([['light','☀️','Claro','Interface clara'],['dark','🌙','Escuro','Conforto em baixa luz'],['system','⚙️','Automático','Segue o tema do dispositivo']] as const).map(([value,icon,label,description])=><button key={value} type="button" onClick={()=>changeTheme(value)} aria-pressed={theme===value} className={`rounded-xl border p-4 text-left transition ${theme===value?"border-blue-500 bg-blue-50 ring-2 ring-blue-100":"border-slate-200 bg-white hover:border-blue-300"}`}><div className="flex items-center justify-between gap-3"><span className="text-xl">{icon}</span>{theme===value&&<span className="rounded-full bg-blue-600 px-2 py-1 text-[10px] font-bold text-white">ATIVO</span>}</div><p className="mt-3 text-sm font-bold text-slate-900">{label}</p><p className="mt-1 text-xs text-slate-500">{description}</p></button>)}</div></section>
 <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Empresa",dashboard?.client?.display_name||dashboard?.client?.legal_name||"—"],["Status",text(dashboard?.client?.status)],["Perfil atual",profiles.find(p=>p.is_current)?`v${profiles.find(p=>p.is_current)?.version_no}`:"Não definido"],["Capacidades",capabilities.filter(c=>c.selected).length]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{l}</p><p className="mt-2 text-lg font-bold text-slate-900">{v}</p></div>)}</div>
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Monitoramento do Radar</h2><p className="mt-1 text-xs text-slate-500">Somente controles de monitoramento podem ser alterados aqui. Liberação para participação continua protegida pelos gates operacionais.</p><div className="mt-4 space-y-3">{enrollments.length?enrollments.map(r=><div key={r.id} className="grid gap-3 rounded-xl border border-slate-100 p-4 lg:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-semibold">Capacidade {r.capability_id.slice(0,8)}…</p><p className="mt-1 text-xs text-slate-500">Método {r.method_version} · carga {r.initial_load_status} · última sincronização {date(r.last_sync_at)} · histórico inicial {r.initial_history_months} mês(es)</p><p className="mt-1 text-xs text-slate-500">Participação: {r.participation_enabled?"habilitada pelo fluxo":"não habilitada"}</p></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={r.monitoring_enabled} disabled={busy} onChange={e=>void updateEnrollment(r,"monitoring_enabled",e.target.checked)} /> Monitoramento</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={r.incremental_sync_enabled} disabled={busy} onChange={e=>void updateEnrollment(r,"incremental_sync_enabled",e.target.checked)} /> Sincronização incremental</label></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma inscrição de Radar configurada.</p>}</div></section>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Capacidades do CNPJ</h2><div className="mt-4 space-y-2">{capabilities.length?capabilities.map(c=><div key={c.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{c.category?.name??c.category?.code??c.category_id}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${c.selected?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{c.selected?"SELECIONADA":"NÃO SELECIONADA"}</span></div><p className="mt-1 text-xs text-slate-500">Status {c.status} · compatibilidade legal {c.legal_compatibility} · versão {c.version}</p></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma capacidade cadastrada.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Histórico do perfil</h2><div className="mt-4 space-y-2">{profiles.length?profiles.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-semibold">Perfil v{p.version_no}</p><p className="mt-1 text-xs text-slate-500">Criado em {date(p.created_at)}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${p.is_current?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-500"}`}>{p.is_current?"ATUAL":"HISTÓRICO"}</span></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma versão de perfil encontrada.</p>}</div></section></div>{message&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">{message}</div>}
 </div>;
}
