"use client";

import {useEffect,useState} from "react";
import {loadCurrentClientDashboard,BackendDashboard} from "@/lib/dashboard";
import {supabase} from "@/lib/supabase";

type Enrollment={id:string;capability_id:string;monitoring_enabled:boolean;participation_enabled:boolean;initial_history_months:number;initial_load_status:string;incremental_sync_enabled:boolean;last_sync_at:string|null;method_version:string};
type Capability={id:string;category_id:string;selected:boolean;status:string;legal_compatibility:string;version:number;category?:{name:string;code:string}|null};
type Profile={id:string;version_no:number;is_current:boolean;created_at:string};
type ThemePreference="light"|"dark"|"system";
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}
function date(v:unknown){if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?text(v):new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)}
function err(v:unknown){if(v instanceof Error)return v.message;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return [o.message,o.details,o.hint,o.code].filter(Boolean).map(String).join(" · ")||"Erro não identificado."}return String(v)}
function statusLabel(v:unknown){const s=String(v??"").toLowerCase();const m:Record<string,string>={ready:"Ativo",active:"Ativo",onboarding:"Em cadastro",inactive:"Inativo",selected:"Selecionada",validated:"Validada",compatible:"Compatível",pending:"Pendente",complete:"Concluída",completed:"Concluída",running:"Em andamento",not_started:"Não iniciada",queued:"Na fila"};return m[s]||text(v)}
function legalLabel(v:unknown){const s=String(v??"").toLowerCase();const m:Record<string,string>={compatible:"Compatível",incompatible:"Incompatível",unknown:"A confirmar",pending:"Em análise",allowed:"Permitida",not_allowed:"Não permitida"};return m[s]||text(v)}

export default function Configuracoes(){
 const[dashboard,setDashboard]=useState<BackendDashboard|null>(null),[enrollments,setEnrollments]=useState<Enrollment[]>([]),[capabilities,setCapabilities]=useState<Capability[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[theme,setTheme]=useState<ThemePreference>("system");
 async function load(){setLoading(true);setError("");try{const d=await loadCurrentClientDashboard();if(!d?.client?.id)throw new Error("Nenhuma empresa está associada a esta conta.");setDashboard(d);const[e,c,p]=await Promise.all([supabase!.from("client_radar_enrollments").select("id,capability_id,monitoring_enabled,participation_enabled,initial_history_months,initial_load_status,incremental_sync_enabled,last_sync_at,method_version").eq("client_id",d.client.id),supabase!.from("client_capabilities").select("id,category_id,selected,status,legal_compatibility,version,category:capability_categories(name,code)").eq("client_id",d.client.id).order("updated_at",{ascending:false}),supabase!.from("client_profiles").select("id,version_no,is_current,created_at").eq("client_id",d.client.id).order("version_no",{ascending:false})]);if(e.error||c.error||p.error)throw e.error||c.error||p.error;setEnrollments((e.data??[])as unknown as Enrollment[]);setCapabilities((c.data??[])as unknown as Capability[]);setProfiles((p.data??[])as Profile[])}catch(e){setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{const stored=window.localStorage.getItem("uni-theme");if(stored==="light"||stored==="dark"||stored==="system")setTheme(stored);void load()},[]);
 function changeTheme(next:ThemePreference){setTheme(next);window.localStorage.setItem("uni-theme",next);window.dispatchEvent(new Event("uni-theme-change"));setMessage(next==="system"?"A aparência seguirá a configuração do dispositivo.":`Tema ${next==="dark"?"escuro":"claro"} ativado.`)}
 async function updateEnrollment(row:Enrollment,key:"monitoring_enabled"|"incremental_sync_enabled",value:boolean){if(!supabase)return;setBusy(true);setMessage("");const{error:e}=await supabase.from("client_radar_enrollments").update({[key]:value,updated_at:new Date().toISOString()}).eq("id",row.id);if(e)setMessage(`Não foi possível salvar: ${err(e)}`);else{setMessage("Configuração atualizada.");await load()}setBusy(false)}
 if(loading)return <div className="p-4 sm:p-6 xl:p-8"><div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando configurações...</div></div>;
 return <div className="mx-auto max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Configurações</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">Ambiente da empresa</h1><p className="mt-2 text-sm text-slate-500">Aparência, capacidades identificadas e controles do Radar.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">Atualizar</button></div>{error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="font-black text-slate-900">Aparência</h2><p className="mt-1 text-sm text-slate-500">Escolha como o UNI deve aparecer neste dispositivo.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{([['light','CL','Claro','Interface clara'],['dark','ES','Escuro','Conforto em baixa luz'],['system','AU','Automático','Segue o dispositivo']] as const).map(([value,code,label,description])=><button key={value} type="button" onClick={()=>changeTheme(value)} aria-pressed={theme===value} className={`rounded-xl border p-4 text-left transition ${theme===value?"border-blue-500 bg-blue-50 ring-2 ring-blue-100":"border-slate-200 bg-white hover:border-blue-300"}`}><div className="flex items-center justify-between gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-[10px] font-black text-slate-600">{code}</span>{theme===value&&<span className="rounded-full bg-blue-600 px-2 py-1 text-[10px] font-bold text-white">ATIVO</span>}</div><p className="mt-3 text-sm font-bold text-slate-900">{label}</p><p className="mt-1 text-xs text-slate-500">{description}</p></button>)}</div></section>
 <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Empresa",dashboard?.client?.display_name||dashboard?.client?.legal_name||"—"],["Situação",statusLabel(dashboard?.client?.status)],["Perfil atual",profiles.find(p=>p.is_current)?`Versão ${profiles.find(p=>p.is_current)?.version_no}`:"Não definido"],["Capacidades selecionadas",capabilities.filter(c=>c.selected).length]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-sm font-semibold text-slate-500">{l}</p><p className="mt-2 text-lg font-black text-slate-900">{v}</p></div>)}</div>
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Monitoramento do Radar</h2><p className="mt-1 text-sm text-slate-500">Controle a coleta e a atualização de oportunidades. A liberação para participar continua protegida pelas etapas do método UNI.</p><div className="mt-4 space-y-3">{enrollments.length?enrollments.map(r=>{const cap=capabilities.find(c=>c.id===r.capability_id);return <div key={r.id} className="grid gap-3 rounded-xl border border-slate-100 p-4 lg:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-bold">{cap?.category?.name||cap?.category?.code||"Capacidade monitorada"}</p><p className="mt-1 text-xs leading-5 text-slate-500">Método {r.method_version} · carga inicial {statusLabel(r.initial_load_status)} · última atualização {date(r.last_sync_at)} · histórico inicial {r.initial_history_months} mês(es)</p><p className="mt-1 text-xs text-slate-500">Participação: {r.participation_enabled?"liberada pelo fluxo":"ainda não liberada"}</p></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={r.monitoring_enabled} disabled={busy} onChange={e=>void updateEnrollment(r,"monitoring_enabled",e.target.checked)}/> Monitoramento</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={r.incremental_sync_enabled} disabled={busy} onChange={e=>void updateEnrollment(r,"incremental_sync_enabled",e.target.checked)}/> Atualização automática</label></div>}):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">O Radar ainda não foi configurado para esta empresa.</p>}</div></section>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Capacidades da empresa</h2><p className="mt-1 text-sm text-slate-500">Categorias identificadas a partir do cadastro e do perfil operacional.</p><div className="mt-4 space-y-2">{capabilities.length?capabilities.map(c=><div key={c.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold">{c.category?.name??c.category?.code??"Capacidade"}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${c.selected?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{c.selected?"SELECIONADA":"NÃO SELECIONADA"}</span></div><p className="mt-1 text-xs text-slate-500">Situação: {statusLabel(c.status)} · compatibilidade legal: {legalLabel(c.legal_compatibility)}</p></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma capacidade cadastrada.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Histórico do perfil</h2><p className="mt-1 text-sm text-slate-500">Versões mantidas para rastreabilidade das decisões.</p><div className="mt-4 space-y-2">{profiles.length?profiles.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-bold">Perfil versão {p.version_no}</p><p className="mt-1 text-xs text-slate-500">Criado em {date(p.created_at)}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${p.is_current?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-500"}`}>{p.is_current?"ATUAL":"HISTÓRICO"}</span></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma versão de perfil encontrada.</p>}</div></section></div>{message&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">{message}</div>}
 </div>;
}
