"use client";

import {FormEvent,useMemo,useState} from "react";

type Message={role:"user"|"assistant";text:string};
type Props={open:boolean;onClose:()=>void;activeModule:string;onNavigate:(module:string)=>void};

function destination(input:string,current:string){const value=input.toLocaleLowerCase("pt-BR"),clientView=["Editais aprovados","Participações","Resultados","Minha conta"].includes(current);if(/configura[cç]/.test(value))return"Configurações";if(/resultado|ganh|perdid/.test(value))return clientView?"Resultados":"Negócios";if(/participa[cç]|sess[aã]o|disputa|lance/.test(value))return clientView?"Participações":"Negócios";if(/documento|certid[aã]o|sicaf|habilita[cç]|cnpj|empresa|cadastro/.test(value))return clientView?"Minha conta":"Painel";if(/fornecedor|cota[cç]|pre[cç]o/.test(value))return clientView?"Editais aprovados":"Fornecedores";if(/intelig[eê]ncia|indicador|tend[eê]ncia/.test(value))return clientView?"Painel":"Inteligência";if(/edital|oportunidade|radar|pesquis|buscar|processo/.test(value))return clientView?"Editais aprovados":"Oportunidades";if(/dashboard|painel|resumo/.test(value))return"Painel";return current}

export default function UniAiPanel({open,onClose,activeModule,onNavigate}:Props){
 const[input,setInput]=useState(""),[messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Sou a IA do UNI. Posso ajudar a localizar oportunidades, acompanhar participações e interpretar resultados."}]);
 const context=useMemo(()=>`Contexto atual: ${activeModule}`,[activeModule]);
 function submit(e:FormEvent){e.preventDefault();const value=input.trim();if(!value)return;const target=destination(value,activeModule);const documentQuestion=/documento|certid[aã]o|sicaf|arquivo/.test(value.toLocaleLowerCase("pt-BR"));const answer=documentQuestion?"Os documentos são administrados fora do UNI Web. Aqui você pode consultar apenas o status definido pelo Owner.":target!==activeModule?`Vou abrir ${target} para continuar no contexto correto.`:`Estamos em ${activeModule}. Posso ajudar a interpretar os dados exibidos nesta página.`;setMessages(m=>[...m,{role:"user",text:value},{role:"assistant",text:answer}]);setInput("");if(!documentQuestion&&target!==activeModule)onNavigate(target)}
 if(!open)return null;
 return <aside className="fixed inset-x-2 bottom-2 top-[70px] z-50 flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl sm:inset-x-auto sm:bottom-4 sm:right-4 sm:top-[76px] sm:w-[410px]"><div className="flex items-start justify-between border-b border-slate-100 px-4 py-3"><div><h2 className="text-sm font-black text-slate-900">Fale com a IA</h2><p className="mt-1 text-xs text-slate-500">{context}</p></div><button type="button" onClick={onClose} aria-label="Fechar" className="grid h-8 w-8 place-items-center rounded-lg text-lg text-slate-500 hover:bg-slate-100">×</button></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={`${m.role}-${i}`} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3 py-2.5 text-sm leading-5 ${m.role==="user"?"bg-blue-600 text-white":"bg-slate-100 text-slate-700"}`}>{m.text}</div></div>)}</div><form onSubmit={submit} className="border-t border-slate-100 p-3"><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Pergunte sobre sua operação..." className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-400"/><button type="submit" className="rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white">Enviar</button></div></form></aside>
}
