"use client";

import { FormEvent, useMemo, useState } from "react";

type Command={module:string;action:string;text:string;filters?:Record<string,string>};
type Message={role:"user"|"assistant";text:string};
type Props={open:boolean;onClose:()=>void;activeModule:string;onNavigate:(module:string)=>void};

function localIso(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`}
function radarSearch(raw:string){const value=raw.toLocaleLowerCase("pt-BR"),now=new Date(),filters:Record<string,string>={};const year=raw.match(/\b(20\d{2})\b/)?.[1],lastDays=value.match(/(?:últimos|ultimos)\s+(\d{1,3})\s+dias/)?.[1];if(year){filters.publicationStart=`${year}-01-01`;filters.publicationEnd=`${year}-12-31`}else if(/este ano|desse ano|deste ano/.test(value)){filters.publicationStart=`${now.getFullYear()}-01-01`;filters.publicationEnd=localIso(now)}else if(/este mês|este mes|desse mês|desse mes/.test(value)){filters.publicationStart=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`;filters.publicationEnd=localIso(now)}else if(lastDays){const start=new Date(now);start.setDate(start.getDate()-Math.max(1,Number(lastDays)));filters.publicationStart=localIso(start);filters.publicationEnd=localIso(now)}if(/grande sp|grande são paulo|grande sao paulo|estado de são paulo|estado de sao paulo|\bsp\b/.test(value))filters.state="SP";if(/pncp/.test(value))filters.source="pncp";if(/compras\.gov|compras gov/.test(value))filters.source="compras_gov_br";if(/cptm/.test(value))filters.source="cptm_portal";const q=raw.replace(/\b20\d{2}\b/g,"").replace(/(?:últimos|ultimos)\s+\d{1,3}\s+dias/gi,"").replace(/(?:este|desse|deste)\s+(?:ano|mês|mes)/gi,"").replace(/\b(?:pesquise|pesquisar|procure|procurar|mostre|mostrar|apenas|somente|editais?|oportunidades?)\b/gi," ").replace(/\s+/g," ").trim();if(q)filters.query=q;return filters}
function detectModule(v:string,current:string){if(/cliente|dossi[eê]|empresa|cadastro/.test(v))return"Cliente";if(/documento|certid[aã]o|cnpj|arquivo/.test(v))return"Documentos";if(/sicaf|habilita[cç][aã]o/.test(v))return"SICAF";if(/fornecedor/.test(v))return"Fornecedores";if(/cfp|cota[cç][aã]o|pre[cç]o/.test(v))return"CFP";if(/gate.*participa[cç][aã]o|participa[cç][aã]o/.test(v))return"Gate de Participação";if(/gate.*econ[oô]mico|econ[oô]mico/.test(v))return"Gate Econômico";if(/disputa|lance/.test(v))return"Disputa";if(/relat[oó]rio/.test(v))return"Relatórios";if(/configura[cç][aã]o/.test(v))return"Configurações";if(/edital/.test(v)&&!/pesquis|radar|oportunidade/.test(v))return"Editais";if(/radar|oportunidade|pesquis|procure|buscar|busque/.test(v))return"Radar";if(/dashboard|painel|resumo/.test(v))return"Dashboard";return current}
function parse(input:string,current:string):Command{const raw=input.trim(),v=raw.toLocaleLowerCase("pt-BR"),module=detectModule(v,current);if(module==="Radar"){if(/triagem|triar/.test(v))return{module,action:"triage",text:raw};if(/an[aá]lise detalhada|motor ia/.test(v))return{module,action:"analyze",text:raw};if(/anexo|baixar.*edital|sincronizar/.test(v))return{module,action:"sync_documents",text:raw};if(/atualizar|recarregar/.test(v))return{module,action:"refresh",text:raw};return{module,action:"search",text:raw,filters:radarSearch(raw)}}if(module==="SICAF"&&/validar|conferir|revisar|concluir/.test(v))return{module,action:"validate_all",text:raw};if(module==="Documentos"&&/atualizar|recarregar/.test(v))return{module,action:"refresh",text:raw};return{module,action:"open",text:raw}}
function reply(c:Command,current:string){if(c.module==="Radar"&&c.action==="search")return"Vou abrir o Radar e aplicar os filtros que identifiquei.";if(c.module==="Radar"&&c.action==="triage")return"Vou executar a triagem da oportunidade atualmente aberta no Radar.";if(c.module==="Radar"&&c.action==="sync_documents")return"Vou sincronizar os anexos da oportunidade aberta no Radar.";if(c.module==="Radar"&&c.action==="analyze")return"Vou solicitar a Análise Detalhada da oportunidade aberta, respeitando os gates do UNI.";if(c.module==="SICAF"&&c.action==="validate_all")return"Vou abrir o SICAF e iniciar a conferência documental dos níveis. Essa ação só é executada com permissão de Owner.";if(c.module==="Documentos")return"Vou abrir a Central Documental. O Owner pode revisar os arquivos e registrar Validado, Divergente ou Pendente.";if(c.module==="Cliente")return"Vou abrir a área de Clientes/Dossiê para você administrar o cliente.";if(c.module!==current)return`Vou abrir ${c.module} para continuar essa tarefa no contexto correto.`;return`Estou no contexto de ${current}. Posso orientar a próxima etapa e executar as ações disponíveis nesse módulo.`}

export default function UniAiPanel({open,onClose,activeModule,onNavigate}:Props){const[input,setInput]=useState("");const[messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Olá! Sou o assistente operacional do UNI. Posso ajudar em Clientes e Dossiês, Documentos, SICAF, Radar, Editais, CFP, Gates, Disputa, Relatórios, Fornecedores, Dashboard e Configurações."}]);const context=useMemo(()=>`Contexto atual: ${activeModule}`,[activeModule]);
 function execute(c:Command){if(c.module!==activeModule)onNavigate(c.module);const delay=c.module===activeModule?0:150;window.setTimeout(()=>{if(c.module==="Radar")window.dispatchEvent(new CustomEvent("uni-ai-radar-command",{detail:{action:c.action,filters:c.filters}}));else if(c.module==="SICAF")window.dispatchEvent(new CustomEvent("uni-ai-sicaf-command",{detail:{action:c.action}}));else if(c.module==="Documentos")window.dispatchEvent(new CustomEvent("uni-ai-document-command",{detail:{action:c.action}}));},delay)}
 function submit(e:FormEvent){e.preventDefault();const value=input.trim();if(!value)return;const c=parse(value,activeModule);setMessages(m=>[...m,{role:"user",text:value},{role:"assistant",text:reply(c,activeModule)}]);setInput("");execute(c)}
 if(!open)return null;return <aside className="fixed bottom-4 right-4 top-[68px] z-50 flex w-[390px] max-w-[calc(100vw-2rem)] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-start justify-between gap-3 border-b border-slate-100 px-4 py-3"><div><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-600 text-xs font-black text-white">IA</span><h2 className="text-sm font-bold text-slate-900">Fale com a IA</h2></div><p className="mt-1 text-[11px] text-slate-500">{context}</p></div><button type="button" onClick={onClose} aria-label="Fechar Fale com a IA" className="rounded-lg px-2 py-1 text-slate-500 hover:bg-slate-100">×</button></div><div className="border-b border-slate-100 bg-slate-50/80 px-4 py-3 text-[11px] leading-5 text-slate-600"><strong>Exemplos:</strong> “abra o dossiê do cliente”, “validar documentos”, “conferir SICAF”, “editais de 2026 para peças automotivas”, “abra CFP”, “ir para disputa” ou “atualizar o dashboard”.</div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={`${m.role}-${i}`} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3 py-2 text-xs leading-5 ${m.role==="user"?"bg-blue-600 text-white":"bg-slate-100 text-slate-700"}`}>{m.text}</div></div>)}</div><form onSubmit={submit} className="border-t border-slate-100 p-3"><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Pergunte ou peça uma ação em qualquer módulo..." className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/><button type="submit" className="rounded-xl bg-blue-700 px-3 py-2.5 text-xs font-bold text-white hover:bg-blue-800">Enviar</button></div><p className="mt-2 text-[10px] text-slate-400">A IA respeita o contexto do módulo, o tenant selecionado e as permissões do Owner/cliente.</p></form></aside>}
