"use client";

import { useEffect, useMemo, useState } from "react";
import { BackendDashboard, loadCurrentClientDashboard } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";

type Opportunity=Record<string,unknown>;
type Gate={id:string;opportunity_id:string;cfp_item_id:string;final_unit_cost:number;suggested_unit_price:number;viability_status:string;target_markup_percent:number};
type Item={id:string;item_number:number|null;description:string;quantity:number;unit:string|null};
type Strategy={id:string;cfp_item_id:string;gate_result_id:string;target_markup_percent:number;floor_markup_percent:number;opening_unit_price:number;minimum_unit_price:number;status:string;notes:string|null;updated_at:string};
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n):"—"}
function err(v:unknown){if(v instanceof Error)return v.message;if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return [o.message,o.details,o.hint,o.code].filter(Boolean).map(String).join(" · ")||"Erro não identificado."}return String(v)}
function statusLabel(v:string){return ({planned:"PLANEJADA",active:"EM DISPUTA",stopped:"RETIRADA",won:"VENCEDORA",lost:"NÃO VENCEDORA"} as Record<string,string>)[v]??v.toUpperCase()}

export default function Disputa(){
 const [dashboard,setDashboard]=useState<BackendDashboard|null>(null);const [opportunityId,setOpportunityId]=useState("");const [gates,setGates]=useState<Gate[]>([]);const [items,setItems]=useState<Item[]>([]);const [strategies,setStrategies]=useState<Strategy[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [target,setTarget]=useState("30");const [floor,setFloor]=useState("25");
 async function boot(){setLoading(true);setError("");try{const d=await loadCurrentClientDashboard();if(!d?.client?.id)throw new Error("Tenant não associado.");setDashboard(d);if(!opportunityId&&d.opportunities.length)setOpportunityId(String(d.opportunities[0].opportunity_id));}catch(e){setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{void boot()},[]);
 async function load(){if(!supabase||!dashboard?.client?.id||!opportunityId){setGates([]);setItems([]);setStrategies([]);return}const [g,i,s]=await Promise.all([supabase.from("gate_economic_results").select("id,opportunity_id,cfp_item_id,final_unit_cost,suggested_unit_price,viability_status,target_markup_percent").eq("client_id",dashboard.client.id).eq("opportunity_id",opportunityId),supabase.from("cfp_items").select("id,item_number,description,quantity,unit").eq("client_id",dashboard.client.id).eq("opportunity_id",opportunityId),supabase.from("dispute_strategies").select("id,cfp_item_id,gate_result_id,target_markup_percent,floor_markup_percent,opening_unit_price,minimum_unit_price,status,notes,updated_at").eq("client_id",dashboard.client.id).eq("opportunity_id",opportunityId)]);if(g.error||i.error||s.error){setError(err(g.error||i.error||s.error));return}setGates((g.data??[]) as Gate[]);setItems((i.data??[]) as Item[]);setStrategies((s.data??[]) as Strategy[])}
 useEffect(()=>{void load()},[dashboard?.client?.id,opportunityId]);
 const opportunities=(dashboard?.opportunities??[]) as Opportunity[];
 const rows=useMemo(()=>gates.map(g=>{const item=items.find(i=>i.id===g.cfp_item_id);const strategy=strategies.find(s=>s.cfp_item_id===g.cfp_item_id);const t=Number(target||30),f=Number(floor||25);const opening=Number(g.final_unit_cost)*(1+t/100);const minimum=Number(g.final_unit_cost)*(1+f/100);return{g,item,strategy,opening,minimum}}),[gates,items,strategies,target,floor]);
 async function generate(){if(!supabase||!dashboard?.client?.id||!opportunityId)return;if(Number(floor)<25){setMessage("O piso de disputa não pode ficar abaixo de 25% pelo método atual.");return}if(Number(target)<Number(floor)){setMessage("O markup alvo não pode ser menor que o piso.");return}const eligible=rows.filter(r=>r.g.viability_status!=="not_viable");if(!eligible.length){setMessage("Nenhum item economicamente apto para estratégia de disputa.");return}setBusy(true);setMessage("");try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Sessão não autenticada.");for(const r of eligible){const {error:e}=await supabase.from("dispute_strategies").upsert({client_id:dashboard.client.id,opportunity_id:opportunityId,cfp_item_id:r.g.cfp_item_id,gate_result_id:r.g.id,target_markup_percent:Number(target),floor_markup_percent:Number(floor),opening_unit_price:r.opening,minimum_unit_price:r.minimum,status:r.strategy?.status??"planned",created_by:auth.user.id,updated_at:new Date().toISOString()},{onConflict:"client_id,cfp_item_id"});if(e)throw e}setMessage(`Estratégia consolidada para ${eligible.length} item(ns).`);await load()}catch(e){setMessage(`Falha ao gerar estratégia: ${err(e)}`)}finally{setBusy(false)}}
 async function setStatus(strategy:Strategy,status:string){if(!supabase)return;setBusy(true);const {error:e}=await supabase.from("dispute_strategies").update({status,updated_at:new Date().toISOString()}).eq("id",strategy.id);if(e)setMessage(`Não foi possível atualizar: ${err(e)}`);else{setMessage(`Status atualizado para ${statusLabel(status)}.`);await load()}setBusy(false)}
 if(loading)return <div className="p-8"><div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando estratégia de disputa...</div></div>;
 return <div className="mx-auto max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Disputa</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Estratégia de Lances</h1><p className="mt-2 text-sm text-slate-500">Planejamento persistido a partir do Gate Econômico. Piso operacional protegido em 25%.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Atualizar</button></div>{error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_150px_150px_auto]"><select value={opportunityId} onChange={e=>setOpportunityId(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Selecione uma oportunidade</option>{opportunities.map(o=><option key={String(o.opportunity_id)} value={String(o.opportunity_id)}>{text(o.process_number)} · {text(o.buyer_name)}</option>)}</select><label className="text-xs font-semibold text-slate-500">Markup alvo %<input value={target} onChange={e=>setTarget(e.target.value)} type="number" min="25" step="0.1" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs font-semibold text-slate-500">Piso %<input value={floor} onChange={e=>setFloor(e.target.value)} type="number" min="25" step="0.1" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><button onClick={()=>void generate()} disabled={busy||!opportunityId} className="self-end rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Processando...":"Gerar estratégia"}</button></div></section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Itens em estratégia</h2><p className="mt-1 text-xs text-slate-500">Itens inviáveis no Gate não entram na geração automática.</p></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Item","Custo final","Abertura","Piso absoluto","Margem alvo","Margem piso","Situação","Ações"].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.g.id}><td className="max-w-[320px] px-4 py-3 font-semibold">{r.item?.item_number?`${r.item.item_number} · `:""}{r.item?.description??"Item não identificado"}</td><td className="px-4 py-3">{money(r.g.final_unit_cost)}</td><td className="px-4 py-3 font-semibold">{money(r.strategy?.opening_unit_price??r.opening)}</td><td className="px-4 py-3 font-semibold text-rose-700">{money(r.strategy?.minimum_unit_price??r.minimum)}</td><td className="px-4 py-3">{r.strategy?.target_markup_percent??Number(target)}%</td><td className="px-4 py-3">{r.strategy?.floor_markup_percent??Number(floor)}%</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.g.viability_status==="not_viable"?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{r.strategy?statusLabel(r.strategy.status):r.g.viability_status==="not_viable"?"FORA DA DISPUTA":"NÃO GERADA"}</span></td><td className="px-4 py-3">{r.strategy?<div className="flex gap-1"><button disabled={busy} onClick={()=>void setStatus(r.strategy!,"active")} className="rounded border border-blue-200 px-2 py-1 font-semibold text-blue-700">Iniciar</button><button disabled={busy} onClick={()=>void setStatus(r.strategy!,"stopped")} className="rounded border border-rose-200 px-2 py-1 font-semibold text-rose-700">Retirar</button><button disabled={busy} onClick={()=>void setStatus(r.strategy!,"won")} className="rounded border border-emerald-200 px-2 py-1 font-semibold text-emerald-700">Venceu</button><button disabled={busy} onClick={()=>void setStatus(r.strategy!,"lost")} className="rounded border border-slate-200 px-2 py-1 font-semibold">Perdeu</button></div>:"—"}</td></tr>)}{rows.length===0&&<tr><td colSpan={8} className="px-4 py-8 text-center text-slate-400">Nenhum Gate Econômico consolidado para esta oportunidade.</td></tr>}</tbody></table></div></section>{message&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700">{message}</div>}
 </div>;
}
