"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { BackendDashboard,loadCurrentClientDashboard } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";

type Row=Record<string,unknown>;
type AnalysisRow={id:string;opportunity_id:string;recommendation:string;created_at:string;analysis_payload?:Record<string,unknown>|null};
const txt=(v:unknown,f="—")=>v===null||v===undefined||v===""?f:String(v);
const norm=(v:unknown)=>txt(v,"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const fmt=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)};
const money=(v:unknown)=>{const n=Number(v);return !Number.isFinite(n)||n<=0?"Não informado":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n)};
const rec=(v:unknown)=>{const s=String(v??"");return s==="aprovado"?"APROVADO":s==="aprovado_com_ressalva"?"APROVADO COM RESSALVA":s==="nao_aprovado"?"NÃO APROVADO":s==="revisao_manual"?"REVISÃO MANUAL":s.replaceAll("_"," ").toUpperCase()};

export default function Editais({onNavigate}:{onNavigate?:(module:string)=>void}){
 const[data,setData]=useState<BackendDashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[analyses,setAnalyses]=useState<AnalysisRow[]>([]),[opportunities,setOpportunities]=useState<Record<string,Row>>({}),[historyQuery,setHistoryQuery]=useState(""),[appliedHistory,setAppliedHistory]=useState("");
 async function reload(){setLoading(true);setError("");try{const d=await loadCurrentClientDashboard();if(!d?.client?.id){setData(d);setAnalyses([]);setOpportunities({});return}setData(d);if(!supabase)throw new Error("Backend indisponível.");const since=new Date(Date.now()-365*86400000).toISOString();const{data:a,error:ae}=await supabase.from("opportunity_ai_analysis_results").select("id,opportunity_id,recommendation,created_at,analysis_payload").eq("client_id",d.client.id).gte("created_at",since).order("created_at",{ascending:false});if(ae)throw ae;const list=(a??[]) as AnalysisRow[];setAnalyses(list);const ids=Array.from(new Set(list.map(x=>x.opportunity_id)));if(ids.length===0){setOpportunities({});return}const{data:o,error:oe}=await supabase.from("public_opportunities").select("id,process_number,title,object_text,buyer_name,city,state,modality,publication_date,proposal_deadline,estimated_value,source_url,lifecycle_class").in("id",ids);if(oe)throw oe;const map:Record<string,Row>={};for(const r of(o??[]) as Row[])map[String(r.id)]=r;setOpportunities(map)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os editais analisados.")}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[]);
 const recent=useMemo(()=>analyses.filter(a=>Date.now()-new Date(a.created_at).getTime()<=30*86400000),[analyses]);
 const archived=useMemo(()=>{const q=norm(appliedHistory);return analyses.filter(a=>{const age=Date.now()-new Date(a.created_at).getTime();if(age<30*86400000||age>365*86400000)return false;const o=opportunities[a.opportunity_id]??{};if(!q)return true;return norm([o.process_number,o.object_text,o.title,o.buyer_name,o.city,o.state,o.modality,a.recommendation].map(v=>txt(v,"")).join(" ")).includes(q)})},[analyses,opportunities,appliedHistory]);
 function openInternal(id:string){sessionStorage.setItem("uni-open-opportunity",id);onNavigate?.("Radar")}
 function submitHistory(e:FormEvent){e.preventDefault();setAppliedHistory(historyQuery.trim())}
 function card(a:AnalysisRow,archivedMode=false){const o=opportunities[a.opportunity_id]??{};const url=txt(o.source_url,"");return <article key={a.id} onClick={()=>openInternal(a.opportunity_id)} className="cursor-pointer rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-300"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-700">{rec(a.recommendation)}</span><span className="text-xs text-slate-400">Analisado em {fmt(a.created_at)}</span>{archivedMode&&<span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600">Arquivado</span>}</div><h2 className="mt-3 text-lg font-bold text-slate-900">{txt(o.object_text??o.title,"Objeto não informado")}</h2><p className="mt-2 text-sm font-semibold text-slate-700">{txt(o.buyer_name,"Órgão não informado")}</p><div className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-xs text-slate-400">Processo</span><p>{txt(o.process_number)}</p></div><div><span className="text-xs text-slate-400">Local</span><p>{[txt(o.city,""),txt(o.state,"")].filter(Boolean).join("/")||"—"}</p></div><div><span className="text-xs text-slate-400">Prazo</span><p>{fmt(o.proposal_deadline)}</p></div><div><span className="text-xs text-slate-400">Valor estimado</span><p>{money(o.estimated_value)}</p></div></div></div><div className="flex shrink-0 flex-col gap-2"><button type="button" onClick={e=>{e.stopPropagation();openInternal(a.opportunity_id)}} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Abrir edital no UNI</button>{url&&<button type="button" onClick={e=>{e.stopPropagation();window.open(url,"_blank","noopener,noreferrer")}} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600">Fonte oficial ↗</button>}</div></div></article>}
 return <div className="mx-auto w-full max-w-[1500px] p-4 sm:p-6 xl:p-8"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Editais</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Editais analisados</h1><p className="mt-2 max-w-4xl text-sm text-slate-500">A lista principal mostra somente editais analisados nos últimos 30 dias. O histórico abaixo permite consultar análises arquivadas dos últimos 12 meses.</p></div>{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{!data?.client?.id&&!loading?<div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Selecione um cliente na página Cliente para consultar os editais analisados.</div>:<><section className="mb-8"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Análises recentes</h2><p className="mt-1 text-sm text-slate-500">Janela operacional: últimos 30 dias.</p></div><button type="button" onClick={()=>void reload()} disabled={loading} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{loading?"Atualizando...":"Atualizar"}</button></div>{loading?<div className="rounded-2xl border bg-white p-8 text-sm text-slate-500">Carregando análises...</div>:recent.length===0?<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Nenhum edital foi analisado nos últimos 30 dias.</div>:<div className="space-y-4">{recent.map(a=>card(a))}</div>}</section><section className="rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Arquivo</p><h2 className="mt-1 text-xl font-bold">Histórico dos últimos 12 meses</h2><p className="mt-1 text-sm text-slate-500">Pesquise por processo, órgão, objeto, local, modalidade ou resultado da análise.</p></div><form onSubmit={submitHistory} className="flex w-full max-w-2xl gap-2"><input value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} placeholder="Pesquisar histórico arquivado..." className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"/><button className="rounded-xl bg-slate-800 px-5 py-3 text-sm font-semibold text-white">Pesquisar</button></form></div><div className="mt-5 text-xs text-slate-500">{archived.length} resultado(s) arquivado(s)</div><div className="mt-4 space-y-4">{archived.length===0?<div className="rounded-xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500">Nenhum edital arquivado encontrado para a pesquisa.</div>:archived.map(a=>card(a,true))}</div></section></>}</div>
}
