"use client";

import { useEffect, useMemo, useState } from "react";
import { resolveCurrentClientId } from "@/lib/dashboard";
import { supabase } from "@/lib/supabase";

type Row=Record<string,unknown>;
type Tab="Resumo"|"Itens"|"Documentos"|"Análise"|"Cotação"|"Disputa"|"Histórico";
const tabs:Tab[]=["Resumo","Itens","Documentos","Análise","Cotação","Disputa","Histórico"];
const txt=(v:unknown,f="—")=>v===null||v===undefined||String(v).trim()===""?f:String(v);
const money=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n):"—"};
const date=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR").format(d)};
const tone=(v:unknown)=>{const s=String(v||"").toLowerCase();if(["approved","queued_for_ai","matched","live"].some(x=>s.includes(x)))return"bg-emerald-50 text-emerald-700 border-emerald-200";if(["rejected","filtered_out","failed"].some(x=>s.includes(x)))return"bg-rose-50 text-rose-700 border-rose-200";return"bg-amber-50 text-amber-700 border-amber-200"};
const friendly=(v:unknown)=>{const s=String(v||"").toLowerCase();if(s.includes("queued_for_ai")||s==="approved"||s==="matched")return"Participação recomendada";if(s.includes("rejected")||s.includes("filtered_out"))return"Participação não recomendada";return"Em análise"};

export default function Oportunidades(){
 const[clientId,setClientId]=useState<string|null>(null),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<Row|null>(null),[tab,setTab]=useState<Tab>("Resumo");
 const[items,setItems]=useState<Row[]>([]),[docs,setDocs]=useState<Row[]>([]),[requirements,setRequirements]=useState<Row[]>([]),[analysis,setAnalysis]=useState<Row[]>([]),[detailBusy,setDetailBusy]=useState(false);
 async function load(){if(!supabase)return;setLoading(true);setError("");try{const id=await resolveCurrentClientId();if(!id)throw new Error("Cliente não associado.");setClientId(id);const{data,error:e}=await supabase.from("client_radar_dashboard").select("*").eq("client_id",id).order("publication_date",{ascending:false}).limit(500);if(e)throw e;setRows((data??[]) as Row[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const q=sessionStorage.getItem("uni-global-search");if(q){sessionStorage.removeItem("uni-global-search");setQuery(q)}},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.process_number,r.buyer_name,r.object_text,r.title,r.modality,r.city,r.state].some(v=>String(v??"").toLowerCase().includes(q)))},[rows,query]);
 async function openOpportunity(r:Row){if(!supabase||!clientId)return;setSelected(r);setTab("Resumo");setDetailBusy(true);const oid=String(r.opportunity_id||"");try{const[ir,dr,rr,ar]=await Promise.all([supabase.from("public_opportunity_items").select("*").eq("opportunity_id",oid).order("item_number"),supabase.from("opportunity_documents").select("id,original_filename,document_kind,validation_status,uploaded_at,storage_bucket,storage_path").eq("client_id",clientId).eq("opportunity_id",oid).order("uploaded_at",{ascending:false}),supabase.from("opportunity_requirements").select("id,title,description,requirement_kind,blocking,status,notes").eq("client_id",clientId).eq("opportunity_id",oid).order("blocking",{ascending:false}),supabase.from("opportunity_ai_analysis_queue").select("id,status,prompt_master_version,queued_at,started_at,finished_at,error_detail").eq("client_id",clientId).eq("opportunity_id",oid).order("queued_at",{ascending:false}).limit(10)]);for(const x of[ir,dr,rr,ar])if(x.error)throw x.error;setItems((ir.data??[])as Row[]);setDocs((dr.data??[])as Row[]);setRequirements((rr.data??[])as Row[]);setAnalysis((ar.data??[])as Row[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setDetailBusy(false)}}
 function navigate(module:string){window.dispatchEvent(new CustomEvent("uni-navigate",{detail:module}))}
 if(loading)return <div className="p-8 text-sm text-slate-500">Carregando oportunidades...</div>;
 return <div className="mx-auto max-w-[1540px] p-5 sm:p-7 xl:p-8">
  <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-600">Encontrar → Analisar → Precificar → Disputar → Acompanhar</p><h1 className="mt-1 text-3xl font-black tracking-tight">Oportunidades</h1><p className="mt-2 text-sm text-slate-500">O UNI organiza a análise; você decide em uma única página por processo.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar órgão, processo ou objeto" className="w-full min-w-[280px] rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm outline-none focus:border-blue-500"/><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold">Atualizar</button></div></div>
  {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
  <div className="grid gap-5 xl:grid-cols-[1fr_1.25fr]">
   <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Radar aderente</h2><p className="text-xs text-slate-500">{filtered.length} oportunidade(s)</p></div></div><div className="max-h-[760px] divide-y divide-slate-100 overflow-y-auto">{filtered.map((r,i)=>{const active=selected&&String(selected.opportunity_id)===String(r.opportunity_id);return <button key={`${txt(r.opportunity_id)}-${i}`} onClick={()=>void openOpportunity(r)} className={`block w-full p-4 text-left transition ${active?"bg-blue-50":"hover:bg-slate-50"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black text-slate-900">{txt(r.process_number)}</p><p className="mt-1 truncate text-xs text-slate-500">{txt(r.buyer_name)}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] font-bold ${tone(r.match_status||r.triage_result)}`}>{friendly(r.match_status||r.triage_result)}</span></div><p className="mt-3 line-clamp-2 text-sm text-slate-700">{txt(r.object_text,r.title?String(r.title):"Objeto não informado")}</p><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-slate-400"><span>{txt(r.modality)}</span><span>{txt(r.city)} / {txt(r.state)}</span><span>Prazo {date(r.proposal_deadline)}</span></div></button>})}{filtered.length===0&&<div className="p-8 text-center text-sm text-slate-400">Nenhuma oportunidade encontrada.</div>}</div></section>
   <section className="min-h-[640px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{!selected?<div className="grid min-h-[640px] place-items-center p-10 text-center"><div><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-blue-600">▤</div><h2 className="mt-4 text-lg font-black">Selecione uma oportunidade</h2><p className="mt-2 max-w-md text-sm text-slate-500">Resumo, itens, documentos, análise, cotação, disputa e histórico ficarão concentrados aqui.</p></div></div>:<><div className="border-b bg-slate-50/70 p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-blue-600">{txt(selected.modality)}</p><h2 className="mt-1 text-xl font-black">{txt(selected.process_number)}</h2><p className="mt-1 text-xs text-slate-500">{txt(selected.buyer_name)} · {txt(selected.city)} / {txt(selected.state)}</p></div><span className={`self-start rounded-full border px-3 py-1.5 text-xs font-black ${tone(selected.match_status||selected.triage_result)}`}>{friendly(selected.match_status||selected.triage_result)}</span></div></div><div className="flex overflow-x-auto border-b bg-white px-3">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-xs font-bold ${tab===t?"border-blue-600 text-blue-700":"border-transparent text-slate-500"}`}>{t}</button>)}</div><div className="p-5">{detailBusy?<p className="text-sm text-slate-500">Carregando detalhes...</p>:<>
    {tab==="Resumo"&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Publicação",date(selected.publication_date)],["Prazo",date(selected.proposal_deadline)],["Valor estimado",money(selected.estimated_total_value)],["Itens",String(items.length)]].map(([k,v])=><div key={k} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase text-slate-400">{k}</p><p className="mt-1 text-sm font-black text-slate-800">{v}</p></div>)}</div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Objeto</p><p className="mt-2 text-sm leading-6 text-slate-700">{txt(selected.object_text,selected.title?String(selected.title):"Objeto não informado")}</p></div><div className="grid gap-3 sm:grid-cols-3"><button onClick={()=>setTab("Análise")} className="rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white">Ver análise</button><button onClick={()=>setTab("Cotação")} className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-black">Precificar</button><button onClick={()=>setTab("Disputa")} className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-black">Ir para disputa</button></div></div>}
    {tab==="Itens"&&<div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-xs"><thead className="bg-slate-50"><tr>{["Item","Descrição","Qtd.","Unidade","Estimado unit.","Estimado total"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{items.map(it=><tr key={String(it.id)}><td className="px-3 py-3 font-bold">{txt(it.item_number)}</td><td className="px-3 py-3">{txt(it.description)}</td><td className="px-3 py-3">{txt(it.quantity)}</td><td className="px-3 py-3">{txt(it.unit)}</td><td className="px-3 py-3">{money(it.estimated_unit_value)}</td><td className="px-3 py-3">{money(it.estimated_total_value)}</td></tr>)}{items.length===0&&<tr><td colSpan={6} className="p-6 text-center text-slate-400">Nenhum item sincronizado.</td></tr>}</tbody></table></div>}
    {tab==="Documentos"&&<div className="space-y-2">{docs.map(d=><div key={String(d.id)} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="text-sm font-bold">{txt(d.original_filename)}</p><p className="mt-1 text-[10px] text-slate-400">{txt(d.document_kind)} · {date(d.uploaded_at)}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{txt(d.validation_status)}</span></div>)}{docs.length===0&&<p className="py-6 text-center text-sm text-slate-400">Nenhum documento disponível.</p>}</div>}
    {tab==="Análise"&&<div className="space-y-4"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><p className="text-[10px] font-bold uppercase tracking-wide text-blue-600">Decisão do UNI</p><p className="mt-2 text-xl font-black text-slate-900">{friendly(selected.match_status||selected.triage_result)}</p><p className="mt-2 text-sm text-slate-600">O Gate e a leitura documental ficam no motor. Aqui aparecem somente a recomendação, exigências e pendências relevantes.</p></div><div><h3 className="text-sm font-black">Exigências identificadas</h3><div className="mt-3 space-y-2">{requirements.map(r=><div key={String(r.id)} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{txt(r.title)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{txt(r.description,"Sem descrição adicional")}</p></div>{r.blocking===true&&<span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-bold text-rose-700">Bloqueante</span>}</div></div>)}{requirements.length===0&&<p className="text-xs text-slate-400">As exigências estruturadas ainda não estão disponíveis.</p>}</div></div><div><h3 className="text-sm font-black">Execuções recentes</h3><div className="mt-3 space-y-2">{analysis.map(a=><div key={String(a.id)} className="flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{txt(a.prompt_master_version)}</span><b>{txt(a.status)}</b></div>)}{analysis.length===0&&<p className="text-xs text-slate-400">Nenhuma análise detalhada executada.</p>}</div></div></div>}
    {tab==="Cotação"&&<div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Cotação e formação de preço</h3><p className="mt-2 text-sm text-slate-500">Custos, frete, tributos e margens são tratados no módulo econômico do UNI.</p><button onClick={()=>navigate("CFP")} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">Abrir cotação</button></div><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Viabilidade econômica</h3><p className="mt-2 text-sm text-slate-500">O Gate Econômico consolida a margem viável por item antes da disputa.</p><button onClick={()=>navigate("Gate Econômico")} className="mt-5 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-black">Ver viabilidade</button></div></div>}
    {tab==="Disputa"&&<div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">Sessão pública</h3><p className="mt-2 text-sm text-slate-500">Estratégia de lance, piso de margem e acompanhamento pós-disputa continuam preservados no motor do UNI.</p><button onClick={()=>navigate("Disputa")} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">Abrir disputa</button></div>}
    {tab==="Histórico"&&<div className="space-y-3"><div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-black">Oportunidade identificada</p><p className="mt-1 text-[11px] text-slate-400">{date(selected.publication_date)}</p></div>{analysis.map(a=><div key={String(a.id)} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-black">Análise UNI · {txt(a.status)}</p><p className="mt-1 text-[11px] text-slate-400">{date(a.queued_at)}</p></div>)}</div>}
   </>}</div></>}</section>
  </div>
 </div>
}
